### ISSUE TITLE
Query dynamodb with list/map datatypes

### ISSUE THREAD

**Issue by nazeemmohammed** [awslabs/aws-athena-query-federation#100]
Getting below error when querying dynamodb table with list and map data types. Works fine with regular data types.

[ErrorCode: INTERNAL_ERROR_QUERY_ENGINE] Amazon Athena an experienced an internal error while executing this query. Please contact AWS support for further assistance. You will not be charged for this query. We apologize for the inconvenience.

**Comment by avirtuos** [comment]
What version of the connector are you using?

**Comment by nazeemmohammed** [comment]
Query Id: 23bf4c99-cd80-431e-990d-5a092a846a99.
Connector Version - 2020.4.1

**Comment by avirtuos** [comment]
Thanks.

**Comment by atennak1** [comment]
Thanks for opening @nazeemmohammed .  Could you paste the stacktrace from the function Cloudwatch logs?  You should find it under the /aws/lambda/AthenaDynamoDB log group.

Also try re-deploying the connector with a all lowercase name and see if that resolves your issue.

**Comment by nazeemmohammed** [comment]
@atennak1  tried with lowercase name function and it still gives same error. The Query Id: 6fcf5702-cf87-4b2a-b658-1a04e64c2ba6.
I could not see stacktrace in cloudwatch logs under - /aws/lambda/AthenaDynamoDB log group.

**Comment by shurvitz** [comment]
Fixed by #228 and #232
