### ISSUE TITLE
[BUG] Unable to connect MongoDB Atlas with connector docdb

### ISSUE THREAD

**Issue by danim47c** [awslabs/aws-athena-query-federation#1048]
**Describe the bug**
I am not able to connect to my MongoDB Atlas cluster with the connector.

**To Reproduce**
1. Set url to
```
mongodb://user:password@xx-xxxxxxx-shard-00-00.xxxxxxx.mongodb.net:27017,xx-xxxxxxx-shard-00-01.xxxxxxx.mongodb.net:27017,xx-xxxxxxx-shard-00-02.xxxxxxx.mongodb.net:27017/?ssl=true&replicaSet=atlas-xxxxxx-shard-0&authSource=admin&retryWrites=true&w=majority
```

2. After this log:
```
No server chosen by com.mongodb.client.internal.MongoClientDelegate$1@71329995 from cluster description ClusterDescription{type=REPLICA_SET, connectionMode=MULTIPLE, serverDescriptions=[ServerDescription{address=xx-xxxxxxx-shard-00-01.xxxxxxx.mongodb.net:27017, type=UNKNOWN, state=CONNECTING}, ServerDescription{address=xx-xxxxxxx-shard-00-00.xxxxxxx.mongodb.net:27017, type=UNKNOWN, state=CONNECTING}, ServerDescription{address=xx-xxxxxxx-shard-00-02.xxxxxxx.mongodb.net:27017, type=UNKNOWN, state=CONNECTING}]}. Waiting for 30000 ms before timing out
```

3. Getting following error:
```
com.mongodb.MongoSocketOpenException: Exception opening socket
	at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:70) ~[task/:?]
	at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:128) ~[task/:?]
	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:117) ~[task/:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:?]
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[?:?]
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[?:?]
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[?:?]
	at java.net.SocksSocketImpl.connect(Unknown Source) ~[?:?]
	at java.net.Socket.connect(Unknown Source) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source) ~[?:?]
	at com.mongodb.internal.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:64) ~[task/:?]
	at com.mongodb.internal.connection.SocketStream.initializeSocket(SocketStream.java:79) ~[task/:?]
	at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:65) ~[task/:?]
	... 3 more
```

**Expected behavior**
I read another issue about this same problem, I replicate the solution but still was not able to connect.

**Connector Details (please complete the following information):**
 - 2023.6.1
 - MongoDB

**Comment by akuzin1** [comment]
Can you provide how you've configured your Network and Database Access for your MongoDB cluster?

**Comment by danim47c** [comment]
> Can you provide how you've configured your Network and Database Access for your MongoDB cluster?

<img width="1258" alt="image" src="https://user-images.githubusercontent.com/48626234/220403069-c657151b-b33c-492f-8a68-b8984bfe6cfa.png">

**Comment by akuzin1** [comment]
Can you try to use the SRV string? 
Format: "mongodb+srv://user:password@<hostname>/?<options>"

**Comment by danim47c** [comment]
I first tried that but it didn't worked, I have tried it again and the same

**Comment by akuzin1** [comment]
Ok got it. I have two follow up questions.
1. Have you been able to access your cluster from a different driver using the connection string you've provided?
For example as such:
```
import pymongo
from pymongo import MongoClient

cluster = MongoClient("mongodb+srv://user:password@<hostname>/?retryWrites=true&w=majority")

for db in cluster.list_databases():
    print(db)
```
2. Is your Lambda configured in a VPC?

**Comment by akuzin1** [comment]
Due to inactivity it appears you may have resolved the issue you encountered, however, if issue persists feel free to reopen ticket. Thank you.

**Comment by vireshsolanki** [comment]
you have to add mongodb://<username>:<password>@<cluster-url>:<port>/?authSource=admin&readPreference=secondaryPreferred&retryWrites=false&tls=true

**Comment by gsvitak-ionna** [comment]
@vireshsolanki can you please provide some more details. I have an atlas cluster I am trying to connect to Athena using the latest version of the federated data connector. I am having trouble since I cannot specify the mongodb+srv: in the connection string. 

I am not sure what to use for the hostname with mongodb: .  

Can you please provide a sample connection string for reference?

**Comment by vireshsolanki** [comment]
@gsvitak-ionna You must use this string "mongodb://<username>:<password>@<cluster-url>:<port>/?authSource=admin&readPreference=secondaryPreferred&retryWrites=false&tls=true"
