### ISSUE TITLE
All queries failing: DynamoDB connector

### ISSUE THREAD

**Issue by houmark** [awslabs/aws-athena-query-federation#107]
**Describe the bug**
All queries failing with the DynamoDB connector:

> Your query has the following error(s):
>
> [ErrorCode: INTERNAL_ERROR_QUERY_ENGINE] Amazon Athena an experienced an internal error while executing this query. Please contact AWS support for further assistance. You will not be charged for this query. We apologize for the inconvenience.
>
> This query ran against the "default" database, unless qualified by the query. Please post the error message on our forum or contact customer support with Query Id: aed23b45-7960-4d3f-8669-13ad1f84d738.

This seems to have started within the last 3 hours.

Maybe this is a temporary issue with the service, but I don't see anything in any health dashboard, so reporting it here to see if anyone can cast light on the exact issue.

**Comment by avirtuos** [comment]
We are looking into it. Seems like a recent change is causing this. I'll update once our On-Call confirms. ETA for next update is probably 15 minut s.

**Comment by sethtdenney** [comment]
Roll-back in progress. Will update when rollback is complete.

**Comment by sethtdenney** [comment]
Rollback complete. We apologize for the inconvenience!

**Comment by avirtuos** [comment]
Still investigating, will update again shortly.

**Comment by avirtuos** [comment]
Thanks team. @houmark  can you confirm service is restored for you?

**Comment by houmark** [comment]
Yes, it seems to be loading again!

**Comment by avirtuos** [comment]
Great.
