### ISSUE TITLE
[FEATURE] Allow multiplexing handler connection strings to be configured via SAM templates

### ISSUE THREAD

**Issue by ned9** [awslabs/aws-athena-query-federation#1073]
Connectors which provide a multiplexing handlers to route queries from data source catalogues to specific target databases rely on configured lambda environment variables to route incoming queries to the appropriate target database. The environment variable names take the form `$<catalog>_connection_string`, where `catalog` corresponds to the name of the Athena data source from which queries will be routed to the location specified by the connection string in the value of the variable.

Currently, there's no way to configure these environment variables from the SAM templates of the connectors, which means that, unless I'm missing something, none of the multiplexing connectors can be configured for automated deployment through eg the CDK.

The simplest workaround to this is to simply not use multiplexing handlers, and have separate connectors for each target database, however this has the downside of potentially greatly increasing the surface area of the deployed stack when there are many different databases, is is the case for our use-case.

See these related issues: #143, #517

This limitation affects the following connectors, which all provide multiplexing handlers:
* athena-cloudera-hive
* athena-cloudera-impala
* athena-datalakegen2
* athena-db2
* athena-hortonworks-hive
* athena-mysql
* athena-oracle
* athena-postgresql
* athena-redshift
* athena-saphana
* athena-snowflake
* athena-sqlserver
* athena-synapse
* athena-teradata

**Comment by henrymai** [comment]
Hi @ned9 

It looks like you can use CDK to update environment variables after deployment: https://stackoverflow.com/questions/70825543/aws-cdk-update-existing-lambda-environment-variables/70832790#70832790

Have you tried that yet?

**Comment by henrymai** [comment]
Closing out this response since there's been no response for 3 weeks. Please re-open if the link above doesn't help.

**Comment by ned9** [comment]
Apologies for the slow reply!

Thanks for digging up that candidate strategy. It's possible that could do what we need, but it wasn't clear to us that it would work in the context of a single stack hydration, where the existing resource being targeted was only just created in the same deployment. Given there's some degree of uncertainty, we decided not to risk any more delays and went with the safe option of just spinning up a separate connector lambda for each database that is added.
