### ISSUE TITLE
[QUESTION] General question

### ISSUE THREAD

**Issue by billybonks** [awslabs/aws-athena-query-federation#110]
I have a question that I don't think is related to a bug or feature request. 
I am getting the following error when trying to use the postgres jdbc connection

`Encountered an exception[java.lang.IllegalArgumentException] from your LambdaFunction executed in context[retrieving meta-data] with message[No enum constant com.amazonaws.connectors.athena.jdbc.connection.JdbcConnectionFactory.DatabaseEngine.POSTGRESQL]`

**Comment by atennak1** [comment]
Hi it looks like you connection string my be misconfigured.  It should start with `postgres://` not `postgresql://`

**Comment by billybonks** [comment]
That seems about right thanks :)
