### ISSUE TITLE
Add column in bulk ---'(' comes with first column and there is not any type selected in last column.

### ISSUE THREAD

**Issue by chaurasiyag** [awslabs/aws-athena-query-federation#1124]
While creating table from here

```

```
<img width="397" alt="Screenshot 2023-03-19 at 11 57 22 AM" src="https://user-images.githubusercontent.com/55340948/226158163-2d1cc777-edb1-4a03-9b54-8cdabc407a2f.png">

 When it comes to add column in bulk , you paste all the column name with its data type , then   **(**  comes with  the first column. And there is not any entry of datatype for the last column.

<img width="777" alt="Screenshot 2023-03-19 at 11 56 13 AM" src="https://user-images.githubusercontent.com/55340948/226158088-271d270f-6e8e-4a7d-bfa2-04089b77a14e.png">

**Comment by burhan94** [comment]
Hi, this doesn't look like a bug related to Athena Query Federation. Please open a ticket with AWS support.
