### ISSUE TITLE
[BUG] Discontinued driver still in use with connector Redshift Connector

### ISSUE THREAD

**Issue by egriffith** [awslabs/aws-athena-query-federation#1156]
**Describe the bug**
If I am reading the pom.xml file correctly, the supplied version of the Redshit JDBC driver is still on version 1.2.55, which has been discontinued and has been superseded by the 2.1 JDBC driver version since at least 2020, if not longer. 

**To Reproduce**
1. Reference https://github.com/awslabs/aws-athena-query-federation/blob/master/athena-redshift/pom.xml

**Expected behavior**
At least annual JDBC driver updates to stay ontop of bugs and security fixes. 

**Screenshots / Exceptions / Errors**
See Pom.xml

**Connector Details (please complete the following information):**
 - Version: 2023.12.1  <--- This itself might be a bug in the version Ids. 2023 December release 1? Maybe 2022 was intended? We aren't in December yet.
 - Name: Redshift

**Comment by henrymai** [comment]
@burhan94 has addressed this now with his patch here: https://github.com/awslabs/aws-athena-query-federation/pull/1168

@chngpe cut a release today containing this patch: https://github.com/awslabs/aws-athena-query-federation/releases/tag/v2023.13.1

Which is also published to SAR under the same version: https://us-east-1.console.aws.amazon.com/lambda/home?region=us-east-1#/create/app?applicationId=arn:aws:serverlessrepo:us-east-1:292517598671:applications/AthenaRedshiftConnector


> Version: 2023.12.1 <--- This itself might be a bug in the version Ids. 2023 December release 1? Maybe 2022 was intended? We aren't in December yet.

No this is not a bug. Our versioning scheme is `<year>.<week of year>.<iteration of week>`, you can also see this with the 2022 releases: https://github.com/awslabs/aws-athena-query-federation/releases?q=2022&expanded=true

Thanks for filing this ticket. Please let us know if there's anything else we can help with.
