### ISSUE TITLE
[BUG] Potential wrong results for some queries with DynamoDB connector

### ISSUE THREAD

**Issue by houmark** [awslabs/aws-athena-query-federation#122]
**Describe the bug**
I'm at the risk of sounding really stupid here, but I wanted to check in here, to rule out my theory.

I have a simple query like this one:
```sql

SELECT * FROM table
WHERE (this = 'that' OR this = 'other') AND something = 'foo'
```

Both fields queried are string/varchar.

That should correctly consider the OR's with the AND, but I seem to get wrong results when doing that. Exactly what it's returning and how the query is interpreted wrong, I am not sure about at this time, but if there's any potential reason to this theory, I'd be happy to dig deeper into it.

I've tried all kinds of things and been reading documentation to see if Athena or Presto handled this different than normal SQL db's, but I did not find such info, which led me to think that maybe the connector had a bug with queries like that?

Doing a `this IN ('one', 'two')` also does not produce the correct results, but doing `NOT IN ('one')` did — meaning just one value in the `IN` seems to work.

Again, there's a high risk I missed something completely obvious or am doing it all wrong, but I don't really have other ideas than trying my luck here.

**Connector Details (please complete the following information):**
 - Version: latest
 - DynamoDB
 - Athena Query ID (for a query returning the wrong results): 8c1d8687-f30b-40ca-963c-ae6342a2ebb8

**Comment by avirtuos** [comment]
Can you describe what you are getting in the results vs what you expect? It's also important to call out if any of the queried fields are part of the ddb range or hash key.

**Comment by houmark** [comment]
Sorry, not sure what the ddb range or hash key means here? Still learning all the basics.

I will try a simpler test case to try to provide expected results vs. actual results. Create a simple table with just a few records, should make it easy to test.

**Comment by houmark** [comment]
Here's a test case which should be easy to replicate, but if you need more info on our setup in relation to DynamoDB, I'd be happy to provide it private:

Query 1 (wrong result):

```
SELECT status, phonenumber
FROM "db"."default"."member_1234_prod"
WHERE phonenumber IS NOT NULL AND (status = 'past_due' OR status = 'canceled')
```

Results returned: phonenumber is always set, all records have status past_due, total records: 28, incorrect amount.

Query 2 (slightly changed AND part to see if first or last OR is used):
```
SELECT status, phonenumber
FROM "db"."default"."member_1234_prod"
WHERE phonenumber IS NOT NULL AND (status = 'canceled' OR status = 'past_due')
```

Results: Same result as query 1, all have phonenumber, all records have status past_due and 28 records returned, incorrect amount.

Query 3 (removing OR and past_due, making it a simple AND based query):
```
SELECT status, phonenumber
FROM "db"."default"."member_1234_prod"
WHERE phonenumber IS NOT NULL AND status = 'canceled'
```
Result: phonenumber always has a value, status is always canceled, 475 results, correct amount.

Query 4 (simple AND with past_due):
```
SELECT status, phonenumber
FROM "db"."default"."member_1234_prod"
WHERE phonenumber IS NOT NULL AND status = 'past_due'
```
Result: phonenumber set for all items, status is past_due for all items, total records returned: **14** which is the correct amount!

I have done similar queries with `IN` to try out if there was a problem with multiple OR's but it seems to produce the same incorrect results, which led me to believe this may be a connector issue in the way it's converting the query to a DynamoDB query/scan.

**Comment by avirtuos** [comment]
@houmark Thanks for the added info. We are currently prioritizing items that are required for us to get these features out of 'Preview' and into GA (aka production). This means it might take us a while to prioritize this item but rest assured I consider it a GA blocker and will be addressed before GA. It just might take us a couple weeks to get someone assigned to it as we are closing other bugs and critical items.

**Comment by atennak1** [comment]
@houmark could you email me the table schema and some sample data?  I could not replicate this with fake basic/similar data.

**Comment by atennak1** [comment]
Also a screenshot of the table details in the DDB Console would help. Thanks.

**Comment by houmark** [comment]
Thanks for the review @atennak1 — sorry you couldn't replicate it. I will try to send along the requested information by email as soon as I have time (I believe I still have your email from last time).

When you say table schema is that then from AppSync? As mentioned before, we run on Amplify which means I am creating the schema in Amplify which uses Appsync and that creates the DynamoDB table.

The screenshot of the DynamoDB Console, what should it show?

**Comment by atennak1** [comment]
Couple of options for getting the schema:
1. Amplify schema may work for me but I don't know that those look like.  We can start with it.
2. Glue schema if the table is registered there (you can also create a Glue crawler for the table and get the schema out that way)
3. In CW logs for the lambda function, the inferred schema gets logged in the response for GetTable operation, or as the input for some of the other operations.
4. It may also be good enough to just take a screenshot of the "Items" tab for the table in the DynamoDB Console.

The DynamoDB Console screenshot should show the "Overview" tab for the table, where details such as "Primary partition key" are shown.

**Comment by avirtuos** [comment]
@atennak1  @houmark Just wanted to check in on this issue since the implications of such a bug would be substantial, where did we land. Is this persisting?

**Comment by houmark** [comment]
@avirtuos I'm sorry, I have not had the time to collect the information requested by @atennak1 but I will try as soon as possible (the issue persists here). If I could give you access to my development setup it would be even better and easier for debugging, but I don't know if that's an option?

**Comment by ykrystal** [comment]
Closing as we are not able to replicate this issue and there has not been any update. Please reopen if this issue persists.
