### ISSUE TITLE
com.amazonaws.SdkClientException with Postgres JDBC connector

### ISSUE THREAD

**Issue by vaidykal** [awslabs/aws-athena-query-federation#125]
I created a Federated Data Source to connect to an RDS-Postgres source system. It uses the MultiplexingJdbcCompositeHandler. I am trying to copy the data across from a source table to S3 converting them to Parquet format in that process.

When I run a CTAS command to copy the data across from a particular table (with a simple CREATE TABLE ... SELECT * FROM catalog.SOURCETABLENAME) I get an SdkClientException error. A similar CTAS for smaller tables (with a few thousand rows) works successfully.

In this case, the source table contains 826K rows.

The error encountered is:

*Your query has the following error(s):

GENERIC_USER_ERROR: Encountered an exception[com.amazonaws.SdkClientException] from your LambdaFunction[arn:aws:lambda:us-east-1:078426083876:function:postgresrecordfn] executed in context[S3SpillLocation{bucket='xyz', key='xyz/jdbc/84be7573-544e-42dd-b147-2b710ff2d5c5/dd8eba77-dd66-4df4-b7dc-210accfd1764', directory=true}] with message[Unable to execute HTTP request: Connect to xyz.s3.amazonaws.com:443 [xyz.s3.amazonaws.com/52.217.4.132] failed: **connect timed out**]. You may need to manually clean the data at location 's3://efg/athenaqueries/Unsaved/2020/03/09/tables/84be7573-544e-42dd-b147-2b710ff2d5c5' before retrying. Athena will not delete data in your account.
This query ran against the "targetschema" database, unless qualified by the query. Please post the error message on our forum or contact customer support with Query Id: 84be7573-544e-42dd-b147-2b710ff2d5c5.*

**Comment by atennak1** [comment]
It looks like you may be running the Connector lambda in a VPC?  If so you may need to [setup a gateway endpoint](https://docs.aws.amazon.com/vpc/latest/userguide/vpce-gateway.html).

**Comment by avirtuos** [comment]
> It looks like you may be running the Connector lambda in a VPC? If so you may need to [setup a gateway endpoint](https://docs.aws.amazon.com/vpc/latest/userguide/vpce-gateway.html).

@vaidykal any update on the above suggestion from @atennak1 ? Please reopen this issue if the problem persists.
