### ISSUE TITLE
[BUG] copyRows does not support DATEMILLI types

### ISSUE THREAD

**Issue by soojinj** [awslabs/aws-athena-query-federation#128]
**Describe the bug**
When [copyRows](https://github.com/awslabs/aws-athena-query-federation/blob/master/athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/data/BlockUtils.java#L458) is called and the block contains a DATE/DATEMILLI vectors (which are currently supported), we come across a type incompatibility issue.

We only support java.time.* types when setting, but when we readObject from the fieldVector, we get  org.joda.time.* types.

**To Reproduce**
1. Go to [BlockUtils unit test](https://github.com/awslabs/aws-athena-query-federation/blob/master/athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/data/BlockUtilsTest.java#L50)
2. Add data types `.addField("col3", Types.MinorType.TIMESTAMPMILLI.getType())`
3. Add data values of type java.time.LocalDateTime
4. The test will fail on CopyRows as org.joda.time.LocalDateTime is not supported in [setValue](https://github.com/awslabs/aws-athena-query-federation/blob/master/athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/data/BlockUtils.java#L213-L242)

**Comment by avirtuos** [comment]
@soojinj do you know what the fix is? I couldn't grok it from the above. It also wasn't clear what problem this manifests as? inability to use that type in a query or just inability to use that function for other purposes outside query path.

**Comment by soojinj** [comment]
should be addressed with https://github.com/awslabs/aws-athena-query-federation/pull/139
