### ISSUE TITLE
[BUG] Timestamps in sub documents are incorrect with connector DocumentDB (MongoDB)

### ISSUE THREAD

**Issue by markopy** [awslabs/aws-athena-query-federation#1316]
Making an Athena query against a MongoDB database which contains documents that have timestamps in a nested field either errors or returns incorrect timestamps.

Consider a MongoDB collection with the following data:
```
[
  {
    _id: ObjectId("647f3e00215323232221127b"),
    test_case: 'milliseconds',
    top_level: ISODate("2023-06-06T13:33:09.378Z"),
    a: { second_level: ISODate("2023-06-06T13:33:09.378Z") }
  },
  {
    _id: ObjectId("647f3e00215323232221127c"),
    test_case: 'no_milliseconds',
    top_level: ISODate("2023-06-06T13:33:09.000Z"),
    a: { second_level: ISODate("2023-06-06T13:33:09.000Z") }
  }
]
```

Athena infers the schema correctly as
```
_id	varchar
test_case	varchar
top_level	timestamp
a	struct<second_level:timestamp>
```

First observe the the top level fields are returned correctly:
```
SELECT test_case, top_level FROM test
=>
#	test_case	top_level
1	milliseconds	2023-06-06 13:33:09.378
2	no_milliseconds	2023-06-06 13:33:09.000
```

The first error occurs when trying to retrieve the timestamp field inside the sub document/struct `a`:
```
SELECT a.second_level FROM test WHERE test_case = 'milliseconds'
=>
SERIALIZATION_ERROR: Could not serialize column 'second_level' of type 'timestamp(3)' at position 1:1
```
Note that MongoDB date objects never have more than millisecond precision so this error should not happen.

If we then try to use a timestamp with only second resolution we don't get an error but the date is entirely incorrect:
```
SELECT a.second_level FROM test WHERE test_case = 'no_milliseconds'
=>
#	second_level
1	1970-01-20 12:20:58.389
```

**Connector Details (please complete the following information):**
 - Version: serverlessrepo:semanticVersion 2023.21.1
 - Name: AthenaDocumentDBConnector

**Comment by markopy** [comment]
Thinking about this some more, there must be some type conversion issue in the connector or some other Athena layer.
`2023-06-06 13:33:09` converted to unix epoch seconds and divided by 1000 results in `1970-01-20 12:20:58`. This doesn't explain the added `389` milliseconds though.

**Comment by AbdulR3hman** [comment]
Hi, can you please provide us with queryid? And can you perform the same tests on both V2/V3 and provide us with query IDs for both tests? thanks

**Comment by markopy** [comment]
Athena V2 appears to work correctly:

```
SELECT a.second_level FROM test WHERE test_case = 'milliseconds'
=>
#	second_level
1	2023-06-06 13:33:09.378

Query Id: 926be188-59af-4464-b7cd-5f26de1a4d39
```

```
SELECT a.second_level FROM test WHERE test_case = 'no_milliseconds'
=>
#	second_level
1	2023-06-06 13:33:09.000

Query Id: 392b0ad6-41df-4557-9c2c-bbf0244de749

```

Athena V3 incorrect results with query ids:
```
SELECT a.second_level FROM test WHERE test_case = 'milliseconds'
=>
SERIALIZATION_ERROR: Could not serialize column 'second_level' of type 'timestamp(3)' at position 1:1

Query Id: e54b056f-ebe5-4fbb-831c-ea36c66ece6e
```

```
SELECT a.second_level FROM test WHERE test_case = 'no_milliseconds'
=>
#	second_level
1	1970-01-20 12:20:58.389

Query Id: c1d18694-57da-4e46-8ac6-dfdd2b17bed0

```

**Comment by AbdulR3hman** [comment]
Apologies for late respond, we were working in the background for a fix. 

There are two things to point out here; first is that in V3, the timestamp expected is Milliseconds; check [V3 Breaking Changes](https://docs.aws.amazon.com/athena/latest/ug/engine-versions-reference-0003.html#engine-versions-reference-0003-breaking-changes) for more info.

However, the second thing is that we found a fix for the bug you've reported, and I've put in a code change internally to fix this. Should be released with the next release. 

thank you for reporting this.

**Comment by n-dallacosta** [comment]
Hi @AbdulR3hman, do you know when the next release will be released?

**Comment by AbdulR3hman** [comment]
Hi @n-dallacosta, I can't provide an exact date; however it should not be too long.
