### ISSUE TITLE
[BUG] java.lang.NoClassDefFoundError: com/google/common/base/MoreObjects

### ISSUE THREAD

**Issue by danielhaviv** [awslabs/aws-athena-query-federation#132]
All throughout the project there are debug logging messages such as: 

- MetadataHandler.java:doHandleRequest:                    ` logger.info("doHandleRequest: response[{}]", response);`

- ExampleRecordHandler.java:GetSplitsResponse `logger.info("doGetSplits: enter - " + request);`

the toString implementation of these classes requires Guava which is not included in the project.

**Comment by atennak1** [comment]
Guava is a dependency in the SDK pom

https://github.com/awslabs/aws-athena-query-federation/blob/master/athena-federation-sdk/pom.xml#L91

**Comment by danielhaviv** [comment]
You're right, seems I'm dragging in an old version with one of my deps.
