### ISSUE TITLE
[FEATURE] Performance enhancement of case-insensitive table search  

### ISSUE THREAD

**Issue by dbadaya1** [awslabs/aws-athena-query-federation#1334]
https://github.com/awslabs/aws-athena-query-federation/pull/1289

The idea is to query information_schema table for table name using predicate WHERE lower(table_name) = 'inputfromathena', which will return all possible case variations of the `inputfromathena`. This will essentially push down the table name to the database, whereas in the current approach we are relying on JDBC interface to list all tables and then filter in the connector. Implementation will remain same in JDBCMetadataHandler as not all subclasses will have support for information_schema, but we can override the implementation of caseInsensitiveTableSearch in databases that have support for information_schema table (for ex. Mysql, Postgresql, Redshift etc.).

Note that this will only improve the performance for case when the table name in the database contains upper case letters, i.e. first call to database getTable returns empty result, so we do a case-insensitive search for getTables (which can be improved using what I described above)

**Comment by akuzin1** [comment]
#1289
