### ISSUE TITLE
[BUG] Athena returns incorrect result for dynamodb table having different data struct in same attribute

### ISSUE THREAD

**Issue by lilychan16** [awslabs/aws-athena-query-federation#1346]
I'm using AthenaDynamoDBConnector version 2023.23.01 but I'm still seeing this bug https://github.com/awslabs/aws-athena-query-federation/issues/256. I'm wondering if there's any workaround for this issue.

**Comment by akuzin1** [comment]
Not sure if this would be a sufficient work around, however, as mentioned in linked issue it would require to define the schema, as a superset of all possible value types, in Data Catalog.
