### ISSUE TITLE
[QUESTION] Password authentication failed

### ISSUE THREAD

**Issue by shlomi-viz** [awslabs/aws-athena-query-federation#135]
I have a question that I don't think is related to a bug or feature request. 

Hey,

I'm trying to connect to Postgres RDS with Username and Password that are stored in `secret manger` as JSON. My password has many special characters, like: = - _ % ! +
At the start I got the error:

```
URLDecoder: Illegal hex characters in escape (%) pattern
```
I managed to bypass it by changing `%` in my password to `%25`. 

But now I'm getting the error: 
```
0: org.postgresql.util.PSQLException: FATAL: password authentication failed for user
```
I guess that there is some logic for escaping the special chars that the Lambda is doing and that makes my password invalid. 
How can I fix this? Should I escape the characters in `secret manger`? if so which ones should I escape?
**I have to use this password and I can't change it.**

Thanks.

**Comment by avirtuos** [comment]
I reviewed the code for how we retrieve the secret and then pass it to the JDBC connection. We are not doing any sanitization. The info stored in SecretsManager for RDS credentials is however JSON format so you may need to escape certain special characters within that JSON document to ensure it is properly readable. Let me know if this helps.

**Comment by shlomi-viz** [comment]
Thanks for the quick response. How can a simulate this? to know what is the value been passed to JDBC? I tried to escape ALL special characters but still got a wrong password error. 
Thanks again

**Comment by shlomi-viz** [comment]
I used this https://docs.oracle.com/javase/8/docs/api/java/net/URLDecoder.html in order to find which characters I needed to escape :-)
