### ISSUE TITLE
[FEATURE] Protobuf & AVRO support for MSK + Glue

### ISSUE THREAD

**Issue by Jtalk** [awslabs/aws-athena-query-federation#1382]
**Is your feature request related to a problem? If yes, please describe.**

We're trying to query our MSK + Protobuf + Glue Schema Registry set up directly via Athena, without having to worry about copying everything into S3.

The athena-msk connector seems to only support [JSON and CSV](https://github.com/awslabs/aws-athena-query-federation/blob/98ccec821df9349a6a51d2d42e8e29438101c781/athena-msk/src/main/java/com/amazonaws/athena/connectors/msk/AmazonMskUtils.java#L130), even though Glue Schema Registry itself supports Protobuf. 

Without Protobuf support, and therefore without being able to query MSK directly with Athena, there seems to be no advantage to using Glue Registry over the Confluent one. 

**Describe the solution you'd like**

Enable direct querying of Protobuf & AVRO data in Athena.

Is there a technical reason why it couldn't work for at least protobuf, with e.g. DynamicMessage? This is a very important feature for us. 

**Additional context**

The connector's docs don't seem to mention this caveat, though it sounds important.

The error I'm getting when trying to use athena-msk with Protobuf: 
<img width="444" alt="image" src="https://github.com/awslabs/aws-athena-query-federation/assets/1573833/b4c67986-6323-47a0-ae52-cb2acac3ad6b">

**Comment by AbdulR3hman** [comment]
this is now supported; please refer to our documentations: https://docs.aws.amazon.com/athena/latest/ug/connectors-kafka.html
