### ISSUE TITLE
[BUG] describe table query will sometimes generate a disjointed schema view.

### ISSUE THREAD

**Issue by shurvitz** [awslabs/aws-athena-query-federation#140]
**Describe the bug**
the SchemaBuilder underlying container for the fields is declared a HashMap, but should be a LinkedHashMap instead. The difference is that a LinkedHashMap maintains the order of the elements in the map.

To illustrate the problem, the following schema list was generated by running a 'describe table' query on the elasticsearch connector (currently in development). Even though, all fields were added to the SchemaBuilder object in order, the resulting list displays the field '**address.street**' out of position (should come after '**address.town**'):

**address.zip**	varchar
**address.town**	varchar
phone.mobile	varchar
phone.landline	varchar
members	array<varchar>
**address.street** varchar
account	varchar
email	array<varchar> 

**To Reproduce**
1. Go to the Athena console.
2. Create a new query: `describe 'lambda:elasticsearch'.movies.customer;`
3. Press Run query.
4. See Results

**Expected behavior**
Expected schema:

**address.zip**	varchar
**address.town**	varchar
**address.street**	varchar
phone.mobile	varchar
phone.landline	varchar
members	array<varchar>
account	varchar
email	array<varchar>

**Comment by avirtuos** [comment]
Thanks for filing this @shurvitz . Per our chat, let me know when you raise a PR for the fix.

**Comment by avirtuos** [comment]
Thanks @shurvitz , fix has been merged and will go out in the next release.
