### ISSUE TITLE
[BUG] Lambda function crashes when checking materialized views with connector Postgres

### ISSUE THREAD

**Issue by timothybwatson** [awslabs/aws-athena-query-federation#1450]
After creating a connector using JDBC to my Postgres RDS instance, and then adding it as a Data source in Athena, I get error messages stating:
`Failed to get metadata for table (stats) from lambda function due to java.lang.RuntimeException: com.amazonaws.services.lambda.invoke.LambdaFunctionException: During Case Insensitive look up could not find Table 'stats' in Database 'public'`

'stats' isn't a table but a Materialized View in my schema (public). A quick check of the source (aws-athena-query-federation/athena-postgresql/src/test/java/com/amazonaws/athena/connectors/postgresql
/PostGreSqlMetadataHandlerTest.java) looks like the connector only checks the name for uniqueness against information_schema.tables which doesn't include materialized views.

**To Reproduce**
1. Create Postgres DB with a Materialized View.
2. Connect Athena to the DB using the JDBC connector.

**Expected behavior**
That it would successfully detect all tables, views, and materialized views.

**Screenshots / Exceptions / Errors**
`Failed to get metadata for table (stats) from lambda function due to java.lang.RuntimeException: com.amazonaws.services.lambda.invoke.LambdaFunctionException: During Case Insensitive look up could not find Table 'stats' in Database 'public'`

Lambda CloudWatch log is also attached showing successful connection and processing of regular tables and views and then failure on 'stats' which is a Materialized View. (Dataset is derived from publicly available government spending data so table names, etc. are not sensitive.)

[Lambda CloudWach Log.csv](https://github.com/awslabs/aws-athena-query-federation/files/12482169/Lambda.CloudWach.Log.csv)

**Connector Details (please complete the following information):**
 - Version: 2023.35.1
 - Name: serverlessrepo-AthenaPostgreSQLConnector

**Comment by akuzin1** [comment]
Thank you for filing a ticket and bringing the following issue to our attention, the bug fix should be included in the latest release **v2023.37.2**, please redeploy the connector to resolve behavior.
