### ISSUE TITLE
[BUG] CWE-200 - Sensitive information leak with connector dynamodb

### ISSUE THREAD

**Issue by jkruse14** [awslabs/aws-athena-query-federation#1488]
**Describe the bug**
High Severity finding from AWS Inspector:

>  CWE-200 - Sensitive information leak
> This code contains a potential information leakage in the handling of the following *exception logging*: (MalformedURLException var6). Logging an exception object typically results in printing the full stack trace, which reveals variable names, method names, line numbers, and other parts of the code. **Fix** Release data more selectively, or declassify the data before it's released. Alternatively, switch to the DEBUG (debug() API) or TRACE (trace() API) logging levels

**To Reproduce**
1. Deploy to account with Security Hub enabled
2. Click on 'Findings
3. Add filter: `Title = CWE-200 - Sensitive information leak`
4. View Finding

**Expected behavior**
The lambda and any related resources do not produce findings in Security Hub and related AWS Security tooling

**Screenshots / Exceptions / Errors**
<img width="295" alt="image" src="https://github.com/awslabs/aws-athena-query-federation/assets/16331726/740af682-663c-4b42-98cf-ae9fff9cbe7d">

**Connector Details (please complete the following information):**
 - Version: 2023.25.2
- Name AthenaDynamoDBConnector

**Additional context**
N/A

**Comment by akuzin1** [comment]
Athena Federation follows a shared responsibility model with the customer, where logging is handled exclusively within the customer account.
