### ISSUE TITLE
[BUG] CWE-330 - Weak pseudorandom number generation with connector dynamodb

### ISSUE THREAD

**Issue by jkruse14** [awslabs/aws-athena-query-federation#1489]
**Describe the bug**
High severity finding from AWS Inspector: 

> CWE-330 - Weak pseudorandom number generation
> Insufficiently random generators or hardcoded seeds can make pseudorandom sequences predictable, which may lead to security vulnerabilities.
> Remediation:
>We detected the use of `getInstanceStrong` to instantiate a [`java.security.SecureRandom`](https://docs.oracle.com/javase/8/docs/api/java/security/SecureRandom.html) object. [`getInstanceStrong`](https://docs.oracle.com/javase/8/docs/api/java/security/SecureRandom.html#getInstanceStrong--) can cause a thread to block for a long time, creating an availability risk. We suggest you use `new SecureRandom()` to instantiate a `java.security.SecureRandom` object.

**To Reproduce**
1. Deploy to account with Security Hub and Inspector enabled
2. Click on 'Findings
3. Add filter: Title = `CWE-330 - Weak pseudorandom number generation`
4. View Finding

**Expected behavior**
The lambda and any related resources do not produce findings in Security Hub and related AWS Security tooling

**Screenshots / Exceptions / Errors**
<img width="298" alt="image" src="https://github.com/awslabs/aws-athena-query-federation/assets/16331726/7baf2e36-bf16-4caf-b7e0-cff39a6f5b1f">

**Connector Details (please complete the following information):**
- Version: 2023.25.2
- Name AthenaDynamoDBConnector

**Additional context**
N/A

**Comment by akuzin1** [comment]
Superficial discovery. `getInstanceStrong` is already being executed within a separate thread.

**Comment by jkruse14** [comment]
> Superficial discovery. `getInstanceStrong` is already being executed within a separate thread.

@akuzin1 - what does this mean?
