### ISSUE TITLE
Unexpected field[key1] while expecting[@

### ISSUE THREAD

**Issue by schandrakandi** [awslabs/aws-athena-query-federation#152]
**Describe the bug**
{
  "errorMessage": "Unexpected field[key1] while expecting[@type]",
  "errorType": "java.lang.IllegalStateException",
  "stackTrace": [
    "com.amazonaws.athena.connector.lambda.serde.BaseDeserializer.assertFieldName(BaseDeserializer.java:200)",
    "com.amazonaws.athena.connector.lambda.serde.BaseDeserializer.getType(BaseDeserializer.java:256)",
    "com.amazonaws.athena.connector.lambda.serde.DelegatingDeserializer.doDeserialize(DelegatingDeserializer.java:56)",
    "com.amazonaws.athena.connector.lambda.serde.DelegatingDeserializer.deserializeWithType(DelegatingDeserializer.java:49)",
    "com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:63)",
    "com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3807)",
    "com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2867)",
    "com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:99)"
  ]
}

**To Reproduce**

**Expected behavior**

**Screenshots / Exceptions / Errors**
If applicable, add screenshots, exception stack traces, or error messages to help explain your problem.  Stack traces for exceptions thrown by your Connector can be found in CloudWatch Logs under the 'aws/lambda/<Lambda_function_name>' log group.

**Connector Details (please complete the following information):**
 - Version: [e.g. 2020.04.01]
 - Name [e.g. redis, hbase, jdbc]
 - Athena Query IDs [if applicable]

**Additional context**

**Comment by avirtuos** [comment]
This issue does not contain sufficient information to understand the error or bug you are experiences. Can you please complete the required questions in the template and then reopen the bug.

**Comment by akshaybadekar29** [comment]
Hi Schandrakandi

Did this issue got resolve for you, I am facing the exact same. 
Please let me know what is the solution

**Comment by drone-ah** [comment]
In case it helps someone else.

I was getting this error when running the lambda using the test button. However, when I was accessing it from Athena, the error was different, and logged to CloudWatch.

In my particular case, I needed to add an environment variable in the lambda of the form

`{$catalog_name}_connection_string` with the value of the connection string.

https://github.com/awslabs/aws-athena-query-federation/issues/174 has a similar issue
