### ISSUE TITLE
[FEATURE] athena-sqlserver without VIEW DATABASE STATE permission

### ISSUE THREAD

**Issue by lucari93** [awslabs/aws-athena-query-federation#1540]
**Is your feature request related to a problem? If yes, please describe.**
In order to use the athena-sqlserver it is mandatory to have a user with `VIEW DATABASE STATE` permission. This permission gives a lot of visiblity on the database and I would like to have the possibility to avoid this.

**Describe the solution you'd like**
Looking at the code here: https://github.com/awslabs/aws-athena-query-federation/blob/40aa36cc034aeaa5e973cadec695f27dda926b83/athena-sqlserver/src/main/java/com/amazonaws/athena/connectors/sqlserver/SqlServerMetadataHandler.java and on the errors I got using the connector I can understand that `VIEW DATABASE STATE` permission is mandatory to perform the query `GET_PARTITIONS_QUERY` to check if a table is partitioned.
I would like to:

- For tables: Add a fallback, so that if the partitions cannot be retrieved, the query is excuted without considering partitions
- For views: skip the query that is useless because it doesn't apply on views and it is actually ignored later in the code

**Describe alternatives you've considered**
An alternative solution could be to have a configuration (via environment variable) to disable the use of partitions by the connector

**Additional context**
Piece of code which I'm referring to:
![image](https://github.com/awslabs/aws-athena-query-federation/assets/15119135/f0993904-d97e-409f-899c-c01443ada398)

**Comment by AbdulR3hman** [comment]
PR has been approved; this is now part of the latest release.
