### ISSUE TITLE
[BUG] Invalid ProjectionExpression - reading a column with reserved keyword with DynamoDB connector

### ISSUE THREAD

**Issue by tudor-a** [awslabs/aws-athena-query-federation#155]
**Describe the bug**
Unable to read a column named 'key' from a DynamoDB table. The error in Cloudwatch logs says that the attribute name (key) is a reserved keyword in DynamoDB. This issue never occurred with the previous version of the DynamoDB connector (2020.04.01) and I am able to query tables regardless of the table name when using the older version (2020.04.01) of the connector. 

**To Reproduce**
1. Deploy the newest version of the DynamoDB Connector (2020.17.01)
2. Create a DynamoDB table and add the following item
{
  "id": "1",
  "key": "bla"
}
3. Navigate to Athena and run a SELECT * FROM "lambda<lambdaname>".default."<tablename>";
4. You should get an error in Athena similar to the one I pasted below.
5. In Lambda function's Cloudwatch logs, you should get an error similar to the one I attached to this report.

**Expected behavior**
When querying DynamoDB using version 2020.04.01 connector, I was able to read the data from the table regardless of the column name and it being a reserved keyword. 

**Screenshots / Exceptions / Errors**
This is the error I get while running the query in Athena:
GENERIC_USER_ERROR: Encountered an exception[null] from your LambdaFunction[function-name] executed in context[S3SpillLocation{bucket='bucket-name', key='athena-spill/***/c---', directory=true}] with message[Unexpected error executing Lambda function]

I am attaching a relevant part of the Cloudwatch logs.
[cloudwatch logs.txt](https://github.com/awslabs/aws-athena-query-federation/files/4546999/cloudwatch.logs.txt)

Note: I tried to troubleshoot this issue by creating a Glue schema, by both running a crawler and creating it manually, but neither helped.

**Connector Details (please complete the following information):**
 - Version: [e.g. 2020.17.1]
 - Name : DynamoDB Connector

**Comment by atennak1** [comment]
Suspect this is due to https://github.com/awslabs/aws-athena-query-federation/commit/8009f2efce62bb4bf88fb7006755d9618f30f95b .  Assigning to @soojinj to check

**Comment by atennak1** [comment]
Fixed by https://github.com/awslabs/aws-athena-query-federation/commit/3d043ffd1f5a8a6050a785a00292f7eb56429e9f

We'll cut a new SAR release later this week or next week.  In the meantime you can build and deploy this yourself by following https://github.com/awslabs/aws-athena-query-federation/wiki/How_To_Build_A_Connector_or_UDF#upgrading
