### ISSUE TITLE
[BUG] SAM Template Reference Error with connector DynamoDB

### ISSUE THREAD

**Issue by sdunstan** [awslabs/aws-athena-query-federation#1569]
**Describe the bug**
When you provide a LambdaRole ARN in the arguments to the AthenaDynamoDBConnector, it fails with the error message:
"Template format error: Unresolved resource dependencies [FunctionRole] in the Resources block of the template".

**To Reproduce**
1. Go to Athena Data Sources
2. Click on new data source
3. Select DynamoDB
4. Click Create Lambda Function
5. Fill in all the details including LambdaRole
6. Hit Deploy
9. See error

**Expected behavior**
Expected behavior is that the lambda is created.

**Screenshots / Exceptions / Errors**
"Template format error: Unresolved resource dependencies [FunctionRole] in the Resources block of the template"

**Connector Details (please complete the following information):**
 - Version: 2023.42.1
 - Name: AthenaDynamoDBConnector
 - Athena Query IDs [if applicable]

**Additional context**
We think this may be caused by [line 74](https://github.com/awslabs/aws-athena-query-federation/blob/master/athena-dynamodb/athena-dynamodb.yaml#L74) referencing the FunctionRole which is not created because of condition on line 77.

**Comment by ejeffrli** [comment]
If you pass in your own lambda role, NotHasLambdaRole will evaluate to false. FunctionRole won't be created and the statement, !If [NotHasLambdaRole, !GetAtt FunctionRole.Arn, !Ref LambdaRole], would not hit "GetAtt FunctionRole.Arn" and cause this issue. Are you deploying through the console?

**Comment by sdunstan** [comment]
Yes, we were deploying through the console.

**Comment by ejeffrli** [comment]
Are you providing an IAM role ARN for LambdaRole field? We aren't able to replicate this issue on our end. We had no issue when we passed in our LambdaRole in the format "arn:aws:iam::<account_id>:role/<role_name>"

**Comment by ejeffrli** [comment]
Thanks for bringing up this issue. This issue is fixed in the latest merge.
