### ISSUE TITLE
[BUG] Redshift Timestamp columns dropped with connector JDBC

### ISSUE THREAD

**Issue by s4saurabh** [awslabs/aws-athena-query-federation#157]
**Describe the bug**
With the new version of connectors pushed to the repo, the new JDBC connector with Redshift solves the query issue to the tables which have timestamp columns but drops any columns with timestamp data type from the output results.

**To Reproduce**
1. Goto Redshift 
2. Create a table with timestamp/non-timestamp fields - create table tstamp(timeofday timestamp, timeofdaytz timestamptz, cat varchar(10);
3. Deploy the JDBC connector with RedShift
4. Query from Athena console: select * from "lambda:redshift1".public.tstamp

**Expected behavior**
Expected to see all columns including timestamp columns.

**Screenshots / Exceptions / Errors**
If applicable, add screenshots, exception stack traces, or error messages to help explain your problem.  Stack traces for exceptions thrown by your Connector can be found in CloudWatch Logs under the 'aws/lambda/<Lambda_function_name>' log group.

![image](https://user-images.githubusercontent.com/1901278/80766471-5aea8f00-8afa-11ea-9270-a7fad05cfe91.png)
**Connector Details (please complete the following information):**
 - Version: 2020.04.30
 - Name jdbc
 - Athena Query IDs : N/A

**Additional context**

**Comment by atennak1** [comment]
@s4saurabh you mentioned "new version" which is currently 2020.17.1 but you wrote 2020.04.30 in the Connector Details section.  Could you confirm which version you used?  Thanks.

**Comment by s4saurabh** [comment]
2020.17.1

**Comment by JosiahDub** [comment]
This bug is also applicable to Postgres databases as well. timestamp columns cannot be resolved.

**Comment by atennak1** [comment]
suspect https://github.com/awslabs/aws-athena-query-federation/blob/f693dcd081a00ed460eaf167e2e20965197e2b3f/athena-jdbc/src/main/java/com/amazonaws/connectors/athena/jdbc/manager/JdbcMetadataHandler.java#L232 is returning Timestamp without TZ which corresponds to TIMESTAMPMILLI, but we only support TIMESTAMPMILLITZ in https://github.com/awslabs/aws-athena-query-federation/blob/2c530c56280edc55a07713d7d5314129bc07e2cc/athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/data/SupportedTypes.java#L39

**Comment by avirtuos** [comment]
@atennak1 is there any meaningful difference between TimestampMilli and DateMilli? they seem to be capable of conveying the exact same thing and we do presently support DateMilli. Could this be as simple as fixing that mapping?

**Comment by shlomi-viz** [comment]
I'm also facing a similar issue. I'm using `athena federated query` to fetch data from Postgres RDS with Athena. Version: `2020.19.1`. When I tried to query a table that has a column of type `timestamp with time zone` I get all other columns except this one.
Are there any plans to support this?

Thanks.

**Comment by fysp11** [comment]
> @atennak1 is there any meaningful difference between TimestampMilli and DateMilli? they seem to be capable of conveying the exact same thing and we do presently support DateMilli. Could this be as simple as fixing that mapping?

I guess it does, since Athena doesn't support all the same timestamp types that redshift does. So, converting from different redshift types to DateMilli is super meaningful, right?

**Comment by hackett123** [comment]
Picking up this old ticket. I created a Redshift table with column type TIMESTAMP and another table with column type TIMESTAMPTZ. In both cases, I was able to query all data from the latest Athena Redshift connector correctly and without dropping any values.

Redshift insert calls:
```
insert into table_with_timestamps
values  (1, '2023-04-27 14:30:45'),
        (2, '2023-04-27 12:15'),
        (3, '2023-04-27')

___

insert into table_with_timestamp_tzs
values  (1, '2023-04-27 14:30:45 EST'),
        (2, '2023-04-27 12:15 PST'),
        (3, '2023-04-27 GMT')
```

Redshift select results:
```
select * from public.table_with_timestamps
1	2023-04-27 14:30:45	
2	2023-04-27 12:15:00	
3	2023-04-27 00:00:00	

___

select * from public.table_with_timestamp_tzs
1	2023-04-27 19:30:45+00	
2	2023-04-27 20:15:00+00	
3	2023-04-27 00:00:00+00	

```

Athena queries:
```
select * from "lambda:redshift"."public"."table_with_timestamps"
#	int_field	time_field	partition_schema_name	partition_name
1	1	2023-04-27 14:30:45.000	*	*
2	2	2023-04-27 12:15:00.000	*	*
3	3	2023-04-27 00:00:00.000	*	*


---

select * from "lambda:redshift"."public"."table_with_timestamp_tzs"
#	int_col	timestamp_tz_col	partition_schema_name	partition_name
1	1	2023-04-27 19:30:45+00	*	*
2	2	2023-04-27 20:15:00+00	*	*
3	3	2023-04-27 00:00:00+00	*	*



```

Therefore I am closing this out.
