### ISSUE TITLE
[QUESTION] About Dynamodb connector

### ISSUE THREAD

**Issue by samish122** [awslabs/aws-athena-query-federation#161]
I have a question that I don't think is related to a bug or feature request. 

How about pricing by querying DynamoDB through Athena, I know there will be cost per query in Athena
But what about dynamo, how I will be charged, per read capacity units ?

**Comment by atennak1** [comment]
If the queried tables are of billing type Provisioned Capacity, there is no extra charge.  Queries will be throttled if they exceed provisioned RCUs.

If the type is On-Demand, then yes there will be [charges](https://aws.amazon.com/dynamodb/pricing/on-demand/) based on the RCUs consumed by the query (currently $0.25 per million RCUs).
