### ISSUE TITLE
[BUG] Password displayed in plain text in cloudWatch logs with connector Postgres JDBC

### ISSUE THREAD

**Issue by shlomi-viz** [awslabs/aws-athena-query-federation#162]
**Describe the bug**
I used secret manager in order to pass the user name and password to the connection string, while looking at the logs I can see the password in plain text.

**To Reproduce**
1. Create a new Lambda
2. Save username and password in secret manager
3. add the secret to the connection string
4. Use lambda and see the password in the logs.

**Expected behavior**
connection string is not displayed or scrambled in logs

**Connector Details (please complete the following information):**
 - Version: 2020.4.1
 - Name jdbc
 - Athena Query IDs 

Thanks

**Comment by atennak1** [comment]
This was fixed by https://github.com/awslabs/aws-athena-query-federation/commit/d580fe74a16a4fcf3d376ea709a814cb6c053dc0 so should be resolved in v2020.17.1+

Can you confirm whether you were using an older version or not?

**Comment by shlomi-viz** [comment]
Where can I see the version? in the Lambda I have a tag with key: `serverlessrepo:semanticVersion` and value: `2020.4.1`
How to I upgrde?

**Comment by atennak1** [comment]
Thanks for confirming.  Simply go to Serverless App Repo and deploy again with the same parameters.  The version is now 2020.19.1.
