### ISSUE TITLE
Some queries failing in the recent week or so

### ISSUE THREAD

**Issue by houmark** [awslabs/aws-athena-query-federation#165]
**Describe the bug**
In the recent week we are seeing some queries failing with a weird error:

Your query has the following errors:SYNTAX_ERROR: line 4:14: Catalog mycatalogname (replaced real name for privacy) does not exist

This query ran against the 'default' database, unless qualified by the query. Please post the error message on our forum or contact customer support with query id.

The above error happened for query ID: 77dd8881-8f96-45ca-b050-47b1a5e6d885

The connector is the DynamoDB connector.

Running ~20 queries rapidly after each other 3-4 queries fail on average. We used to see all queries complete, some after a good amount of time (due to max concurrency limitations current on this public preview, which I would love to see lifted to speed up our UI), but at least they would complete without errors.

**To Reproduce**
Just run queries.

**Expected behavior**
Queries to not fail.

**Comment by avirtuos** [comment]
@houmark This issue is a bit surprising because this error occurs when our engine can not find your catalog (e.g. your Lambda function information). I have a few follow up questions:

1. Is this truly intermittent meaning it fails sometimes (potentially in bursts) but succeeds without any changes on your end most of the time?
2. are you using the lambda:<function_name> syntax in your queries? or are you pre-registering your catalogs so that you don't need to use the 'lambda:' in your SQL?

**Comment by avirtuos** [comment]
@sethtdenney Can you take a deeper look at this with Luc so we start to spread this knowledge a bit more?

**Comment by houmark** [comment]
Zero changes in our end, our dashboard has not been modified for weeks, but I started seeing this a week ago and it will sometimes fail one chart out of ~20, sometimes, 1 but mostly 3-4. 

I am not sure to be honest, but we have a Glue catalog on the tables but the entire thing is quite complex with Amplify in front, doing GraphQL queries, which then are transformed to Athena queries. In the 2-3 months developing this, I never saw this error and only noticed it about a week ago, and was waiting to see if it was temporary, but now it seems it's not. Can recreate this on a consistent basis, but it is different queries failing when it happens, so it seems to be some issue in the connection outside of our control.

**Comment by avirtuos** [comment]
We have tracked down the main source of this issue and have rolled back the change. Let me know if you do _not_ see error rates recover.
