### ISSUE TITLE
[BUG] Error running queries in AWS QuickSight with connector athena-dynamodb

### ISSUE THREAD

**Issue by matthorn-repo** [awslabs/aws-athena-query-federation#168]
**Describe the bug**
I'm receiving an error trying to run queries against athena dynamodb tables in AWS quicksight. These work fine in Athena so I'm surprised they don't work in quicksight.

**To Reproduce**
1. Go to AWS QuickSight
2. Click on 'Manage Data'
3. Click on 'New Data Set'
4. Click on 'Athena'
5. Name the data set and select 'AmazonAthenaPreviewFunctionality' for the work group
6. Click 'Create Data Source'
7. Select the database and table containing the dynamodb table view in athena
8. Click 'Directly Query Your Data' or 'Import to SPICE' and click 'Visualize'
4. Query fails with error below

**Expected behavior**
Queries run normally, as they do in Athena.

**Screenshots / Exceptions / Errors**
```
region: | us-east-1
-- | --
1589388077501
7650ffe2-c9a2-46e6-8ad0-270a4dbb00bc
100071
[Simba][AthenaJDBC](100071) An error has been thrown from the AWS Athena client. HIVE_METASTORE_ERROR: com.facebook.presto.spi.PrestoException: Required Table SerDe information is not populated. (Service: null; Status Code: 0; Error Code: null; Request ID: null)
HY000
java.sql.SQLException
ATHENA
```

**Connector Details (please complete the following information):**
 - Version: 2020.19.1
 - Name dynamodb

**Comment by avirtuos** [comment]
Hi @matthorn-repo ,

Can you please provide us with the Athena query id for the above as well as logs from the Lambda function that you deployed the DDB Connector to. Those logs can be found in cloudwatch in your account.

The error message above is a bit surprising to me. If you are not able to share the above info on this GitHub issue, you can email me virtuoso [at] amazon.com

**Comment by ankurgupta4891** [comment]
Hi @matthorn-repo, 

AWS QuickSight doesn't support Athena data source connectors (AQF feature) yet. The limitation here is, QuickSight is still on old Athena JDBC driver that does not support `catalog` and looks for data in default catalog. QuickSight team is working on Athena data source connectors integration, however there is no official announcement when the support will come out. If possible, please reach out AWS support to get update on the timelines for QuickSight product.

**Comment by avirtuos** [comment]
Thanks @ankurgupta4891 !

@matthorn-repo , I'm closing this issue for now but please reopen it if you have further questions. We hope this will work for you soon and are actively working with the QuickSight team.

**Comment by aravind08** [comment]
Any update on this connector?

**Comment by arlyon** [comment]
@avirtuos Is this bug fixed? Why close the issue prematurely and lose visibility on its status? For context, I am also experiencing this issue over a year later.
