### ISSUE TITLE
[Question] Sample redshift connection string 

### ISSUE THREAD

**Issue by maannaash** [awslabs/aws-athena-query-federation#174]
Can someone provide a sample redshift connection string? I have tried following :

default - redshift://jdbc:redshift://<REDSHIFT JDBC URL>:5439/<DATABASE NAME>?user=<USERNAME>&password=<PASSWORD>
But I keep getting error - "Must provide default connection string parameter default for database type postgres: java.lang.RuntimeException"

**Comment by avirtuos** [comment]
I dont think the format of your connection string is the issue. This error suggests that your are not setting the appropriate environment variable on your Lambda function. What was the name of the environment_variable that you used? and what was the catalog name used in your query when you received this error?

**Comment by maannaash** [comment]
The environment variable name that I am using is default. Since I am connecting to one database I also changed my handler to  - 
 com.amazonaws.connectors.athena.jdbc.postgresql.PostGreSqlRecordHandler
My catalog name is redshift1.

Below is the cloudwatch log for lambda function
Must provide default connection string parameter default for database type postgres: java.lang.RuntimeException
java.lang.RuntimeException: Must provide default connection string parameter default for database type postgres
	at com.amazonaws.connectors.athena.jdbc.manager.JDBCUtil.getSingleDatabaseConfigFromEnv(JDBCUtil.java:58)
	at com.amazonaws.connectors.athena.jdbc.postgresql.PostGreSqlRecordHandler.<init>(PostGreSqlRecordHandler.java:65)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

**Comment by avirtuos** [comment]
We might have a typo in our documentation, can you try setting an env variable on your Lambda function of redshift1_connection_string? Basically the connection string should be in an environment variable of the format {$catalog_name}_connection_string. There is also supposed to be an ability to use a failsafe of default but that doesn't seem to be working for you either because of a typo in our docs (e.g. default is the wrong name) or a bug in the connector. Once you confirm if redshift1_connection_string helps and thus unblocks you we can turn our attention to root causing the issue with default

**Comment by maannaash** [comment]
Thanks for the update. I did try adding redshift1_connection_string and providing the connection sting in this as an environment variable but I still keep getting same error. Please note that I have single database so as per documentation I replaced the lambda function function handler to - com.amazonaws.connectors.athena.jdbc.postgresql.PostGreSqlRecordHandler as per the documentation. I am not using the MultiplexingJdbcCompositeHandler

 - When I have both default and redshift1_connection_string as environment variables then the error is "Must provide default connection string parameter default for database type postgres"
 - When I have just redshift1_connection_string as the environment variable and removed default then the error is - "Default connection string must be present: "

**Comment by abhijeetvg** [comment]
@maannaash This looks like a validation bug when Redshift engine is configured with the database specific handler. While we work on a fix, you may be able to unblock by using Multiplexing handlers. See [multiplexing handler parameters](https://github.com/awslabs/aws-athena-query-federation/tree/master/athena-jdbc#Multiplexing-handler-parameters) for more details.

**Comment by maannaash** [comment]
I tried with the Multiplexing handlers but still it is not working. 

Even with Multiplexing handler when I used my environment variable as redshift1_connection_string(and did provide and default) then the I get error as "Default connection string must be present". This validation is in DatabaseConnectionConfigBuilder.java:80 which is causing it. 

And with Multiplexing handler when I provide the default and redshift1_connection_string as environment variable I get error - "Catalog is not supported in multiplexer. After registering the catalog in Athena, must set 'redshift1_connection_string' environment variable in Lambda." This is coming from MultiplexingJdbcMetadataHandler.java:87. I believe once we give default the redshift1_connection_string is ignored. So I am not finding an other way around to get this working.

**Comment by avirtuos** [comment]
@abhijeetvg Any progress looking into this?

**Comment by abhijeetvg** [comment]
@maannaash I was unable to reproduce this issue on my setup.

Followed steps:
1. Create data sources in Athena (`redshift1`, `redshift2` - both point to same Lambda Redshift connector). See [instructions here](https://docs.aws.amazon.com/athena/latest/ug/connect-to-a-data-source-lambda.html).

I used a single Lambda (recommend using SAR to deploy) with following properties:

* Handler: 
```
com.amazonaws.connectors.athena.jdbc.MultiplexingJdbcCompositeHandler
```
* Environment Variables:
```
"default": "redshift://jdbc:redshift://<host>:5439/<schema>?${<SecretName>}"
"redshift1_connection_string": "redshift://jdbc:redshift://<host>:5439/<schema>?${<SecretName>}"
"redshift2_connection_string": "redshift://jdbc:redshift://<host>:5439/<schema>?user=<user>&password=<password>"
"spill_bucket": "<s3_bucket>"
"spill_prefix": "<s3_prefix>"
```

I was able to select the data source in Athena, retrieve databases and tables, and query (SELECT) one of the tables successfully.

`redshift1` and `redshift2` demonstrate different connection strings using Secrets Manager and user/password approaches respectively.

If this does not help, could you:
1. Set `Reserve concurrency` for your lambda to 1, ensures generation of all logs for the execution in a single file.
2. Run a sample query against the catalog.
3. Share full log from CloudWatch with us.
4. Share handler name and all environment variables.

**Comment by avirtuos** [comment]
@drone-ah, this issue appears to be stale (no reply in > 20 days) and we have not be able to reproduce. Please reopen if you have tried the above suggestions and can still not get this to work. Thanks.
