### ISSUE TITLE
[QUESTION] General question COMPILATION ERROR

### ISSUE THREAD

**Issue by ray-pan-bci** [awslabs/aws-athena-query-federation#175]
I have a question that I don't think is related to a bug or feature request. 

<Describe your question>
What I wanted to do is to deploy this lambda using terraform. Seems the prerequisite is to get the target/athena-dynamodb-1.0.jar file. So I took an approach of mvn clean install as instructed. How ever I got this error when do the first mvn clean install step at dir athena-federation-sdk:

ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /Users/path/Repos/aws-athena-query-federation/athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/data/BlockTest.java:[76,24] package javax.activation does not exist
[ERROR] /Users/path/Repos/aws-athena-query-federation/athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/data/BlockTest.java:[378,20] cannot find symbol
  symbol:   class UnsupportedDataTypeException
  location: class com.amazonaws.athena.connector.lambda.data.BlockTest
[INFO] 2 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10.015 s
[INFO] Finished at: 2020-05-21T02:00:33-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:testCompile (default-testCompile) on project aws-athena-federation-sdk: Compilation failure: Compilation failure:
[ERROR] /Users/path/Repos/aws-athena-query-federation/athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/data/BlockTest.java:[76,24] package javax.activation does not exist
[ERROR] /Users/path/Repos/aws-athena-query-federation/athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/data/BlockTest.java:[378,20] cannot find symbol
[ERROR]   symbol:   class UnsupportedDataTypeException
[ERROR]   location: class com.amazonaws.athena.connector.lambda.data.BlockTest
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

I am not familiar with java and my java -version is "1.8.0_251" .  How can I solve this ? Or is there any better solution to deploy this lambda using terraform? 

Thank you

**Comment by avirtuos** [comment]
I'm not sure why your environment was unable to find that particular dependency but I'm also surprised we had that dependency on UnsupportedDataTypeException. I've prepared a PR which changes it to a core java exception of UnsupportedOperation(...)

https://github.com/awslabs/aws-athena-query-federation/pull/176

This is now merged so if you update your local branch you can try rebuilding and lets see if it works or if you encountered a different error.

**Comment by avirtuos** [comment]
Also, have you considered deploying using Serverless Application Repository instead of building from source? I'm not very familiar with TerraForm but can't you use it to deploy a ready-made SAM application in Serverless Application Repository?

**Comment by ray-pan-bci** [comment]
Merged your new changes and now "build sucess" Thank you 

And yes I was able to deploy the connector using SAM but I am just trying to find anther way to deploy it as code. Thanks a lot

**Comment by avirtuos** [comment]
Happy to help. let us know if you have other questions or need any help.
