### ISSUE TITLE
[BUG] error occurs when using the LIMIT clause with AthenaGoogleBigQueryConnector

### ISSUE THREAD

**Issue by kensukeok** [awslabs/aws-athena-query-federation#1767]
**Describe the bug**

Creating a lambda function to execute SQL queries in Athena can result in an error or return the expected results depending on the number specified in the LIMIT clause.

**Screenshots / Exceptions / Errors**

error message

```
GENERIC_USER_ERROR: Encountered an exception[java.lang.IndexOutOfBoundsException] from your LambdaFunction[arn:aws:lambda:xxxxxxxxxxx:function:xxxxxxxxxxx] executed in context[S3SpillLocation{bucket='xxxxxxxxxxx', key='xxxxxxxxxxx', directory=true}] with message[index: 512, length: 1 (expected: range(0, 512))]
```

**Connector Details (please complete the following information):**
 - Version: 2024.6.1

**Comment by kensukeok** [comment]
[message1.txt](https://github.com/awslabs/aws-athena-query-federation/files/14370189/message1.txt)
[message2.txt](https://github.com/awslabs/aws-athena-query-federation/files/14370193/message2.txt)

error message

**Comment by akuzin1** [comment]
The fix has been included in latest version v.2024.10.1, please upgrade connector. Thank you for your patience!

**Comment by kensukeok** [comment]
It works well! Thanks!
