### ISSUE TITLE
[QUESTION] Null value in ARRAY is possible ?

### ISSUE THREAD

**Issue by tkcmada** [awslabs/aws-athena-query-federation#177]
I have a question that I don't think is related to a bug or feature request. 

This is related to my developping connector. Not public connector.

Let's say kdb+ returns array of Java long type as a a column value of one row.
See below bid_amounts column.
I could pass bid_amounts to ARRAY in Athena by using Apache Arrow UnionListWriter.

There is one problem about null alue in ARRAY.
kdb+ can include null value in ARRAY by treating Long.MIN_VALUE as null representative.
So if I just show those value in Athena, it would look like below.
| id | bid_amounts                                       |
|---| -----------------------------------------|
| 1  | [ 1000000 , -9223372036854775808]  |

But I'd like to show this as below in Athena.
| id | bid_amounts                                       |
|---| -----------------------------------------|
| 1  | [ 1000000 , NULL  ]  |

I'm wondering can we pass NULL value to Athena by UnionListWriter ?

**Comment by avirtuos** [comment]
Currently, null items within a list are 'ignored'. I don't believe this is the _best_ behavior and likely represents an area where we could be doing something better. I've not yet looked to see if Arrow supports null items within lists but I'd be surprised if they didn't.

**Comment by tkcmada** [comment]
Hi @avirtuos 

Actually, I don't mind if Athena doesn't show NULL value in ARRAY in console as I can convert ARRAY to VARHAR by array_join(ary, delimiter, null_representation) function.
 
Can null value in ARRAY be passed around spill-bucket and athena-result-bucket ?
It seems that null value in ARRAY is ignored completely and not written into UnionListWriter in BlockUtils#writeList.

com.amazonaws.athena.connector.lambda.data.BlockUtils#writeList
```
        writer.startList();

        Iterator itr = value;
        while (itr.hasNext()) {
            //For each item in the iterator, attempt to write it to the list.
            Object val = itr.next();
            if (val != null) {
                switch (Types.getMinorTypeForArrowType(child.getType())) {
                    case LIST:
                         ...
                        break;
                    case STRUCT:
                         ...
                        break;
                    default:
                        writeListValue(writer, child.getType(), allocator, val);
                        break;
                }
            }
        }
        writer.endList();
```

**Comment by avirtuos** [comment]
My comment was not about the console, but rather about where we write the data to Apache Arrow within the connector SDK. Today we ignore NULL entries in lists.
