### ISSUE TITLE
[FEATURE] View support for federated data sources

### ISSUE THREAD

**Issue by tkcmada** [awslabs/aws-athena-query-federation#179]
**Is your feature request related to a problem? If yes, please describe.**
When we have various data sources including federated data sources and want to join them,
currently we can write SELECT SQL joining them.
But from self discovery of data sources , it's better to register VIEW which joins multiple data sources.

**Describe the solution you'd like**
Allow the use of federated sources within a view. Today Athena does not scan VIEWs for catalog registration. 

**Describe alternatives you've considered**

**Additional context**

Do you have any plan to support it  in future ?

**Comment by atennak1** [comment]
Thanks for submitting.  We'd certainly like to support this in the future.  Keeping open for prioritization.  +1 if you're affected.

**Comment by pvieito** [comment]
+1

**Comment by avirtuos** [comment]
I updated the description a bit so that when this issue is picked up, the Athena engineer will have a better understanding of what functionality is missing within our engine to support this.

**Comment by Miksu82** [comment]
+1

**Comment by sandeshkg** [comment]
+1

**Comment by C2BB** [comment]
+1

**Comment by cmthomps** [comment]
+1

**Comment by jinsy-at-cascade** [comment]
+1

**Comment by chngpe** [comment]
Hi!

We are happy to announce we support view for federated data sources!

Please visit https://aws.amazon.com/about-aws/whats-new/2023/04/amazon-athena-view-support-external-data-sources/
