### ISSUE TITLE
[BUG] GENERIC_INTERNAL_ERROR with JDBC connector on PostgreSQL database

### ISSUE THREAD

**Issue by pvieito** [awslabs/aws-athena-query-federation#181]
I am trying the JDBC connector with a PostgreSQL database and while in general is works, on some views I got the following error:

```
Your query has the following error(s):

GENERIC_INTERNAL_ERROR: Index: 0, Size: 0
```

This view schema types on PostgreSQL:

````
character varying
date
character varying
character varying
character varying
character varying
date
date
double precision
double precision
double precision
double precision
character varying
character varying
ARRAY
integer
integer
ARRAY
integer
ARRAY
ARRAY
ARRAY
double precision
double precision
double precision
character varying
````

**Connector Details:**
 - Name: AthenaJdbcConnector
 - Version: 2020.19.1
 - Athena Query ID: faedcd4b-5d82-4ae0-99a0-48ab2d29b3cb

**Comment by avirtuos** [comment]
Can you provide us with the logs from the Lambda function in cloudwatch? if those logs contain information which you are not comfortable sharing on GitHub you can email me virtuoso[at]amazon.com or you can raise a support ticket via AWS Support.

**Comment by pvieito** [comment]
Thanks, I've just opened a support ticket at AWS with Case ID 7042545541.

In general, is there any environment variable to enable more verbose logs?

**Comment by pvieito** [comment]
Totally unrelated question, have you modified the required permissions to use federated queries? Today I got this message which did not appear yesterday:

```
<REDACETED> is not authorized to perform: athena:GetDataCatalog on resource: arn:aws:athena:eu-west-1:532132528437:datacatalog/<REDACTED>
```

I added the resource to the IAM policy and it seems to be working but it seems that the resource nor the action are not recognized by the IAM editor.

**Comment by avirtuos** [comment]
We have not made any changes to the IAM permissions.

**Comment by shlomi-viz** [comment]
@pvieito did you managed to fix this error? I'm getting a similar error when trying to query a table that has an `ARRAY` column

**Comment by Meosit** [comment]
Experiencing this issue too, as mentioned, it appears for tables which contain fields of array type. Also it seems that in cloudwatch there is no relevant logs, even with debug log level.

**Comment by shurvitz** [comment]
Take a look at PR #319. Once merged it should fix the ARRAY issue as well as provide support for other types by defaulting their value to varchar (instead of dropping them).

**Comment by shurvitz** [comment]
FYI, I just cut a new release for Athena Query Federation (v2020.51.1) and published to SAR in prod. This release includes all the latest PRs including #319. 
Let me know if it fixes this issue so that I can close it.

**Comment by Meosit** [comment]
As for me, it works like a charm. (But please note that I have manually patched and deployed this exact PR before the merge)
