### ISSUE TITLE
[QUESTION] Using Glue metadata with Dynamo connector

### ISSUE THREAD

**Issue by SeanPrendi** [awslabs/aws-athena-query-federation#182]
Hi there, I don't understand how to use the DyanmoDB connector with glue metadata instead of the connector's schema inference. I have outlined my situation in this stackoverflow question: https://stackoverflow.com/questions/62067271/how-to-use-aws-glue-metadata-in-queries-with-the-dynamodb-athena-connector

But I will copy-paste it here in case it's helpful:

I am trying to use the Athena Federated query system with the pre-built [Athena-DynamoDB Connector](https://docs.aws.amazon.com/athena/latest/ug/athena-prebuilt-data-connectors-dynamodb.html). I have the connector setup so I can run queries like this:

    SELECT * FROM "lambda:<connector>".[Something]."DynamoDB Table Name"
However, with some tables I get the following Java error from the connector:

> GENERIC_USER_ERROR: Encountered an exception[null] from your LambdaFunction[< connector>] executed in context[retrieving meta-data] with message[Unexpected error executing Lambda function]

I believe this error comes from the connector's limited ability to infer table schema, causing it to raise a null reference exception when it encounters missing data in the table, as referenced [here](https://github.com/awslabs/aws-athena-query-federation/issues/112#issuecomment-589625169). So I am attempting to use the suggested solution:

> As a work around, you can define the schema of this DDB table in Glue. That will cause the connector to bypass it's schema inference capability and perhaps stop the error so you can continue your work while we investigate.

I have setup a glue crawler that crawls the table that has the issue, I have run the glue crawler, and the table's metadata is viewable in the Glue console. However, I don't understand how to actually use this metadata instead of using the connector's schema inference. Any queries on the offending table return the same errors.

Some other information that might be relevant, but I'm not sure:

 1. The table's name in Dynamo has capital letters like this: MyTable. This gets changed in glue to all lowercase like: mytable
 2. The table contains columns with capital letters in the name like this: MyCol1, MyCol2, etc. These get changes in glue to all lowercase like: mycol1, mycol2, etc
 3. All resources have been partitioned using CloudFormation instead of the console. If anything needs to be partitioned, I would prefer to do it this way instead of via the console.
 4. The [Something] in the query above is the database name, but it seems like any arbitrary input works. I suspect that I might have to specify this to get the queries working with glue, but that's just a guess and nothing I've tried so far has worked

***

Additionally, I have manually set the sourceTable and columnMapping properties for the table via the console, as well as manually setting the database's location to dynamo-db-flag. I'm not sure if I'm supposed to structure my queries in some way to utilize this metadata, if setting these properties should make queries on the table use the glue metadata automatically and it's not for some reason, or I'm missing something entirely. But any help would be appreciated.

**Comment by atennak1** [comment]
The [Something] should equal the Glue database that the table is under.  For example, if the crawled table mytable is under the 'default' database, then the query should be `SELECT * FROM "lambda:<connector>".default.mytable`.

If this doesn't work, please provide your AWS account number and Lambda CloudWatch logs.  You can email them to me (tennakoo[at]amazon.com) or you can raise a support ticket via AWS Support.

**Comment by SeanPrendi** [comment]
Hi, sorry for the late reply. Unfortunately I had tried that and it didn't quite work, I can't send that info over right now but I've made a bug report (#184) detailing a bug that we've discovered which is seemingly highly related to why that didn't work.

**Comment by avirtuos** [comment]
closing in favor of #184
