### ISSUE TITLE
[QUESTION] Right way to deal with provisioned/autoscaling RCUs

### ISSUE THREAD

**Issue by mariaines** [awslabs/aws-athena-query-federation#183]
I have a question that I don't think is related to a bug or feature request. 

Hi, 

What's the right way to deal with provisioned read capacity when using the DynamoDB connector? I have autoscaling on my tables, and when testing out the connection in Athena, I quickly spiked our usage due to the scans, leading to some production "throughput exceeded" errors :(  Is it possible to configure a percentage of RCUs that the lambda function is allowed to use? If not, do I just have to manually up my read capacity every time I want to run a query?

I'm not sure I fully understand how the connectors work, so please correct me if any of my assumptions are wrong.

Thanks in advance!

**Comment by atennak1** [comment]
Currently, the only way to mitigate this is to set a low [reserved concurrency](https://docs.aws.amazon.com/lambda/latest/dg/configuration-concurrency.html#configuration-concurrency-reserved).  This will reduce parallelization and should reduce RCU consumption to a degree.

**Comment by mariaines** [comment]
Thanks @atennak1, that is helpful, I'll try that out.
