### ISSUE TITLE
[BUG] Weak date format parsing with DynamoDB Connector

### ISSUE THREAD

**Issue by SeanPrendi** [awslabs/aws-athena-query-federation#185]
**Describe the bug**
The date parsing in the DynamoDB connector seems to be very weak, causing some inconsistencies and issues, with little ability to control it manually. Specifically, if we use the tables schema inference for parsing dates, our date format seems to be parsed as a string. It doesn't seem like there's any way to specify a date format with manually specifying the table schema. When we use Glue we get the issues mentioned in #184, and when we use DDL we have to specify a date format that then leads to inconsistent parsing when our dates are slightly inconsistently stored. While ideally our system should produce dates and times in a 100% consistent format, this isn't always feasible and it seems to create room for a large gap in usability of the connector.

**To Reproduce**
1. Have inconsistent date formats in a table
2. Define the table's schema with and set a date format using the datetimeFormatMapping option
3. Run a query on that table

**Expected behavior**
The connector should be able to correctly interpret dates that are not entirely consistent. 

**Screenshots / Exceptions / Errors**
For example, I don't think it's possible to use the connector to correctly parse each of the following when defining the table schema:

>2020-05-22T04:20:34.7Z
>2020-04-13T09:52:44.97Z
>2019-09-11T12:03:15.4511823Z

Due to the inconsistent length of the last part.

**Connector Details (please complete the following information):**
 - Version: 2020.19.1
 - Name: DynamoDB

**Comment by atennak1** [comment]
We initially planned to do dynamic parsing at the Item level, but this was too much of a performance hit.  Now that we know there are mixed-format cases out there, we can consider making this a configuration parameter for those willing to take the performance hit.

**Comment by henrymai** [comment]
Since #184 is fixed now, you can specify the type of your DateTime column as String in your Glue Table.
Then you can just use Trino's date_parse function here: https://trino.io/docs/current/functions/datetime.html#date_parse
