### ISSUE TITLE
[FEATURE] Add support for postgres array column

### ISSUE THREAD

**Issue by shlomi-viz** [awslabs/aws-athena-query-federation#186]
**Is your feature request related to a problem? If yes, please describe.**
Array type (for example: `text[]`) is not support, while trying to query the table (any column) I get `GENERIC_INTERNAL_ERROR: Index: 0, Size: 0` , I would like to be able to query this type of column.

**Describe the solution you'd like**
Fetch data from `array` column

**Comment by shlomi-viz** [comment]
Any updates? maybe an estimation on when this could be fixed? Thanks

**Comment by avirtuos** [comment]
Hi @shlomi-viz I dont have a date I can commit to at the moment, we are focused on getting this to production (GA) and then will start burning down enhancements more aggressively.

**Comment by eddiesiegel** [comment]
+1 for this request. Even if array columns can't be supported immediately, a useful intermediate step would be to just ignore them so that the other columns in the table can still be queried.

**Comment by shlomi-viz** [comment]
My temp solution is to create a view (for each table with `array` column) and query it (instead of the actual table).
