### ISSUE TITLE
[BUG] Elasticsearch Connector: request contains unrecognized parameter: [ignore_throttled]

### ISSUE THREAD

**Issue by atennak1** [awslabs/aws-athena-query-federation#188]
Opened on behalf of @pvieito

**Describe the bug**
```
java.lang.RuntimeException: com.amazonaws.services.lambda.invoke.LambdaFunctionException: Error processing request to map index (example_index): Elasticsearch exception [type=illegal_argument_exception, reason=request [/example_index/_mapping] contains unrecognized parameter: [ignore_throttled]]
```

**To Reproduce**
`describe federation_elasticsearch.exaple_domain.example_index;`

**Expected behavior**

**Screenshots / Exceptions / Errors**
If applicable, add screenshots, exception stack traces, or error messages to help explain your problem.  Stack traces for exceptions thrown by your Connector can be found in CloudWatch Logs under the 'aws/lambda/<Lambda_function_name>' log group.

**Connector Details (please complete the following information):**
 - Version: 2020.19.1
 - Name: elasticsearch
 - Athena Query IDs [if applicable]

**Additional context**
Used Elasticsearch 6.X

**Comment by shurvitz** [comment]
@pvieito, can I have the exact Elasticsearch version that you are using?

**Comment by pvieito** [comment]
@shurvitz Sure!

```
  "version": {
    "number": "6.5.4",
    "build_flavor": "oss",
    "build_type": "deb",
    "build_hash": "d2ef93d",
    "build_date": "2018-12-17T21:17:40.758843Z",
    "build_snapshot": false,
    "lucene_version": "7.5.0",
    "minimum_wire_compatibility_version": "5.6.0",
    "minimum_index_compatibility_version": "5.0.0"
  }
```

**Comment by shurvitz** [comment]
@pvieito,
Sorry to hear you're experiencing this issue.

It looks like the **ignore_throttled** parameter was added to Elasticsearch V6.6 (first as a beta functionality and officially incorporated in V6.7) to be able to search frozen indices: 
https://www.elastic.co/guide/en/elasticsearch/reference/6.6/searching_a_frozen_index.html
https://www.elastic.co/guide/en/elasticsearch/reference/6.7/searching_a_frozen_index.html

We're looking at using an earlier API version to address your issue and will update you soon.

**Comment by atennak1** [comment]
Looks like the Rest client isn't compatible in either direction (using client 6.5.4 did not work with server 7.4 either).  We'll have to implement some kind of dynamic client loading.

**Comment by avirtuos** [comment]
@atennak1 somewhat hacky but I wonder if we can make the client version a build-time choice (assuming the code / interfaces didnt change) and then from the one code base we can publish a 6.x and a 7.x flavor of the connector to app repo. Thoughts?

**Comment by shurvitz** [comment]
@avirtuos unfortunately the REST client API is significantly different between 6.x and 7.x. However, maybe with a build-time choice for dependencies in combination with an environment variable, we can support 2 different clients at run-time.

**Comment by akuzin1** [comment]
Version 6.8 of Elasticsearch has passed its [EOL date](https://www.elastic.co/support/eol). We recommend upgrading to version 7.10+ of Elasticsearch or migrating to Opensearch. Thank you.
