### ISSUE TITLE
[BUG] where filter in athena returns 0 records and disable_projection_and_casing set to always with connector DynamoDB

### ISSUE THREAD

**Issue by mo2menelzeiny** [awslabs/aws-athena-query-federation#1904]
**Describe the bug**
Athena SQL queries are OK when there are no "where" conditions use columns and use "disable_projection_and_casing" environment variable set.

**To Reproduce**

1. Steps to reproduce the behavior:
2. Set up DynamoDB connector for Athena.
3. Set `disable_projection_and_casing` environment variable to `always`.
4. Configure and run a crawler to scan the table
5. use the generated table from the crawler in a `select *` query
6. see results 
10. Add a where filter `select * from table where column = value`
11. see no results (zero)

**Expected behavior**
the filter results should return values

**Connector Details (please complete the following information):**
 - Version: 2024.10.1 using serverless repo application deployment

**Additional context**
When I unset `disable_projection_and_casing` and add column mapping the same filter query works fine

**Comment by AbdulR3hman** [comment]
Closing this ticket due to being stale... If you are still having issues, please open a new ticket with the information requested in the previous comment. Thank you
