### ISSUE TITLE
[BUG] Using WHERE with date column returns 0 results with connector Athena DynamoDB

### ISSUE THREAD

**Issue by mo2menelzeiny** [awslabs/aws-athena-query-federation#1907]
**Describe the bug**
I have a date column with the format yyyy-MM-dd, when I use it in the queries the results are always 0, I used datetimeFormatMapping="date=yyyy-MM-dd" as outlined in the docs but still the date is not parsed
**To Reproduce**
1. Setup athena dynamo db connector from serverless repository
2. crawl your data and create a table
3. add the appropriate properties like datetimeFormatMapping, columnMapping
4. "select * from <table> where date = date('2024-01-01')
5. results = 0 

**Expected behavior**
the results should return the rows with date field = 2024-01-01

**Screenshots / Exceptions / Errors**
If applicable, add screenshots, exception stack traces, or error messages to help explain your problem.  Stack traces for exceptions thrown by your Connector can be found in CloudWatch Logs under the 'aws/lambda/<Lambda_function_name>' log group.

**Connector Details (please complete the following information):**
 - Version: latest
 - Name dynamodb
 - Athena Query IDs [if applicable]

**Additional context**

**Comment by AbdulR3hman** [comment]
Morning, closing this as we didn't hear back. If you are still facing issues, please open a new ticket with the requested info in the previous comment. Thank you.
