### ISSUE TITLE
Fully qualified table function names for federated query passthrough

### ISSUE THREAD

**Issue by rakimo97** [awslabs/aws-athena-query-federation#1936]
I understand from the docs that:
>  Passthrough queries must be run within the context of the catalog of the outer query (that is, the query that calls the table function)

This is fine when executing queries via the console or directly via the API but third party tools might not provide direct control over the execution context.

For example, dbt will only execute queries in the context where the table is being built into. Therefore it is currently not possible to use  passthrough queries with dbt as you cannot build a table into a federated query catalog.

This could be solved if you could could specify the fully qualified table function in which to execute the passthrough query. ie _<catalog_id>.system.query_. From the Trino docs this seems like it should be possible: https://trino.io/docs/current/develop/table-functions.html#access-control

**Comment by AbdulR3hman** [comment]
Thank you, we've added this to our backlog.
