### ISSUE TITLE
[FEATURE] Migrate to AWS Java SDK v2

### ISSUE THREAD

**Issue by aajisaka** [awslabs/aws-athena-query-federation#1960]
**Is your feature request related to a problem? If yes, please describe.**

AWS Java SDK v2 has been released and now it's widely used. Is there any plan to upgrade it to SDK v2?

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

Migration Task list:
- [x] https://github.com/awslabs/aws-athena-query-federation/issues/2076
- [x] https://github.com/awslabs/aws-athena-query-federation/issues/2078
- [x] https://github.com/awslabs/aws-athena-query-federation/issues/2079
- [x] https://github.com/awslabs/aws-athena-query-federation/issues/2080
- [x] https://github.com/awslabs/aws-athena-query-federation/issues/2081
- [x] https://github.com/awslabs/aws-athena-query-federation/issues/2082
- [x] https://github.com/awslabs/aws-athena-query-federation/issues/2083
- [x] https://github.com/awslabs/aws-athena-query-federation/issues/2084
- [x] https://github.com/awslabs/aws-athena-query-federation/issues/2085
- [x] https://github.com/awslabs/aws-athena-query-federation/issues/2086
- [x] https://github.com/awslabs/aws-athena-query-federation/issues/2087
- [x] https://github.com/awslabs/aws-athena-query-federation/issues/2088
- [x] https://github.com/awslabs/aws-athena-query-federation/issues/2089
- [x] https://github.com/awslabs/aws-athena-query-federation/issues/2090
- [x] https://github.com/awslabs/aws-athena-query-federation/issues/2091
- [x] https://github.com/awslabs/aws-athena-query-federation/issues/2092
- [x] https://github.com/awslabs/aws-athena-query-federation/issues/2093
- [x] https://github.com/awslabs/aws-athena-query-federation/issues/2094

**Comment by macohen** [comment]
Thanks for opening this issue. We do have plans to move to SDK v2. Are you interested in participating in the upgrade? Any questions, comments, concerns, PRs are welcome.

**Comment by aimethed** [comment]
Taking over this issue for tracking the migration to AWS SDK v2.

**Comment by aimethed** [comment]
All changes have been merged in to v2-master branch. Changes will now be tested before merging into master and releasing

**Comment by aimethed** [comment]
Closing as v2 migration branch has been merged to master. Release is being cut now.
