### ISSUE TITLE
Document the raw request/response payloads

### ISSUE THREAD

**Issue by avirtuos** [awslabs/aws-athena-query-federation#20]
Integration with languages other than Java will benefit from detailed documentation on the serialized form required by each request/response. At present we are making heavy use of Jackson's ObjectMapper but we will want to move away from this in the future to something that gives us more control of how we evolve the protocol while minimizing disruption of older clients (Lambda functions).

**Comment by atennak1** [comment]
I'm working on this and should have a PR out within a week.  Primary documentation will be in the form of JSON request and response samples also used in unit tests.

**Comment by richardhboyd** [comment]
Hey, just checking in on this.

**Comment by avirtuos** [comment]
Hey @richardhboyd the documentation and code are in a pull request. We are rolling out the changes to Athena fleet then we will merge the PR so that no one is impacted by the cut over. The PR is public so you are welcome to provide feedback. 

@atennak1 what's the ETA for merging, last I looked the deployment we needed was already in-progress.

**Comment by atennak1** [comment]
Should be able to merge early next week.

**Comment by richardhboyd** [comment]
It's possible that I missed something, but I can't seem to find a commit/merge with the serialized form of the requests/responses.

**Comment by richardhboyd** [comment]
nvm, found it.

https://github.com/awslabs/aws-athena-query-federation/tree/master/athena-federation-sdk/src/test/resources/serde/v2
