### ISSUE TITLE
[BUG] Invalid policy action "dynamodb:ListSchemas" with connector for DynamoDB 

### ISSUE THREAD

**Issue by wmoussa-gc** [awslabs/aws-athena-query-federation#2106]
**Describe the bug**
Perhaps it is just a cleaning exercise, but the policy console flagged that the action "dynamodb:ListSchemas" is not valid.

**To Reproduce**

**Expected behavior**

**Screenshots / Exceptions / Errors**
![image](https://github.com/user-attachments/assets/2fa65811-f362-4cc3-9780-c8a201762d48)

**Connector Details (please complete the following information):**
 - Version: version 2024.25.1
 - Name: AthenaDynamoDBConnector

**Additional context**

**Comment by AbdulR3hman** [comment]
Opened a PR to clean it up; thank you for bring this to our attention.

**Comment by AbdulR3hman** [comment]
merged; again thank you
