### ISSUE TITLE
[BUG] Datacatalog name cannot be prefixed with lambda: in Athena with connector JDBCConnector

### ISSUE THREAD

**Issue by edgarklerks** [awslabs/aws-athena-query-federation#215]
**Describe the bug**
The athena datacatalog data source name requirements clashes with the default connection string. This causes the AthenaJdbcConnector SAM unusable from cloudformation. 

Name of data source specification:

 Use up to 127 characters and must be unique within your account. It cannot be changed after creation. Valid characters are a-z, A-Z, 0-9, _ (underscore), @ (at) and - (hyphen).

From the Readme:
default                         Default connection string. Required. This will be used when catalog is `lambda:${AWS_LAMBDA_FUNCTION_NAME}`.

The *:* is not allowed. 

**To Reproduce**

* Create postgresql rds 
* Create serverless application (AthenaJdbcConnector — version 2020.19.1)
* Create datasource with lambda:<lambda-function-name> <- This will fail 

**Expected behavior**
I expect to have another separator, which is compatible with athena data sources. 

**Connector Details (please complete the following information):**
 - version 2020.19.1
 - Name jdbc
 - Athena Query IDs [if applicable]

**Comment by edgarklerks** [comment]
Workaround is to give the datacatalog a different name and adjust the name manually.

**Comment by avirtuos** [comment]
lambda: is a reserved prefix you can only use it when _not_ registering a data source.
