### ISSUE TITLE
[QUESTION] New Connectors 'wishlist' or 'roadmap'

### ISSUE THREAD

**Issue by gmsharpe** [awslabs/aws-athena-query-federation#216]
I have a question that I don't think is related to a bug or feature request. 

Is there a 'wishlist' or 'roadmap' for new connectors published somewhere?  I'm looking for another side project and I happen to also be evaluating Athena's Federated Queries for my day job.

**Comment by avirtuos** [comment]
We are not yet publishing a roadmap of new connectors. The closest to a wishlist would be the currently open feature enhancements. I couldn't tell from your description but are you looking to build a new connector and wondering what might be a useful one to build that we aren't currently working on?

**Comment by gmsharpe** [comment]
Hi Anthony!  Yes, sorry for not clarifying.  I am interested in starting a new connector to get a feel for the process, framework and such from the ground up.  If you have any ideas, let me know.

**Comment by avirtuos** [comment]
Cassandra or accumulo might be interesting connectors to consider. A way to run a query against Flink is another interesting one though more complex since Flink query (e.g. query over a stream) lifecycles are much different than Athena.

**Comment by gmsharpe** [comment]
Awesome.  Thank you.  All sound interesting.  I'll let you know if I get anything off the ground.
