### ISSUE TITLE
[QUESTION] Column descriptions in Athena UI

### ISSUE THREAD

**Issue by BernardOrzechowski** [awslabs/aws-athena-query-federation#219]
I have a question that I don't think is related to a bug or feature request. 

I deployed some of your examples (athena-example, dynamodb) but in none of them the table columns are displayed in Athena UI.

I was writing my own connector,though that I have a bug, but the reference code you provide (MetadataHandler/doGetTable) doesnt produce the right metadata needed in the UI.

Take a look at the attached screenshot.
![athena_missing_column_descriptions](https://user-images.githubusercontent.com/7222949/87874274-cd1b9300-c9c8-11ea-8f41-be9ef2ed9647.PNG)

The MetadataHandler/doGetTable returns a new GetTableResponse -  I thought that the schema object will work with Athena UI, but it doesnt...

```
return new GetTableResponse(request.getCatalogName(),
                request.getTableName(),
                schema, 
                Collections.EMPTY_SET
                );
```

Can you share a code snippet how to add columns to Athena UI? **The columns are visible when I execute "describe $catalog.$schema.$table;"**

**Comment by avirtuos** [comment]
I believe this is an intentional issue. There were some challenges with the time it took for these fields to populate so they were left blank in the UI for now. I'll keep this issue open for us to confirm when this will be fixed / supported.

**Comment by nauy2697** [comment]
Hi,

Thanks for reaching out, metadata for a table should show in our Athena WebUI now.

Closing ticket, if you have any additional questions, feel free to re-open
