### ISSUE TITLE
[QUESTION] General question

### ISSUE THREAD

**Issue by gmsharpe** [awslabs/aws-athena-query-federation#221]
I have a question that I don't think is related to a bug or feature request. 

I apologize in advance if this is a particularly annoying kind of question.  I'm not sure where to inquire about release timelines, though.  Does the team have any target in mind for promoting this service out of Preview status?

I think a UDF would be perfect for some of the use cases I have at work right now.  I likely have 3 - 6 months before I need something that is production ready.  I don't want to invest too much time on this approach, though, if the release is quite a ways off.  There are certainly other ways I can solve this problem in the short term, if needed.

Sorry again, and I understand if the answer is simply, "we don't know" or "we can't answer that".

Looking forward to using AQF in the future, regardless.

**Comment by avirtuos** [comment]
If you email me at virtuoso [at] amazon.com, I'll put you in touch with our product manager who can give you a better answer to this question. Probably the safest thing I can say is that I expect us to meet your timeline and if we don't ... I'll be pretty surprised/disappointed.
