### ISSUE TITLE
[BUG] List database with JDBC connection

### ISSUE THREAD

**Issue by yipez-spec** [awslabs/aws-athena-query-federation#2251]
**Describe the bug**

**To Reproduce**
1. Create any jdbc metadata handler instance, for example: jdbc:snowflake://%s.snowflakecomputing.com:%s/?warehouse=%s&user=%s&password=%s
2. Call doListSchemaNames

**Expected behavior**
We should be able to retrieve a list of database + their corresponding schemas 

**Screenshots / Exceptions / Errors**
If applicable, add screenshots, exception stack traces, or error messages to help explain your problem.  Stack traces for exceptions thrown by your Connector can be found in CloudWatch Logs under the 'aws/lambda/<Lambda_function_name>' log group.

**Connector Details (please complete the following information):**
 - Version: [e.g. 2020.04.01 - if you are unsure, look at the tags on the Lambda function. One of the tag should contain the version if you deployed via Serverless Application Repo.] latest
 - Name [e.g. redis, hbase, jdbc] snowflake
 - Athena Query IDs [if applicable] 

**Additional context**

**Comment by yipez-spec** [comment]
Code with problems:
https://github.com/yipez-spec/aws-athena-query-federation/blame/master/athena-snowflake/src/main/java/com/amazonaws/athena/connectors/snowflake/SnowflakeMetadataHandler.java#L568

Code with problems:
https://github.com/awslabs/aws-athena-query-federation/blob/master/athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcMetadataHandler.java#L154C25-L154C42

**Comment by AbdulR3hman** [comment]
Hi, I'm not sure we have enough to replicate the issue; It could be the user that is passed to the connector (the connection string) does not have permission to retrieve all the schemas; or catalogs/databases. the code you've referred to is the two codes that list schemas/databases; but what exactly is the problem you are referring to? (as in the code); if you can provide us with more details maybe we can try to replicate it on our end;

**Comment by yipez-spec** [comment]
I checked with Burhan and looks like it's an expected behavior but more like a limitation on any database with more than 2 levels.
