### ISSUE TITLE
[BUG] inconsistent generic error with connector documentDB

### ISSUE THREAD

**Issue by WillLiu360** [awslabs/aws-athena-query-federation#229]
**Describe the bug**
I'm getting this "GENERIC_INTERNAL_ERROR: Row type must have at least one parameter" when querying a fairly large docdb collection(about 21m documents) attached screenshot from the athena console as well as lambda connector logs. it happens 90% of the time but occasionally will work without any changes.

**To Reproduce**
Steps to reproduce the behavior(inconsistently):
1. Go to 'athena console'
2. Click on 'preview table'

**Expected behavior**
preview first 10 rows of data

**Screenshots / Exceptions / Errors**
![Screen+Shot+2020-08-04+at+12 54 01+PM](https://user-images.githubusercontent.com/17725649/89333291-c34d8d00-d662-11ea-94e5-c12ababc6487.png)
![Screen+Shot+2020-08-04+at+12 51 46+PM](https://user-images.githubusercontent.com/17725649/89333326-cf394f00-d662-11ea-9c14-c76267f266d4.png)

**Connector Details (please complete the following information):**
 - Version: connector was deployed about 2 months back, not sure where to find the version
 - Name [athena-docdb]
 - Athena Query IDs [if applicable]

**Additional context**
I saw this for dynamoDB https://github.com/awslabs/aws-athena-query-federation/issues/75, not sure it's related.

**Comment by WillLiu360** [comment]
spend about 2 hours with aws support in chat today and they suggest we open a ticket here while they investigate further intenally.

**Comment by avirtuos** [comment]
Hi @WillLiu360 my apologies that you had to spend so much time with aws support and didn't get a resolution to your issue.

I have a few follow up questions:

1. What version of the connector are you using? You can find this by looking at the tags on the lambda function, you should see one that says something like 2020.x.x
2. Can you share the athena query id for an example where you got this failure? I'll be able to look up some logs within Athena to see if we get more info on the failure.
3. You mentioned that the error is inconsistent, can you give more detail on what you mean by that? does the query work sometimes? or with certain tables but not others? If it works sometimes but not others can you also provide a query id where it worked?

The error that you pasted above is indicates that one of the columns on your table, as defined in Glue, is not a supported type or may have a name with illegal characters. In more recent versions of the connector we have improved this logging to show which column and why.

**Comment by shurvitz** [comment]
@WillLiu360, You can try using `string` instead of `varchar` in your Glue metadata definitions. From the CloudWatch logs you included it looks like the processing of the Glue supplemental metadata processing is aborted due to a varchar column type.

**Comment by shurvitz** [comment]
@WillLiu360, Let us know if that resolved your issue.
