### ISSUE TITLE
[BUG] DocumentDB (MongoDB) connector can't handle Database with uppercase letters

### ISSUE THREAD

**Issue by tlierdotfr** [awslabs/aws-athena-query-federation#2312]
**Describe the bug**
There is a property that allow the connector to match Collections that have UpperCase letters in their name with appropriate GlueDB definition but it seems like that there is no such process for Database names that also may contains UpperCase letters.

**To Reproduce**

1. Set up MongoDB and the DocumentDB connector for Athena.
2. Configure the Glue database "mydatabase" to match existing MongoDB database "myDatabase"
3. Set the URI parameter to "docdb-metadata-flag"
4. Configure the Glue table "data" with "docdb-metadata-flag" set to true and sourceTable property set to "data"
5. In Athena, query the collection either using : `select * from mydatabase.data` or `select * from myDatabase.data`
7. See no results at all

**Expected behavior**
The query should display results accordingly to table content.

**Screenshots / Exceptions / Errors**
Query without any rows : 
![image](https://github.com/user-attachments/assets/91d2e37d-099b-42c5-8677-0bea048783b5)

Using `SELECT * FROM TABLE(system.query( ... ))` seems to work but unfortunately this querying method is not compatible with Athena Quicksight DataSource.
![image](https://github.com/user-attachments/assets/b235acab-e907-4a0a-8185-f9e25d4ec24a)

**Connector Details (please complete the following information):**
 - Version: 2024.25.1
 - Name aws-athena-query-federation for DocumentDB

**Additional context**
I use MongoDB 4.4 data source and not DocumentDB for this use case.

**Comment by AbdulR3hman** [comment]
Hi; this was resolved; please see `enable_case_insensitive_match` in our documentation; https://docs.aws.amazon.com/athena/latest/ug/connectors-docdb.html
