### ISSUE TITLE
[BUG] Update Athena Federation Summary Image to remove databases not supported 

### ISSUE THREAD

**Issue by s4saurabh** [awslabs/aws-athena-query-federation#237]
**Describe the bug**
This image https://raw.githubusercontent.com/awslabs/aws-athena-query-federation/master/docs/img/athena_federation_summary.png on this repository home page shows Oracle and Sql Server as part of Athena federation even though JDBC connector doesn't support Oracle and Sql Server databases.

**To Reproduce**
1. Go to https://github.com/awslabs/aws-athena-query-federation
2. Scroll down and check the image for Athena federation: 
3. The image shows Oracle and SqlServer data sources even though they are not supported yet. 

**Expected behavior**
Update the image to remove Oracle and Sql Server so that customers are not confused.

**Screenshots / Exceptions / Errors**
https://raw.githubusercontent.com/awslabs/aws-athena-query-federation/master/docs/img/athena_federation_summary.png

**Connector Details (please complete the following information):**
 N/A

**Additional context**
N/A

**Comment by henrymai** [comment]
Both are supported now.
