### ISSUE TITLE
[QUESTION] DocumentDB unable to find valid certification

### ISSUE THREAD

**Issue by GreinV** [awslabs/aws-athena-query-federation#2389]
I installed AthenaDocDBConnection through the Serverless Application Repository.  
And I'm getting the following error:

```
Timed out after 30000 ms while waiting for a server that matches com.mongodb.client.internal.MongoClientDelegate$1@21a5fd96. Client view of cluster state is {type=REPLICA_SET, servers=[{address=db_address, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketWriteException: Exception sending message}, caused by {javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target}, caused by {sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target}, caused by {sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target}}]: com.mongodb.MongoTimeoutException
```

How can I add the SSL certificate if I don’t have access to the code? Or what am I doing wrong?

`default_docdb: mongodb://<user>:<pass>@<host>:<port>/?tls=true&ssl_ca_certs=rds-combined-ca-bundle.pem&replicaSet=rs0`

`IMAGE_URI: 292517598671.dkr.ecr.us-east-1.amazonaws.com/athena-federation-repository-docdb:2024.42.3`

**Comment by GreinV** [comment]
Can anyone help?

**Comment by danielOfir1** [comment]
I am experiencing exactly the same error, I also tried version 2024.46.1 but the same issue occurs.
To add some more information, I am also seeing in the lambda's logs:
`WARN  uri:86 - Connection string contains unsupported option 'tlscafile'.`

**Comment by GreinV** [comment]
Any solutions?

**Comment by GreinV** [comment]
I just provided the URL link to the certificate, and it worked.
`ssl_ca_certs=https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem`
