### ISSUE TITLE
[QUESTION] Access to a cross - account table via DynamoDB Connector

### ISSUE THREAD

**Issue by tudor-a** [awslabs/aws-athena-query-federation#239]
I have a question that I don't think is related to a bug or feature request. 

Is there a way to enable Athena+DDB Connector from account A to query a DynamoDB table in account B by using the ddb connector? If there is another way to group them, please suggest, any idea would be very welcome!

Is there a way to do this by applying cross-account IAM rules, without changing the java source code?
I've been testing some cross - account IAM roles trying to make this work, but haven't been successful so far.
Thanks!

**Comment by avirtuos** [comment]
I believe this would require some code changes to how the DDB client is instantiated.
