### ISSUE TITLE
[BUG] END_OBJECT: java.lang.IllegalStateException with connector JDBC MySQL 

### ISSUE THREAD

**Issue by batrahs** [awslabs/aws-athena-query-federation#243]
**Describe the bug**
JDBC MySQL connector is failing with exception "END_OBJECT: java.lang.IllegalStateException"

**To Reproduce**
1. Create Data Source for MySQL
2. Try to connect to this DataSource in Athena console
3. No Databases will be displayed and in Cloud Watch log for lambda you will get this error

This is same issue as reported earlier https://github.com/awslabs/aws-athena-query-federation/issues/223

**Expected behavior**
Connection to data source should succeeded

**Screenshots / Exceptions / Errors**

Expected field name token but got END_OBJECT: java.lang.IllegalStateExceptionjava.lang.IllegalStateException: Expected field name token but got END_OBJECT	at com.amazonaws.athena.connector.lambda.serde.BaseDeserializer.assertFieldName(BaseDeserializer.java:221)	at com.amazonaws.athena.connector.lambda.serde.BaseDeserializer.getNextStringField(BaseDeserializer.java:82)	at com.amazonaws.athena.connector.lambda.serde.FederatedIdentitySerDe$Deserializer.doDeserialize(FederatedIdentitySerDe.java:103)	at com.amazonaws.athena.connector.lambda.serde.FederatedIdentitySerDe$Deserializer.deserialize(FederatedIdentitySerDe.java:84)	at com.amazonaws.athena.connector.lambda.serde.PingRequestSerDe$Deserializer.doTypedDeserialize(PingRequestSerDe.java:96)	at com.amazonaws.athena.connector.lambda.serde.PingRequestSerDe$Deserializer.doTypedDeserialize(PingRequestSerDe.java:72)	at com.amazonaws.athena.connector.lambda.serde.DelegatingDeserializer.doDeserialize(DelegatingDeserializer.java:59)	at com.amazonaws.athena.connector.lambda.serde.DelegatingDeserializer.deserializeWithType(DelegatingDeserializer.java:49)	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:63)	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3807)	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2867)	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:99) | Expected field name token but got END_OBJECT: java.lang.IllegalStateException java.lang.IllegalStateException: Expected field name token but got END_OBJECT at com.amazonaws.athena.connector.lambda.serde.BaseDeserializer.assertFieldName(BaseDeserializer.java:221) at com.amazonaws.athena.connector.lambda.serde.BaseDeserializer.getNextStringField(BaseDeserializer.java:82) at com.amazonaws.athena.connector.lambda.serde.FederatedIdentitySerDe$Deserializer.doDeserialize(FederatedIdentitySerDe.java:103) at com.amazonaws.athena.connector.lambda.serde.FederatedIdentitySerDe$Deserializer.deserialize(FederatedIdentitySerDe.java:84) at com.amazonaws.athena.connector.lambda.serde.PingRequestSerDe$Deserializer.doTypedDeserialize(PingRequestSerDe.java:96) at com.amazonaws.athena.connector.lambda.serde.PingRequestSerDe$Deserializer.doTypedDeserialize(PingRequestSerDe.java:72) at com.amazonaws.athena.connector.lambda.serde.DelegatingDeserializer.doDeserialize(DelegatingDeserializer.java:59) at com.amazonaws.athena.connector.lambda.serde.DelegatingDeserializer.deserializeWithType(DelegatingDeserializer.java:49) at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:63) at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3807) at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2867) at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:99)
-- | --

**Connector Details (please complete the following information):**
 - Version: [e.g. 2020.04.01] Latest code from repo - 868cb34
 - Name [e.g. redis, hbase, jdbc] jdbc
 - Athena Query IDs [if applicable] 

**Additional context**
None

**Comment by avirtuos** [comment]
@burhan94 @atennak1 Hey team, this is the 2nd time we are received reports that this change has broken customers. Can you please take a look and then come back to me with details on whats going on and if true, why our testing isn't catching this before we push these commits?

@batrahs for now, can you try building against the last tagged release (https://github.com/awslabs/aws-athena-query-federation/tree/v2020.33.1)? There are cases where master will be broken when used with prod Athena, though we do aim to minimize that.

**Comment by avirtuos** [comment]
@burhan94 and @batrahs  any updates?

**Comment by burhan94** [comment]
Hi @batrahs, 

So this issue affects Federated DDL, and should be mitigated if you use the the latest tagged release (https://github.com/awslabs/aws-athena-query-federation/tree/v2020.33.1). We are currently deploying a fix, and it should be available within the next few days.

**Comment by burhan94** [comment]
Fix was deployed last week.
