### ISSUE TITLE
[DOC] Glue table column name mapping with connector DynamoDB

### ISSUE THREAD

**Issue by shurvitz** [awslabs/aws-athena-query-federation#245]
**Describe the bug**:

**The following behavior can be confusing to customers and should be documented to facilitate proper setup of Glue tables when used for supplemental metadata definitions.**

When using an AWS Glue table for supplemental metadata definitions, Glue will convert all column names to lowercase (**with the exception of columns within a complex structure or nested array**). In order to accommodate column names in AWS Glue that do not conform to Glue naming convention (all lowercase), federated queries use the `columnMapping` key (in the **Table properties**) to map column names defined in Glue to their corresponding names in the actual data source used by the individual connectors.

It is important to note that the mapping works fine for simple types, but does not work for columns within nested complex types such as structs or nested arrays. Essentially, **only first-level column names can be mapped**. 

However, since **Glue allows mixed-case letters in the nested column names**, the latter can be made to match the names of the corresponding columns in the DDB data source allowing queries to continue to work.

**To Reproduce**:
1. Create a DynamoDB table with a Map element that has a mixed-case name, containing a field with a mixed-case name. 
2. Use a crawler to create a Glue table for the same DDB table (notice that the newly create a table with a lowercase name for the struct column).
3. Run a **select** query on the table and observe that no information is returned.
4. Add `columnMapping` in the Glue table's **Table properties** `<Glue column name>=<DDB column name>`.
5. Run the **select** query again and observe that it now works even though the nested column is mixed-case. That is because the crawler does not automatically change the case of column names within a complex type. If, however, the names did not match, the returned result would have been `null`.

**Connector Details (please complete the following information):**
 - Version: 2020.33.1
 - Name: DynamoDB

**Additional context**:
This issue was first observed by Cx (https://t.corp.amazon.com/V243439710) using the DynamoDB connector.

**Comment by shurvitz** [comment]
Supporting columnMapping for nested column is not recommended since the field can easily get cluttered with information and therefore more prone to errors.

**Comment by kevindekemele** [comment]
It is not clear how to add the `columnMapping` key to the Glue table's Table properties.
Does the value have to be an array for all columns you have to map? Or should it be true? Where to fill in `<Glue column name>=<DDB column name>` ?

**Comment by rajak178** [comment]
Hi
@shurvitz 

Can you please provide more details on how you are adding columnMapping in Table properties of catalog table to read camelCased names in actual data source?

Thanks

**Comment by brifordwylie** [comment]
Silly question.. I've tried to get the Glue Crawler NOT to lowercase all my column names but haven't figure out how to do that. Does anyone have a suggestion or document pointer that I can look at? 

Thanks in advance :)

**Comment by henrymai** [comment]
@brifordwylie This is a limitation of Glue itself (it only supports lowercased column names).

There is a new feature in the DynamoDB connector that will let you query your columns defined your Glue Table as if there is no case sensitivity at all. See `disable_projection_and_casing` here: https://docs.aws.amazon.com/athena/latest/ug/connectors-dynamodb.html#connectors-dynamodb-parameters

**Comment by henrymai** [comment]
columnMapping documentation has been updated as well to say that it only applies to the top level: https://docs.aws.amazon.com/athena/latest/ug/connectors-dynamodb.html

> columnMapping – Optional table property that defines column name mappings. Use this if AWS Glue column naming rules prevent you from creating a AWS Glue table with the same column names as your DynamoDB table. For example, capital letters are not permitted in AWS Glue column names but are permitted in DynamoDB column names. The property value is expected to be in the format col1=Col1,col2=Col2. Note that column mapping applies only to top level column names and not to nested fields.
