### ISSUE TITLE
[QUESTION] Can this work with Quicksight 

### ISSUE THREAD

**Issue by fotherda71** [awslabs/aws-athena-query-federation#252]
I have a question that I don't think is related to a bug or feature request. 

I have got the Amazon Athena DynamoDB Connector working in that it appears as a table in Athena and can be queried. However I can't use it in Quicksight. When I try to connect to the table using the Athena data source connector it finds the data columns and types correctly but it cannot load any data. It gives the following error:

sourceErrorCode:	
100071
sourceErrorMessage:	
[Simba][AthenaJDBC](100071) An error has been thrown from the AWS Athena client. HIVE_UNKNOWN_ERROR: java.net.URISyntaxException: Relative path in absolute URI: arn:aws:dynamodb:eu-west-1:451642671797:table/user_data
sourceErrorState:	
HY000
sourceException:	
java.sql.SQLException
sourceType:	
ATHENA

Maybe I'm not configuring it correctly or maybe what I'm trying to do is not yet possible. If it's the latter then is there another way to view dynamoDB data in Quicksight?

Thanks Dave

**Comment by avirtuos** [comment]
Quicksight support is in the works. I don't believe it works 'out of the box' right now. Did you query from quicksight generate any logs for the Athena Lambda function in cloudformation?

**Comment by fotherda71** [comment]
No it didn't produce anything in the logs but I got the immediate error shown above.

**Comment by fotherda71** [comment]
@avirtuos Is this the preferred alternative to integrating DynamoDB with Quicksight: https://aws.amazon.com/blogs/database/how-to-perform-advanced-analytics-and-build-visualizations-of-your-amazon-dynamodb-data-by-using-amazon-athena/

**Comment by matt-helios** [comment]
@fotherda71 I used that method and it works.  Was curious about using federated queries with quick sight too

**Comment by aidansteele** [comment]
@fotherda71 Have you tried again lately? I noticed that there was an AWS blog post published a few hours ago indicating this should indeed work: https://aws.amazon.com/blogs/big-data/accessing-and-visualizing-data-from-multiple-data-sources-with-amazon-athena-and-amazon-quicksight/

**Comment by henrymai** [comment]
This already works, see this related issue: https://github.com/awslabs/aws-athena-query-federation/issues/776
