### ISSUE TITLE
[BUG] ARN value missing in FederatedIdentity data when connected over JDBC. "UNKNOWN_ARN" instead

### ISSUE THREAD

**Issue by dvdotsenko** [awslabs/aws-athena-query-federation#253]
When using AWS Web UI Console's Athena UI to make requests, my user's ARN comes across as value of `arn` attribute of FederatedIdentity object.

When using JDBC ( Intellij DataGrip plugin + AthenaJDBC42_2.0.14.jar from https://docs.aws.amazon.com/athena/latest/ug/connect-with-jdbc.html ) for same IAM user, `arn` attribute contains `"UNKNOWN_ARN"` string.

JDBC connection string `jdbc:awsathena://us-east-1.amazonaws.com:443;UID=AKIA############;PWD=###############;Workgroup=AmazonAthenaPreviewFunctionality;` 

SQL Query:
```
select table_schema, table_name
from my.information_schema.tables
where table_schema = '{some valid schema name here}'
```

One of several requests to Lambda handling `my` catalog:
```
{
    "@type": "ListTablesRequest",
    "identity": {
        "id": "UNKNOWN",
        "principal": "UNKNOWN",
        "account": "897117390337",
        "arn": "UNKNOWN_ARN",  // <------------------
        "tags": {},
        "groups": []
    },
    "queryId": "666883c1-5177-437f-8183-7fada2475b72",
    "catalogName": "my",
    "schemaName": null  // <--------- note odd null value here. Expect a string
}
```

Another SQL statement:
```
select * from my."{some valid schema name here}"."board1195__2020_{fragment removed for privacy reasons}_Instagram_Facebook__chart2950__IG_FB_Placement_Performance"
```

One of several requests to Lambda handling `my` catalog:
```
2020-09-27 01:06:41 bd9d0379-860a-4233-97ef-233accee6a38 INFO  CompositeHandler:54 - Raw Request: {"@type":"GetTableRequest","identity":{"id":"UNKNOWN","principal":"UNKNOWN","account":"897117390337","arn":"UNKNOWN_ARN","tags":{},"groups":[]},"queryId":"40e77462-2cee-4ea0-84a2-40e78e341926","catalogName":"my","tableName":{"schemaName":"{some valid schema name here}","tableName":"board1195__2020_{fragment removed for privacy reasons}_instagram_facebook__chart2950__ig_fb_placement_performance"}}
```

**Expected behavior**

SOME form of user identity must be present in `FederatedIdentity` object data. Without it, cannot match IAM user to our internal user and proper credentials to fulfill the query.

**Connector Details (please complete the following information):**
- Version:
 Git Commit 8b9cdec by Shachar Hurvitz <shurvitz@amazon.com> Sep 23, 2020 at 10:05
 - Name lambda handler example `athena-example` 
 - Athena Query IDs are within the request JSON examples above.

**Comment by burhan94** [comment]
Hi, 

I haven't enabled the feature globally yet. It will become public in the next few weeks, but I can whitelist your account so that you can try it out. Is 897117390337 the correct account to whitelist? What region are you using?

**Comment by dvdotsenko** [comment]
> I haven't enabled the feature globally yet. It will become public in the next few weeks, but I can whitelist your account so that you can try it out. Is 897117390337 the correct account to whitelist? What region are you using?

897117390337 is the correct (Staging) AWS account.

us-east-1

Thank you

**Comment by burhan94** [comment]
Can you retry your query now and let me know what the results are?

**Comment by dvdotsenko** [comment]
@burhan94 

Tried request at 2020-09-28 19:02:21 UTC (Noon Sept 28 US Pacific)

```
2020-09-28 19:02:21 5950a758-d7e9-447c-b3c1-f464aff37509 INFO  CompositeHandler:54 - Raw Request: 
{
    "@type": "ListSchemasRequest",
    "identity": {
        "id": "UNKNOWN",
        "principal": "UNKNOWN",
        "account": "897117390337",
        "arn": "UNKNOWN_ARN",  <--- don't see ARN value yet.
        "tags": {},
        "groups": []
    },
    "queryId": "8835b776-6482-4fe3-8cb7-4c022f65bbae",
    "catalogName": "my"
}
```

**Comment by burhan94** [comment]
Oops, sorry I made a small mistake during the whitelist process, can you retry the query again? Sorry for the back and forth. Double checked it this time.

**Comment by dvdotsenko** [comment]
@burhan94 

It's a beauty!

```
2020-09-28 20:36:47 f8a31c05-b6c8-4a3b-bf8c-0fa69e669b6c INFO  CompositeHandler:54 - Raw Request: 
{
    "@type": "ListSchemasRequest",
    "identity": {
        "id": "UNKNOWN",
        "principal": "UNKNOWN",
        "account": "897117390337",
        "arn": "arn:aws:iam::897117390337:user/ddotsenko",  // <----------------------
        "tags": {},
        "groups": []
    },
    "queryId": "b9cc3cb8-8050-48d4-b0ec-259997366035",
    "catalogName": "my"
}
```

Look forward to GA announcement on your side. How would I know this is in GA?
Hoped to move this to production account 583912811210 (us-east-1) in ~3 weeks.

**Comment by atennak1** [comment]
Stay tune to the AWS announcements page for GA news!
