### ISSUE TITLE
[BUG] Between Syntax Invalid with connector Elasticsearch

### ISSUE THREAD

**Issue by RossWilliams** [awslabs/aws-athena-query-federation#255]
**Describe the bug**
Using a SQL BETWEEN keyword results in an elasticsearch predicate that fails to parse by the lucene DSL.

**To Reproduce**
1. Query with Elasticsearch Syntax similar to: `SELECT * FROM "lambda:x".y.z WHERE a BEWEEN Date('2020-09-01') and Date('2020-10-01')`
2. Notice the predicates use <= AND >= syntax in CloudWatch
3. Notice Athena reports an issue and does not return results
4. Refer to the elastic documentation [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html) recommending to use the Range syntax instead as it is easier to parse.
5. Run query in elastic using Range syntax, notice no issues and results are returned

**Expected behavior**
Valid SQL against data should return results, not cause Elasticsearch 400 error responses.

**Additional context**
The code below handles lower bound and upper bound.  It looks like it could be converted to range syntax without much restructuring.

https://github.com/awslabs/aws-athena-query-federation/blob/8b9cdecc9c869ecfdb32a8484566bf72b14320e4/athena-elasticsearch/src/main/java/com/amazonaws/connectors/athena/elasticsearch/ElasticsearchQueryUtils.java#L180

**Comment by avirtuos** [comment]
@RossWilliams Thanks for finding this. Sounds like you might even have a proposed fix in mind. Have you considered submitting a pull request with a fix? We'd gladly accept the contribution :) If not, we will prioritize addressing the issue. 

@shurvitz This seems like another one for you as you are most familiar with this connector at the moment.
