### ISSUE TITLE
[FEATURE] Provide columns to be selected to the handler

### ISSUE THREAD

**Issue by KevinGlinski** [awslabs/aws-athena-query-federation#257]
I'm using a custom handler to wrap a REST API to query data in an external system and then hooking tableau up to query athena.  When setting a filter in tableau (or any other BI tool) it will do a "Select distinct userName from users" and return all the values of foo to display in a pick list.

With query federation, It would be helpful if i knew what fields were being selected because in this case I have a list of all userNames that I can return if it is the only field being selected and I never have to hit the external API.  Similar, it I only need a column or two besides the userName, I can request only those two columns from the API which improves API query performance.

For complex queries, it may not be possible, but this use case doesn't apply as much for complex queries.

**Comment by hackett123** [comment]
The Athena V3 query engine will now apply projection pushdown if applicable to your queries. We get your table's schema with `GetTable`, then the engine will attempt to create a new schema with only the input columns, and sends that projection schema down to your connector for `ReadRecords`. So, the columns to be selected are already provided and trimmed down for the handler.

Here's some proof from the latest mysql jar against the TPCDS table `store_sales`:

Running a select * generates this debug log:
```
Generated SQL : SELECT `ss_sold_date_sk`, `ss_sold_time_sk`, `ss_item_sk`, `ss_customer_sk`, `ss_cdemo_sk`, `ss_hdemo_sk`, `ss_addr_sk`, `ss_store_sk`, `ss_promo_sk`, `ss_ticket_number`, `ss_quantity`, `ss_wholesale_cost`, `ss_list_price`, `ss_sales_price`, `ss_ext_discount_amt`, `ss_ext_sales_price`, `ss_ext_wholesale_cost`, `ss_ext_list_price`, `ss_ext_tax`, `ss_coupon_amt`, `ss_net_paid`, `ss_net_paid_inc_tax`, `ss_net_profit` FROM `test`.`store_sales`
```

Running a select against just one column generates this debug log:
```
Generated SQL : SELECT `ss_customer_sk` FROM `test`.`store_sales`
```

So, in your handler, to know what fields are being selected, you can just read the input schema to the ReadRecordsRequest.
