### ISSUE TITLE
[BUG] Mixed Case Tables  with connector Amazon TimeStream

### ISSUE THREAD

**Issue by ashpad** [awslabs/aws-athena-query-federation#265]
**Describe the bug**
While using the Amazon TimeStream Connector, if the Timestream Schema/Table contains mixed case. The Athena query does not work.

Error :
GENERIC_USER_ERROR: Encountered an exception[com.amazonaws.services.timestreamquery.model.ValidationException] from your LambdaFunction[arn:aws:lambda:us-east-1:525474232104:function:timestreamcatalog] executed in context[retrieving meta-data] with message[Requested database 'sampledb' not found for identifier 'sampledb.iot' at line 1:1 (Service: AmazonTimestreamQuery; Status Code: 400; Error Code: ValidationException; Request ID: FZ62COAQDUZZRFG4ZXEZ4E2V3U; Proxy: null)]
 
 
 

**Additional context**
Per discussions this is because the connector currently doesnt support mixed case due to (Timestream is case-sensitive, i.e., UTF-8 binary comparison) while Athena isn’t

**Comment by hackett123** [comment]
This was fixed recently with https://github.com/awslabs/aws-athena-query-federation/pull/1201. Closing this issue.
