### ISSUE TITLE
[BUG] GSI does not work in filter  with connector  dynamodb

### ISSUE THREAD

**Issue by sivankumar86** [awslabs/aws-athena-query-federation#279]
**Describe the bug**
  SQL query failed when GSI added in where condition and GSI was created with selected field 

**To Reproduce**
1. Go to  Dynamodb and create a table with 6 columns
2. Create a GSI with only few columns
3. Go to Athena and run select * from table ## it would work 
4.  Run select * from table where GSIkey='<condition>'

Error:
 GENERIC_USER_ERROR: Encountered an exception[com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException] from your LambdaFunction[arn:aws:lambda:us-east-1:3423423423:function:dynamo] executed in context[S3SpillLocation{bucket='athendfdfsaaiad', key='athedna-spill/0f8ff141-b562-47d1-a755-86ac39d58c1f/ed16b1eb-6270-44aa-8ac1-7dbe1993dbfe', directory=true}] with message[One or more parameter values were invalid: Global secondary index elb_name-index does not project [request_verb] (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: dsfasdfsadfasdfasdfasdf; Proxy: null)]

**Expected behavior**
  It should return all the columns as per select query even if GSI does not contains that column then fetch from table using table pkey.

Used latest version connector 
athena-dynamodb-1.0.jar

**Comment by henrymai** [comment]
This issue has been fixed by the pull request above
