### ISSUE TITLE
Postgres Athena Federated Query Error : table not found [Issue]

### ISSUE THREAD

**Issue by nikspatel03** [awslabs/aws-athena-query-federation#281]
I'm getting following error while querying postgres schema from athena federated query.  I can see Schema and table populated in Athena console through Data source but while executing query getting following error: 

WARN  CompositeHandler:104 - handleRequest: Completed with an exception.java.lang.RuntimeException: Could not find table in my_schema_name at com.amazonaws.connectors.athena.jdbc.manager.JdbcMetadataHandler.getSchema(JdbcMetadataHandler.java:247) ~[task/:?]	at com.amazonaws.connectors.athena.jdbc.manager.JdbcMetadataHandler.doGetTable(JdbcMetadataHandler.java:216) ~[task/:?]	at com.amazonaws.connectors.athena.jdbc.MultiplexingJdbcMetadataHandler.doGetTable(MultiplexingJdbcMetadataHandler.java:116) ~[task/:?]	at com.amazonaws.athena.connector.lambda.handlers.MetadataHandler.doHandleRequest(MetadataHandler.java:250) ~[task/:?]	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:132) ~[task/:?]	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:100) [task/:?]	at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:902) [LambdaSandboxJava-1.0.jar:?]	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:341) [LambdaSandboxJava-1.0.jar:?]	at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:63) [LambdaSandboxJava-1.0.jar:?]	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_201]	at java.lang.Class.forName(Class.java:348) [?:1.8.0_201]	at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:150) [LambdaJavaRTEntry-1.0.jar:?] |
-- | --

**Comment by mcuelenaere** [comment]
We're suffering from this as well using the MySQL JDBC connector. It looks like tables consisting of lowercase characters only **do** work however.

Our current workaround is to create views and naming then using just lowercase characters.

**Comment by gaoyuming** [comment]
I've run into the same issue when using federated query against RDS resources through JDBC connectors. The target tables or columns must be in lower case. If the name is in UPPER case or Mixed case, query fails.

I am able to walk around this issue by creating views in the target DB using lowercase names, as mcuelenaere@ suggested.

AWS documentation noted that Athena is case insensitive, hence the table and column names are changed into lower case. 

I can see there is another opened issue #61  which is flagged as "enhancement" for exploring the possibilities of adding case mapping at the JDBC connector level.

https://github.com/awslabs/aws-athena-query-federation/issues/61

**Comment by edvorkin** [comment]
What about database name? My db name is in mixed case and I still see the issue even for the lower case tale name

**Comment by ykrystal** [comment]
Duplicate. Please follow [#61](https://github.com/awslabs/aws-athena-query-federation/issues/61) for updates.
