### ISSUE TITLE
[BUG] Athena Console freezes with connector athena-jdbc to mysql

### ISSUE THREAD

**Issue by existeundelta** [awslabs/aws-athena-query-federation#287]
Just refresh metadata of the source produce that Athena Console freeze, and at the same time ther are about 4k invocations of the lambda function just to get the metadata

with:
com.amazonaws.connectors.athena.jdbc.MultiplexingJdbcCompositeHandler

java8

**Comment by akuzin1** [comment]
Thank you for reaching out, the `athena-federation-jdbc` connector has actually been deprecated and we suggest migrating over to data source specific connector, which in your case will be AthenaMySQLConnector — version 2023.16.2. This should resolve your issues.
