### ISSUE TITLE
[BUG]  getSchema: Unable to map type for column[datetime] with connector athena-federation-jdbc to mysql

### ISSUE THREAD

**Issue by existeundelta** [awslabs/aws-athena-query-federation#289]
**Describe the bug**
An Error is thrown trying to map column type Datetime
ERROR JdbcMetadataHandler:242 - getSchema: Unable to map type for column[datetime] to a supported type, attempted Timestamp(MILLISECOND, null)

**Comment by avirtuos** [comment]
Datetime is not currently in the list of supported types.

**Comment by shurvitz** [comment]
@existeundelta It's likely that https://github.com/awslabs/aws-athena-query-federation/pull/314 fixed this issue for the JDBC connectors. Can you try again with the patch, and let us know.

**Comment by shurvitz** [comment]
New version of the connector (which contains a fix for this is now available) is now available: v2020.51.1. Closing issue.
