### ISSUE TITLE
[BUG] DateTimeFormatterUtil timestamp round-trip fails

### ISSUE THREAD

**Issue by ahggns** [awslabs/aws-athena-query-federation#293]
**Describe the bug**
`DateTimeFormatterUtil#packDateTimeWithZone` and `DateTimeFormatterUtil#constructZonedDateTime` does not produce a round-trip equivalence.

**To Reproduce**
I have test cases for this on a branch here: https://github.com/awslabs/aws-athena-query-federation/compare/master...ahggns:ah/datetimeformatter-roundtrip

**Comment by avirtuos** [comment]
Hey @soojinj I think you are most familiar with this code path. Can you take a look? Should be a quick test/fix.

**Comment by avirtuos** [comment]
@soojinj I vaguely recall you had reached a conclusion on this on Friday but I dont see an update here. Can you refresh our memories as to where this landed?

**Comment by soojinj** [comment]
Hi @ahggns I was able to check your test cases. The reason for this discrepancy is because we normalize all UTC equivalent timezones (including Z) as UTC. However, I did notice the underlying value is actually the same time in same time zone as well, so it shouldnt cause any data incorrectness.

Expected :2015-12-21T17:42:34Z
Actual   :2015-12-21T17:42:34Z[UTC] 

I will look into it further to see if there is anything we can do to conserve the data as is.

**Comment by avirtuos** [comment]
I chatted with @ahggns earlier today, they are going to revisit this given @soojinj 's update.

**Comment by ahggns** [comment]
Hi @soojinj,

I believe that you're correct that the slightly different offset format doesn't seem to be an issue. I think the issue I'm actually having relates to the time zone of the system where the `constructZonedDateTime` method is called.

It looks like the `DateTimeFormatterUtilTest` sets the default timezone to UTC before running any tests:
https://github.com/awslabs/aws-athena-query-federation/blob/349bef30d9ff6643673435a3ec52426391247081/athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/data/DateTimeFormatterUtilTest.java#L49-L53

Our connector implementation doesn't set the time zone, so when I run tests (from the East Coast of the US) I get a non-UTC result on this line:
https://github.com/awslabs/aws-athena-query-federation/blob/349bef30d9ff6643673435a3ec52426391247081/athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/data/DateTimeFormatterUtil.java#L307

-Andrew

**Comment by avirtuos** [comment]
@ahggns I may be miss-understanding but I believe we are doing this because Athena uses UTC as its base timezone, in an attempt to simplify the matrix of client, server, data timezone conversions. If this doesn't help calrify what is happening, can you share what behavior you'd expect?

**Comment by ahggns** [comment]
So the system time zone when our connector runs is guaranteed to be UTC? In that case I think we can do the same thing in our tests to set the default timezone before doing any timestamp conversions.

Is there any documentation I can reference in a comment to explain why we're doing this?
