### ISSUE TITLE
[BUG] Error running 'describe' statement from Athena console with custom connector

### ISSUE THREAD

**Issue by ahggns** [awslabs/aws-athena-query-federation#294]
**Describe the bug**
In the Athena console running a custom connector, DDL statements with backquoted identifiers results in an error message stating that backquoted identifiers are not supported.

**To Reproduce**
1. I have a custom connector with a lambda function named `foundry-athena` with a database `"foundry"`. 
2. I run the following command in the Athena console:
```
DESCRIBE `lambda:foundry-athena`."foundry"."/my/table/name"
```

**Expected behavior**
Per documentation at https://github.com/awslabs/aws-athena-query-federation/tree/master/athena-example this is the correct syntax.

**Screenshots / Exceptions / Errors**
Running describe command above results in the following error  (appears inside the query editor rather than above where errors during query execution appear.
```
line 1:10: backquoted identifiers are not supported; use double quotes to quote identifiers (service: amazonathena; status code: 400; error code: invalidrequestexception; request id: 338c13ac-4159-4843-bead-a13570c15dcc)
```

**Comment by shurvitz** [comment]
Hi Andrew,
Can you try removing the double-quotes around the database and table name (as shown in the example) or use the back-quote instead?

The following works for me:

describe \`lambda:ddb\`.default.movies; (this is the notation from the example)

This also works:

describe \`lambda:ddb\`.\`default\`.\`movies\`;

If neither works, can you share the connector type and version you are using?

**Comment by avirtuos** [comment]
@shurvitz Can you confirm if you tried to reproduce? I don't think we need Andrew to try these permutations. We can test ourselves and validate but I've seen whats in the documentation work many times. We may have a regression on our side if it no longer works...or some copy-paste trickiery is afoot with the recent doc updates.

**Comment by ahggns** [comment]
Using exclusively backticks did get past this specific error:
```
DESCRIBE `lambda:foundry-athena`.`foundry`.`/my/table/name`
```

This did result in a new error, though, after a successful response by our service to the `doGetTable` method in the connector. Seems a more detailed stacktrace didn't make it to CloudWatch.
```
Your query has the following error(s):

java.lang.RuntimeException: java.lang.IllegalArgumentException

This query ran against the "foundry" database, unless qualified by the query. Please post the error message on our forum or contact customer support with Query Id: 583bfef5-dfeb-4e21-87d3-0b9edde54b55.
```

**Comment by shurvitz** [comment]
@ahggns I may need more information in order to recreate your issue as the above seems to work for me. Also, the query ID you specified only contains 2 arguments for the describe query, but needs 3. 

Can you share the following information: Which connector are you using (and version)?

**Comment by ahggns** [comment]
This is for a new custom connector we're working on that we're currently running in our dev account. 

I'm running these statements in the Athena query editor on the AWS console, I'm not sure how the query is getting mapped to arguments. I may have copied an error from a query that didn't explicitly specify the schema, so just in case here's a fresh one:

```
DESCRIBE `lambda:foundry-athena`.`foundry`.`/palantir/athena/fruit-parquet`;
```
```
Your query has the following error(s):

java.lang.RuntimeException: java.lang.IllegalArgumentException

This query ran against the "foundry" database, unless qualified by the query. Please post the error message on our forum or contact customer support with Query Id: e920e9b9-c119-4021-afa5-2ec8b2fb8484.

**Comment by shurvitz** [comment]
@ahggns Is there a specific reason your table argument contains slashes? Typically, this argument should not be a path, just the table name.

**Comment by ahggns** [comment]
The slash notation is how tables are referenced in the target system. 

Unfortunately I can't find any related logs in CloudWatch.

**Comment by shurvitz** [comment]
Unfortunately, I haven't been able to recreate the issue here. Even if I specify a slash in the table name, I still get a CloudWatch log. It's hard for me to say w/o seeing the code, but I can make a couple suggestions though:
1. Rebase your code with the GA version of the SDK (2020.46.1).
2. Instead of specifying the table path in the query, use an environment variable that you can pass in via the CloudFormation stack (i.e. your connector.yaml) to map the table to the correct path. This will allow you to do the mapping from within the doGetTable() implementation.

**Comment by avirtuos** [comment]
@ahggns were you able to make progress here?

**Comment by ahggns** [comment]
Yes, this seems to be due to us having had Arrow 2.0.0 jars on the classpath in the lambda function (our backend service runs with 2.0.0). We removed those to ensure we were taking the 0.11.0 jars from the sdk's dependencies and the describe command is now working.
