### ISSUE TITLE
[FEATURE] Publish SDK to public package repository

### ISSUE THREAD

**Issue by ahggns** [awslabs/aws-athena-query-federation#300]
Are there plans to publish the SDK jars and tools to a public package repository? We're currently developing our connector internally and it would be helpful if we could reference the SDK artifact on a public channel rather than needing to download the jar from github.

**Describe the solution you'd like**
Publish SDK jar (and sources jar) to a public package repository like jcenter, bintray, or maven-central. As a bonus it would be helpful if the validation tooling was available for consumption through a public channel.

**Describe alternatives you've considered**
We're currently doing this manually with our internal systems so we can refer to sdk artifacts.

**Comment by avirtuos** [comment]
Yes, this is certainly on our todo list. I'm not 100% sure yet if we will publish to central or self-host but either way you'll be able to pull a copy of the pre-compiled artifacts from a maven compatible repository.

**Comment by avirtuos** [comment]
@burhan94 can we prioritize this. EMR team has folks that are familiar with this process if you aren't sure where to begin. Let me know and I can connect you with the appropriate people.

**Comment by chadmorrow** [comment]
This would be extremely helpful. Bonus points if put on maven central with the other AWS SDK's.

**Comment by avirtuos** [comment]
This is absolutely be in central. Wheels are moving though slowly due to ReInvent commitments and holidays. Stay tuned.

**Comment by chadmorrow** [comment]
Any update on this?

**Comment by mojodna** [comment]
It appears to be in central now (https://search.maven.org/artifact/com.amazonaws/aws-athena-federation-sdk), but the last release there was from February (2022.7.1).

**Comment by henrymai** [comment]
> It appears to be in central now (https://search.maven.org/artifact/com.amazonaws/aws-athena-federation-sdk), but the last release there was from February (2022.7.1).

Latest version is now up (2022.23.1).
