### ISSUE TITLE
Identity is only partially populated

### ISSUE THREAD

**Issue by aidansteele** [awslabs/aws-athena-query-federation#301]
Hi,

Now that query federation is generally available, I tried it out but found that the `identity` field is not being fully populated. Here's an example of the input my Lambda function gets:

```json5
{
    "@type": "PingRequest",
    "identity": {
        "id": "UNKNOWN",
        "principal": "UNKNOWN",
        "account": "607481581596",
        "arn": "UNKNOWN_ARN",
        "tags": {},
        "groups": []
    },
    "catalogName": "compress",
    "queryId": "bd3b0cd8-8a43-4862-a57b-9bb7975662b2"
}

{
    "@type": "UserDefinedFunctionRequest",
    "identity": {
        "id": "UNKNOWN",
        "principal": "UNKNOWN",
        "account": "607481581596",
        "arn": "UNKNOWN_ARN",
        "tags": {},
        "groups": []
    },
    "inputRecords": {
        "aId": "bd3b0cd8-8a43-4862-a57b-9bb7975662b2",
        "schema": "<truncated by me>",
        "records": "<truncated by me>"
    },
    "outputSchema": "<truncated by me>",
    "methodName": "compress",
    "functionType": "SCALAR"
}
```

In the wiki page on [Known limitations](https://github.com/awslabs/aws-athena-query-federation/wiki/Limitations_And_Issues) it mentions that this isn't populated, but I'm not sure if this has been updated since GA. It links to #26 but that was closed back in July. 

There's also #253 where they got the correct input after their account was whitelisted. @atennak1 said to stay tuned for GA - which made me think this should be fixed? My apologies if I've misunderstood.

Is this expected behaviour or a bug? Let me know if there's anything else I can provide to help debug this.

**Comment by avirtuos** [comment]
Sounds like a bug to me. Can you share a query id and confirm if this was in a Preview workgroup or regular workgroup? I don't think all the recent fixes have been applied to the preview workgroup, at some point we started prepping for production and updating the preview was not viable. That will be remedied for future previews. 

@burhan94 is this on your radar as a know limitation of GA? I doubt it.

**Comment by aidansteele** [comment]
Sorry I should have clarified. The query ID and account ID in the example are real queries that I ran and failed. 

This was using a non-preview workgroup and Athena engine v2

**Comment by burhan94** [comment]
So UDF's aren't GA yet. We are aiming to release UDF and Sagemaker support soon, however. Stay tuned.

**Comment by aidansteele** [comment]
That makes sense - thanks for the clarification. Looking forward to it. You folks have done amazing work.
