### ISSUE TITLE
[BUG] <BUILD FAILURE> with connector <athena-jdbc>

### ISSUE THREAD

**Issue by HowardXia** [awslabs/aws-athena-query-federation#302]
**Describe the bug**
Failed to build athena-jdbc in cloud9 m5.large newly created.

I am trying to tweak athena-jdbc for oracle, my first step is to make sure if the "Package and Deploy" works fine before any code changes.

**To Reproduce**
Just follow the same steps for athena-example at 
https://github.com/awslabs/aws-athena-query-federation/tree/master/athena-example

Step 1 - Step 3  Good
Step 4: Write The Code : **NO CODE CHANGE just for testing deploy**
Step 5: Package and Deploy Your New Connector 
~/environment/aws-athena-query-federation/athena-jdbc (master) $ ../tools/publish.sh <MY_S3_BUCKET_NAME> athena-jdbc us-east-1
After ran command above, into error:
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.978 s
[INFO] Finished at: 2020-11-17T00:07:00Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project athena-jdbc: Could not resolve dependencies for project com.amazonaws:athena-jdbc:jar:1.0: Failed to collect dependencies at com.amazonaws:aws-athena-federation-sdk:jar:2020.46.1: Failed to read artifact descriptor for com.amazonaws:aws-athena-federation-sdk:jar:2020.46.1: Could not find artifact com.amazonaws:aws-athena-query-federation:pom:1.0 in redshift (https://s3.amazonaws.com/redshift-maven-repository/release) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Additional context**
Could you please advise how to resolve build failure?

**Comment by avirtuos** [comment]
Looks like you forgot to build the sdk first. Try building the sdk module first. The athena-example project has the step by step build instructions incase you aren't sure which directory is the sdk.

**Comment by HowardXia** [comment]
Hi Athony,

Thanks for your response.
I built the sdk successfully, and confirmed the aws-athena-federation-sdk-2020.46.1.jar generated. 
Below is command history.
    1  git clone https://github.com/awslabs/aws-athena-query-federation.git
    2  cd aws-athena-query-federation/
    3  ./tools/prepare_dev_env.sh
    4  source ~/.profile
    5  ls
    **6  cd athena-federation-sdk
    7  mvn clean install -DskipTests=true > /tmp/log**
    8  cd ../
    9  ls
   10  cd athena-jdbc/
   11  ../tools/publish.sh oracle-connector-bucket athena-jdbc us-east-1
   12  history

Thanks & Reagrds,
Howard Xia

**Comment by avirtuos** [comment]
Did the sdk build succeed? The above error looks like it couldn't find the sdk jar

**Comment by HowardXia** [comment]
yes, aws-athena-federation-sdk-2020.46.1.jar is generated in target folder.

**Comment by avirtuos** [comment]
can you try building athena-example? When I get to my computer I'll see if I can reproduce the issue.

**Comment by HowardXia** [comment]
Got error too.

[INFO] 
[INFO] --------------------< com.amazonaws:athena-example >--------------------
[INFO] Building athena-example 1.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.327 s
[INFO] Finished at: 2020-11-17T14:07:18Z
[INFO] ------------------------------------------------------------------------
**[ERROR] Failed to execute goal on project athena-example: Could not resolve dependencies for project com.amazonaws:athena-example:jar:1.0: Failed to collect dependencies at com.amazonaws:aws-athena-federation-sdk:jar:2020.46.1: Failed to read artifact descriptor for com.amazonaws:aws-athena-federation-sdk:jar:2020.46.1: Failure to find com.amazonaws:aws-athena-query-federation:pom:1.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]**
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by HowardXia** [comment]
I tried athena-example a couples of days before, it worked. but in different Cloud9 ENV. 
My Cloud9 ENV for athena-example was deleted, it was t2.micro, Current is m5.large.

I'll try different Cloud9 env.

**Comment by avirtuos** [comment]
I just pulled a fresh copy from the repo on a new cloud9 env and all the connectors built without issue. I a bit stumped as to what kind of issue could cause your maven cli to fail to find the jars but I'm not sure what else to suggest aside from start with a clean (maybe even new) cloud9 env and carefully capture the output of the setup steps.  You can use the linux 'script' ( https://man7.org/linux/man-pages/man1/script.1.html ) to capture all output. In the event you run into the issue again, you can potentially share the info captured by script and we can give you a 2nd set of eyes to see what might be going wrong.

**Comment by HowardXia** [comment]
I'll try different new cloud9 environment, thanks a lot,

**Comment by HowardXia** [comment]
Hi Anthony,

I tried mvn clean install at root, then build athena-jdbc, it went through without error.
Seems like athena-jdbc not only depend on sdk, also depend on something other project. 
Just not sure which one, **Could you please advise which one else other than sdk need to build first?**
If build root, then build athena-jdbc, got error **"[Errno 28] No space left on device: 'packaged.yaml'"**,
connector not get deployed. I am using m5.large.

[INFO] --- maven-install-plugin:2.4:install (default-install) @ athena-jdbc ---
[INFO] Installing /home/ec2-user/environment/aws-athena-query-federation/athena-jdbc/target/athena-jdbc-1.0.jar to /home/ec2-user/.m2/repository/com/amazonaws/athena-jdbc/1.0/athena-jdbc-1.0.jar
[INFO] Installing /home/ec2-user/environment/aws-athena-query-federation/athena-jdbc/pom.xml to /home/ec2-user/.m2/repository/com/amazonaws/athena-jdbc/1.0/athena-jdbc-1.0.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 15.073 s
[INFO] Finished at: 2020-11-17T17:13:29Z
[INFO] ------------------------------------------------------------------------
Uploading to 8e170129f7abb5c6ce68f13d048c0c14  9922 / 9922.0  (100.00%)
Uploading to f2192c03aa492ef2104991bb8be53aba  10107 / 10107.0  (100.00%)
Uploading to bee6c1ad6790d5852cfe3f43d0559652  32424612 / 32424612.0  (100.00%)
**Error: Failed to package template: /home/ec2-user/environment/aws-athena-query-federation/athena-jdbc/athena-jdbc.yaml. 
 [Errno 28] No space left on device: 'packaged.yaml'**

 Thanks & Regards,
Howard.

**Comment by avirtuos** [comment]
@HowardXia How much disk space do you have on that instance? you may need to give it a larger root volume. I'd expect 16Gb would be more than enough.
