### ISSUE TITLE
[FEATURE] Validation flag to expect zero tables

### ISSUE THREAD

**Issue by ahggns** [awslabs/aws-athena-query-federation#304]
**Is your feature request related to a problem? If yes, please describe.**
The connector validation tool currently fails if no tables are returned from the lambda function (during the `SHOW TABLES` phase). Due to scale limitations my connector will not be able to list tables via this API.

**Describe the solution you'd like**
Can a flag be added to the connector validator to tell the validation tooling to expect zero tables to be returned?

**Describe alternatives you've considered**
For now I've just forked the code to disable this assertion.

**Comment by avirtuos** [comment]
I've made the requested change, once the build/test pass I'll merge it for you. ETA is probably 30 min for review + build + merge

**Comment by avirtuos** [comment]
merged. if you pulled the latest from the repo you'll get the changes. add a '-e' flag to the validator command to disable show tables non-empty checks.
