### ISSUE TITLE
[BUG] NullPointerException with connector athena-udfs. 

### ISSUE THREAD

**Issue by freemanlutsk** [awslabs/aws-athena-query-federation#305]
**Describe the bug**
Problem with `nulltype` column.  https://docs.delta.io/latest/delta-batch.html#nulltype-columns  
**To Reproduce**
Try to encrypt `NULL` row.

**Screenshots / Exceptions / Errors**
```GENERIC_USER_ERROR: com.facebook.presto.spi.PrestoException: Encountered an exception[java.lang.RuntimeException] from your LambdaFunction[athena_user_defined_functions] executed in context[calling UDF method encrypt] with message[java.lang.NullPointerException]```

**Connector Details (please complete the following information):**
 - serverlessrepo:semanticVersion: 2020.35.1
 - Athena Query IDs `6e9f66c8-150f-4472-af1d-ca186f048b74`

**Additional context**
With condition `WHERE blabla_id<>''and username<>''` works as expected.

**Comment by avirtuos** [comment]
Can you share the stacktrace (logs) of you Lambda function? This error originated in your Lambda function.

**Comment by freemanlutsk** [comment]
Do you mean this trace ?

`java.lang.NullPointerException: java.lang.RuntimeExceptionjava.lang.RuntimeException: java.lang.NullPointerException	at com.amazonaws.athena.connector.lambda.handlers.UserDefinedFunctionHandler.invokeMethod(UserDefinedFunctionHandler.java:530)	at com.amazonaws.athena.connector.lambda.handlers.UserDefinedFunctionHandler.lambda$makeExtractor$10(UserDefinedFunctionHandler.java:463)	at com.amazonaws.athena.connector.lambda.data.writers.fieldwriters.VarCharFieldWriter.write(VarCharFieldWriter.java:77)	at com.amazonaws.athena.connector.lambda.data.writers.GeneratedRowWriter.writeRow(GeneratedRowWriter.java:116)	at com.amazonaws.athena.connector.lambda.handlers.UserDefinedFunctionHandler.processRows(UserDefinedFunctionHandler.java:213)	at com.amazonaws.athena.connector.lambda.handlers.UserDefinedFunctionHandler.processScalarFunction(UserDefinedFunctionHandler.java:173)	at com.amazonaws.athena.connector.lambda.handlers.UserDefinedFunctionHandler.processFunction(UserDefinedFunctionHandler.java:160)	at com.amazonaws.athena.connector.lambda.handlers.UserDefinedFunctionHandler.doHandleRequest(UserDefinedFunctionHandler.java:146)	at com.amazonaws.athena.connector.lambda.handlers.UserDefinedFunctionHandler.handleRequest(UserDefinedFunctionHandler.java:131)Caused by: java.lang.NullPointerException	at com.amazonaws.athena.connectors.udfs.AthenaUDFHandler.encrypt(AthenaUDFHandler.java:189)	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)	at java.lang.reflect.Method.invoke(Method.java:498)	at com.amazonaws.athena.connector.lambda.handlers.UserDefinedFunctionHandler.invokeMethod(UserDefinedFunctionHandler.java:521)	... 8 more`


BTW I’ve created workaround with `CAST(0 AS VARCHAR(256))`, it helped me to replace `NULL` to `0`. Currently works as expected.

**Comment by dbadaya1** [comment]
Resolved
