### ISSUE TITLE
[BUG] Workgroup issue with connector DynamoDB Connector

### ISSUE THREAD

**Issue by tudor-a** [awslabs/aws-athena-query-federation#306]
Hi,
I have deployed the DynamoDB connector to a new account, with all necessary resources created successfully. The account is Tokyo, ap-northeast-1.
I manually created a new Workgroup named AmazonAthenaPreviewFunctionality and tried running some queries with this connector - basic select queries and `show tables (...)`.
I am unable to execute a query on this workgroup, so there are no logs to add here. The error I get in Athena is pasted below.
I tried using a Glue crawler to create a new database/table for this DynamoDB table, but this wasn't helpful.
Is this somehow related to the account itself?
Thanks 

**Screenshots / Exceptions / Errors**
**Your query has the following error(s):
The given Workgroup name is a reserved Athena Workgroup Name. Please submit your query using a different Workgroup. (Service: AmazonAthena; Status Code: 400; Error Code: InvalidRequestException)**

**Connector Details :**
 - Version: 2020.46.1
 - DynamoDB Connector
 - Request ID: ddb9143a-b07d-491d-a6f7-7df6e3b644c2

**Comment by avirtuos** [comment]
ap-northeast-1 is not one of our Preview regions. Also, these features are now GA and starting to roll out to all regions. You can currently use them in US-East-1, Us-East-2, or Us-West-2 without a special workgroup.
