### ISSUE TITLE
[FEATURE] Delta Lake Connector

### ISSUE THREAD

**Issue by rubenssoto** [awslabs/aws-athena-query-federation#310]
Hello,

Now it is possible to query delta lake files through manifest files, but it would be good for performance reasons have a connector that really understands delta lake format and take advantage of delta lake log.

Is It possible?

https://github.com/delta-io/delta

Thank you.

**Comment by avirtuos** [comment]
This is on our radar but too soon for me to share details. Customers should feel free to +1 this issue to help is understand popularity of supporting Delta format.

**Comment by rubenssoto** [comment]
thank you so much!

Delta has a Standalone Reader, could help you

https://github.com/delta-io/connectors

**Comment by scMarkus** [comment]
We do have a use case with an ever growing historical table partitioned by day and the schema within the partitions can arbitrarily change. Currently for each added column we need to manually update Hive Metastore via Presto. To have Deltas schema evolution capabilities combined with atomic changes seamlessly integrated into Presto would be a huge benefit to us.

Furthermore it might even reduce the necessity for having an external Hive Metastore. Yes, i am aware that many companies use the Metastore to kind of solve the issues i have just described. But for a dedicated use case it might be beneficial
to have at least to option to not maintain an additional service and use the storage layer which should scale equally well or better to persist the meta data. 

Looking forward to this !

**Comment by malonsocasas** [comment]
Hello, 
Thanks for this issue, we are really interested in this feature too ! 
Are there some update on it ? Is it possible to help ? 
Thanks a lot !

**Comment by devstein** [comment]
> This is on our radar but too soon for me to share details

@avirtuos Can you share any more details now? Would love to see this capability.

**Comment by abin-tiger** [comment]
+1

**Comment by henrymai** [comment]
See: https://github.com/awslabs/aws-athena-query-federation/pull/825#issuecomment-1359839427
