### ISSUE TITLE
[BUG] forward slashes in database name/LogGroup with connector AthenaCloudWatch (Logs)

### ISSUE THREAD

**Issue by leafmulch** [awslabs/aws-athena-query-federation#312]
**Describe the bug**

When Athena console populates its tables from the selected database all you see is a spinning circle and in the developer tools network window you can observe 404's. This only occurs when there is a forward slash in the database name (which reflects the name of the corresponding Log Group.)

This is a very common naming convention in the CloudWatch Log Group names and therefore this should be a common occurrence.
 
**To Reproduce**
1. Go to Athena console
2. Click on CloudWatch datasource.
3. and then a database including '/' in its name
4. See 404 error in Chrome developer tools and spinning circle

**Expected behavior**
When there is no '/' in the database name the tables and fields populate correctly. I would expect this to be the same behaviour regardless of whether a '/' was in the name or not.

**Screenshots / Exceptions / Errors**
![image](https://user-images.githubusercontent.com/9284517/100746948-501e1280-33d9-11eb-97ac-c2bd0f50ea5c.png)

**Connector Details (please complete the following information):**
 - Version: 2020.46.1
 - Name: AthenaCloudWatchConnector
 - Athena Query IDs n/a

**Additional context**
n/a

**Comment by akuzin1** [comment]
Thank you for reaching out. Upgrading your Cloudwatch connector should resolve this issue.
