### ISSUE TITLE
[FEATURE] Apache Kudu connector

### ISSUE THREAD

**Issue by qwalker** [awslabs/aws-athena-query-federation#315]
Is there any plan or ongoing work on kudu connector? Any advices on athena query federation with kudu?

**Comment by avirtuos** [comment]
Can you share more about your use case?

**Comment by qwalker** [comment]
@avirtuos Sure. We have a OLAP system. We use kudu to store user properties and recent days' user behaviors.  User properties are being updated frequently, and user behaviors are mostly append only logs. We snapshot user properties and offload historical user behaviors to S3, and use Presto to query data in S3 and kudu together.  For better scalability, We really want to use Athena to query S3 and Kudu together, so we need a Kudu connector for Athena.

**Comment by hackett123** [comment]
If you are looking for a Kudu connector, you can engage with your AWS support representative or account manager to get it onto the product team's radar. The Athena service team currently has no plans to add a new connector for Kudu.
