### ISSUE TITLE
[QUESTION] Is calling a UDF over JDBC possible?

### ISSUE THREAD

**Issue by shaider0802** [awslabs/aws-athena-query-federation#321]
I just set up a Postgresql database (RDS) for federated queries. It turns out that we can't call user defined functions available in the postgresql database (e.g. a table-valued SQL function). I have three questions in that regard:
1. Can anyone pls. confirm that indeed this is the case (I tried more than one ways of invoking the UDF, but got syntax error or table not found error, showing that the federated query only works with tables.
2. I'm assuming it's to prevent side-effects (since a UDF in postgresql can do DML). Can you pls. confirm if that's the underlying reason?
3. Finally, is it possible to write one's own connector that is able to call postgresql user defined functions? 

Thanks

**Comment by shurvitz** [comment]
@shaider0802, Can you share your query(s)?

**Comment by avirtuos** [comment]
Athena Federation only support federating table scan and certain predicate operations. If you are attempting to use postgres UDFs in your Athena query, that is not supported.
