### ISSUE TITLE
[BUG] <descrption of issue> with connector <connector type>

### ISSUE THREAD

**Issue by matt-helios** [awslabs/aws-athena-query-federation#323]
**Describe the bug**
mvn clean install fails for Athena-dynamodb

**To Reproduce**
I run mvn clean install from the sdk directory first.

Then I run mvn clean install from the Athena-dynamodb directory and get the following:

```
[ERROR] Failed to execute goal on project athena-dynamodb: Could not resolve dependencies for project com.amazonaws:athena-dynamodb:jar:1.0: Failure to find com.amazonaws:athena-federation-integ-test:jar:2020.51.1 in https://s3-us-west-2.amazonaws.com/dynamodb-local/release was cached in the local repository, resolution will not be reattempted until the update interval of dynamodb-local-oregon has elapsed or updates are forced -> [Help 1]
[ERROR] 
```

Am running on MacBook with Big Sur.

**Comment by avirtuos** [comment]
Did you build the module it is complaining about?  Looks like you haven't built the integration test module. 

@shurvitz did you update the readme for this connector and the example connector when we added this new dependency?

**Comment by matt-helios** [comment]
Thanks for fast reply.  I'm a java noob.  What commands should I run?

**Comment by avirtuos** [comment]
Go into the athena-federation-integ-tesr directory and run the below command

 mvn clean install

**Comment by matt-helios** [comment]
Yes that worked!
