### ISSUE TITLE
[QUESTION] Federated queries with QuickSight?

### ISSUE THREAD

**Issue by matt-helios** [awslabs/aws-athena-query-federation#326]
I set up the federated query and it worked great with Athena.  However, I wanted to generate visualizations with QuickSight and my federated queries weren't an option in QuickSight. Is this not supported?

**Comment by avirtuos** [comment]
It should indeed be an option. I'd reach out to Quicksight team for support as I have seen them demo this working. There may be some nuances that I am not aware of. Worse case, let us know and I'll see if I can track down a good contact.
