### ISSUE TITLE
[QUESTION] Is Aurora MySQL Supported?

### ISSUE THREAD

**Issue by gmsharpe** [awslabs/aws-athena-query-federation#329]
I have a question that may be related to a bug or feature request, but thought it'd be easy to first pose as a general inquiry.

**Is Aurora MySQL supported with the JDBC connector?**  I realize that the list for the connector specifies only 'MySQL, Postgres & Redshift' in the official doc, but I want to clarify whether this includes Aurora Postgres &/or MySQL before I try to troubleshoot my Jdbc Connector deployment.

Thank you!

**Comment by avirtuos** [comment]
Yes, aurora mysql and postgres should work though not all data types are supported.

**Comment by gmsharpe** [comment]
Awesome.  Thanks, Anthony!  I'll fiddle with my connector config a bit.  I imagine I made some trivial mistake in the deployment.

**Comment by avirtuos** [comment]
Don't hesitate to post the error message or issue you are facing. Two common issues I've seen oth the JDBC connector are:

1. Ensuring your Lambda function is in the proper VPC and have proper security groups to access the aurora instance from a network perspective. 
2. Password with special characters sometimes give us issues (past bugs) but I think those have all been patched.
