### ISSUE TITLE
[FEATURE] AWS Cognito connector

### ISSUE THREAD

**Issue by matthias-pichler-warrify** [awslabs/aws-athena-query-federation#346]
**Is your feature request related to a problem? If yes, please describe.**

We store personal identifiable information of a user (such as name, email etc) in AWS Cognito and prefer to only have it there as to make sure these kind of things get deleted properly when the user deletes their profile (for GDPR compliance). We use the `sub` everywhere else. To connect some analytical data to things like the user's email address we would like to be able to `JOIN` to the User Pool in AWS Cognito.

**Describe the solution you'd like**

A connector to AWS Cognito that can be deployed via the Serverless Application Repository to connect to AWS Cognito. (Even cross account!)

**Describe alternatives you've considered**

I thought about a batch export from cognito into S3.

**Additional context**

**Comment by hackett123** [comment]
If you are looking for a Cognito connector, you can engage with your AWS support representative or account manager to get it onto the product team's radar. The Athena service team currently has no plans to add a new connector for Cognito.

**Comment by hackett123** [comment]
Updating closure status.
