### ISSUE TITLE
[BUG] MySQL Date type fields do not properly display

### ISSUE THREAD

**Issue by aiasmartakis** [awslabs/aws-athena-query-federation#349]
RDS with Mysql 5.7 does not properly convert dates (of Date type) to the correct year (instead they show dates in/around 1969).
Example:
SELECT m.id, m.date_field FROM "rds"."injobs"."milestone" m limit 10

returns 1967-09-26

RDS directly
SELECT m.id, m.date_field FROM injobs.milestone m LIMIT 10
returns 2018-11-05

The field type in mysql is date

**Comment by shurvitz** [comment]
What version of the connector are you using?

**Comment by aiasmartakis** [comment]
strange I installed it from the AWS serverless repo five days ago, however it is tagged:

serverlessrepo:semanticVersion | 2020.51.1

I see the serverlessrepo now indeed has the 2021.6.1 version

**Comment by aiasmartakis** [comment]
What is the best way to upgrade to the latest? remove the old cloudformation an install fresh?

**Comment by aiasmartakis** [comment]
I installed it on top with the same name (as per https://docs.aws.amazon.com/serverlessrepo/latest/devguide/serverlessrepo-how-to-consume-new-version.html) which did the trick. I'll test it now, once I confirm I'll close the bug.

Slightly wondering why these serverless repo connectors don't show in the published apps under the 'serverless repo' service, but that's a question for another forum :)

**Comment by aiasmartakis** [comment]
Confirmed 2021.6.1 fixes it!
