### ISSUE TITLE
[FEATURE] Google BigQuery support

### ISSUE THREAD

**Issue by jdrake** [awslabs/aws-athena-query-federation#353]
**Is your feature request related to a problem? If yes, please describe.**
No

**Describe the solution you'd like**
A native or JDBC connector for Google BigQuery

**Describe alternatives you've considered**
Am considering hacking the existing athena-jdbc connector

**Additional context**
Looks like the BigQuery connector was removed in https://github.com/awslabs/aws-athena-query-federation/pull/49. I'm curious if there's a reason why?

**Comment by burhan94** [comment]
Hi @jdrake 

BQ connector is in the pipeline. If you'd like to get a sneak peak, feel free to reach out to our PM scottrig@amazon.com

**Comment by avirtuos** [comment]
@burhan94 are we reviving the one @hocanint-amzn wrote before launch last year?

**Comment by burhan94** [comment]
Thats the plan. Scott and I are trying to compile a list of interested customers, and we will proceed from there.

**Comment by hocanint-amzn** [comment]
Sweet, please let me know if I can be of any assistance in its revival.
