### ISSUE TITLE
[FEATURE] Snowflake support

### ISSUE THREAD

**Issue by jdrake** [awslabs/aws-athena-query-federation#354]
Is your feature request related to a problem? If yes, please describe.
No

Describe the solution you'd like
A native or JDBC connector for Snowflake

Describe alternatives you've considered
Am considering hacking the existing athena-jdbc connector

Additional context
N/A

**Comment by henrymai** [comment]
There's a snowflake connector now: https://github.com/awslabs/aws-athena-query-federation/tree/master/athena-snowflake
