### ISSUE TITLE
[BUG] Query that returns TIME type throws GENERIC_USER_ERROR with connector Athena-Vertica

### ISSUE THREAD

**Issue by asimjalis** [awslabs/aws-athena-query-federation#357]
**Describe the bug**
Athena-Vertica connector throws `GENERIC_USER_ERROR` if the query returns value of type `TIME`

**To Reproduce**
1. Go to Athena console.
2. Run query on Vertica that returns value of type `TIME`.
3. Athena console displays error message.

**Expected behavior**
No error should be thrown.

**Screenshots / Exceptions / Errors**

Here is a query that I ran.

```
SELECT 
transaction_time
FROM store.store_sales_fact;
```

This query uses tables in the sample database VMart that ships with Vertica Community Edition.

For details on the schema see [here](https://vertica.com/docs/10.0.x/HTML/Content/Authoring/GettingStartedGuide/Appendix/Tables/storeSchemaTables/store_sales_fact.htm).

Here is the error that I got.

```
Your query has the following error(s):

GENERIC_USER_ERROR: Encountered an
exception[java.lang.RuntimeException] from your
LambdaFunction[arn:aws:lambda:us-west-2:861469877924:function:vertica_feb_1]
executed in context[retrieving meta-data] with message[Error in
executing queries on Vertica: [Vertica][VJDBC](5861) ERROR: Error
calling getPerInstanceResources() in User Function ParquetExport at
[/data/qb_workspaces/jenkins2/ReleaseBuilds/Hammermill/REL-10_0_1-x_hammermill/build/udx/supported/ParquetExport/ParquetExport.cpp:426],
error code: 0, message: Data Type Time is not supported]

This query ran against the "online_sales" database, unless qualified
by the query. Please post the error message on our forum or contact
customer support with Query Id: 22ed6b2d-d2f8-4a60-823a-0976b040dfac.
```

**Connector Details (please complete the following information):**
 - Version: 2021.35.10 
 - Name: vertica
 - Athena Query IDs: N/A

**Additional context**
Selecting other columns on the table do not throw this error.

**Comment by avirtuos** [comment]
Time is not presently a supported data type in the Vertica connector. You can find the complete list of supported types here: https://github.com/awslabs/aws-athena-query-federation/tree/master/athena-vertica#vertica-data-types-supported

**Comment by asimjalis** [comment]
The `EXPORT TO PARQUET` query works if `TIME` is cast to `VARCHAR`.

```sql
EXPORT TO PARQUET(
  directory = 's3://asimj-vertica-export/tmp-2021-02-22-1',
  Compression='snappy', fileSizeMB=16, rowGroupSizeMB=16) AS
SELECT CAST(transaction_time AS VARCHAR) AS transaction_time 
FROM "store"."store_sales_fact";
```

```
 Rows Exported
---------------
       5000000
```

Instead of `SELECT transaction_time FROM "store"."store_sales_fact"` the SQL should be `SELECT CAST(transaction_time AS VARCHAR) AS transaction_time FROM "store"."store_sales_fact"`

The Athena-Vertica connector handles this for `TIMESTAMP` and `TIMESTAMPZ` (see code below). The same code should handle `TIME` as well. The code is located here.

https://github.com/awslabs/aws-athena-query-federation/blob/6c928545080e54f2f2ce769990dae3abade99e96/athena-vertica/src/main/java/com/amazonaws/connectors/athena/vertica/query/VerticaExportQueryBuilder.java#L97
