### ISSUE TITLE
[FEATURE] Document Lambda Protocol

### ISSUE THREAD

**Issue by joshuanapoli** [awslabs/aws-athena-query-federation#363]
Could you please document the Lambda function interface and spill protocol?

[The Athena User Guide mentions:](https://docs.aws.amazon.com/athena/latest/ug/connect-to-a-data-source.html)
> Connectors use Apache Arrow as the format for returning data requested in a query, which enables connectors to be implemented in languages such as C, C++, Java, Python, and Rust.

Only a Java SDK is provided here. Protocol documentation would help realize the multi-language support implied by the documentation.

**Comment by avirtuos** [comment]
The protocol is documented in the form of example request/replies and unit tests that validate the associated serialization.  You can find it at the below link. This isn't as good as human readable documentation but it is example driven which should help enable this for other languages if that is your goal.

https://github.com/awslabs/aws-athena-query-federation/tree/master/athena-federation-sdk/src/test/resources/serde
