### ISSUE TITLE
[BUG] maybe remove airport codes for region names in the ReadMe.

### ISSUE THREAD

**Issue by davetbo-amzn** [awslabs/aws-athena-query-federation#366]
When you mention which regions are supported by this plugin you should not use internal terminology. As far as I know we don't use IAD, PDX, etc in customer-facing messaging.

**Comment by avirtuos** [comment]
Do you have any examples where you saw these identifiers? We will scrub them.

**Comment by avirtuos** [comment]
Oof, right on the front page. I've raised a PR to remove those. Any others that you saw? I'll search the repo when I get to a computer. I'm on mobile presently.

**Comment by davetbo-amzn** [comment]
That was the only one I saw but I didn’t search extensively. I just started the tutorial. I’ll let you know if I find more.

Best,
Dave

**Comment by burhan94** [comment]
All of the ReadMe's have them (oops, my bad). I'll cut a PR later today to update & remove.

**Comment by avirtuos** [comment]
@burhan94 did we take care of this?

**Comment by burhan94** [comment]
PR sent: https://github.com/awslabs/aws-athena-query-federation/pull/370

**Comment by burhan94** [comment]
merged. closing ticket out
