### ISSUE TITLE
[BUG] Query with range in sort keys and identifying partition key with connector dynamoDbConnector

### ISSUE THREAD

**Issue by laurihak** [awslabs/aws-athena-query-federation#373]
**Describe the bug**
I have played around to query against index and it seems to be working fine. Range and another where clause to key expression attribute does not work.

Dynamodb table:
partition key:  id
sort key: datetime

So i Query the table as : 
SELECT *
FROM <aws.lambda.dynamo.connector.table>
WHERE partitionkey = 'id' AND sortKey BETWEEN 'dateFrom' AND 'dateTo'

Having the error: 

When deleting the the primary key from query it works fine.

WHERE sortKey BETWEEN 'dateFrom' AND 'dateTo'

**To Reproduce**
1. Have table with primary and sortKey
2. Query the table with primary key = 'yourPrimaryKey' and sortKey > 'from' AND  sortKey < 'to'.
Optional syntax: sortKey BETWEEN 'from' AND 'to'
3. Send the query from Athena

**Expected behavior**
Expected to query range with sort key.

I think the problem might be related to that dynamodb key-condition-expression should use BETWEEN if the original query includes the same key twice.

**Screenshots / Exceptions / Errors**
Your query has the following error(s):

GENERIC_USER_ERROR: Encountered an exception[com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException] from your LambdaFunction[arn:aws:lambda:eu-west-1:#######:function:dynamolambda] executed in context[S3SpillLocation{bucket='########', key='athena-spill/########f', directory=true}] with message[KeyConditionExpressions must only contain one condition per key (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: JL285EOAIDF2V6N92FRA1TRS0NVV4KQNSO5AEMVJF66Q9ASUAAJG; Proxy: null)]

This query ran against the "default" database, unless qualified by the query. Please post the error message on our forum or contact customer support with Query Id: 9027cae2-72d6-4029-bb50-612161c71e7c.

**Connector Details (please complete the following information):**
 - Version: 2021.6.1
 - Name: DynamoDb, AthenaDynamoDBConnector
 - Athena Query IDs 9027cae2-72d6-4029-bb50-612161c71e7c

**Comment by miettal** [comment]
I face same issue.

last year grafana Athena datasouce was released, and I tried to connect dynamodb and grafana via athena.
but this connector is not support for filtering range key by using BETWEEN.
https://grafana.com/grafana/plugins/grafana-athena-datasource/

This function is critical for visualization of time series data.

**Comment by henrymai** [comment]
Latest version of the DDB Connector (v2022.39.1) is out and resolves this issue.
