### ISSUE TITLE
[QUESTION] Should UDF queries work with "engine version 2" ?

### ISSUE THREAD

**Issue by johnchapin** [awslabs/aws-athena-query-federation#386]
Our previously working UDF queries began failing a couple of days ago. I'm not sure what engine version our `AmazonAthenaPreviewFunctionality` work group was using before - I would have guessed it was version 2, but I'm not 100% sure.

So the question is, should UDF queries work with "engine version 2" or just "engine version 1" ? If so, I wasn't able to find any documentation mentioning any engine version requirement for UDFs (especially not a different requirement from Athena Query Federation in general, which the docs say [requires "engine version 2"](https://docs.aws.amazon.com/athena/latest/ug/connect-to-a-data-source.html)).

Here's a quick reproduction of my findings:

### Engine version 1, UDF queries execute successfully

```
# Confirm work group is using "engine version 1"
$ aws athena get-work-group \
   --region us-east-1 \
   --work-group AmazonAthenaPreviewFunctionality \
   --query WorkGroup.Configuration.EngineVersion

{
    "SelectedEngineVersion": "Athena engine version 1",
    "EffectiveEngineVersion": "Athena engine version 1"
}

# Submit UDF query successfully
$ aws athena start-query-execution \
   --region us-east-1 \
   --work-group AmazonAthenaPreviewFunctionality \
   --query-string "USING FUNCTION compress(col1 VARCHAR) RETURNS VARCHAR TYPE LAMBDA_INVOKE WITH (lambda_name = 'test-udf') SELECT compress('StringToBeCompressed');"

{
    "QueryExecutionId": "9ad7ff19-247d-4b36-9ef5-aa0899fe5255"
}

# Get successful query results
$ aws athena get-query-results \
   --region us-east-1 \
   --query-execution-id 9ad7ff19-247d-4b36-9ef5-aa0899fe5255 \
   --query 'ResultSet.Rows[].Data' --output text

_col0
eJwLLinKzEsPyXdKdc7PLShKLS5OTQEAUrEH9w==
```

### Engine version 2, UDF queries fail

```
# Confirm work group is using "engine version 2"
$ aws athena get-work-group \
   --region us-east-1 \
   --work-group AmazonAthenaPreviewFunctionality \
   --query WorkGroup.Configuration.EngineVersion

{
    "SelectedEngineVersion": "Athena engine version 2",
    "EffectiveEngineVersion": "Athena engine version 2"
}

# Submit UDF query, receive error response
$ aws athena start-query-execution \
   --region us-east-1 \
   --work-group AmazonAthenaPreviewFunctionality \
   --query-string "USING FUNCTION compress(col1 VARCHAR) RETURNS VARCHAR TYPE LAMBDA_INVOKE WITH (lambda_name = 'test-udf') SELECT compress('StringToBeCompressed');"

An error occurred (InvalidRequestException) when calling the StartQueryExecution operation: line 1:7: mismatched input 'FUNCTION'. Expecting: 'EXTERNAL'
```

**Comment by burhan94** [comment]
Hi, 

So UDF's are still in preview, and as a part of the GA release, we updated the syntax. The syntax is a breaking change for customers using the AmazonAthenaPreviewFunctionality workgroup with the V2 engine. The immediate workaround is to switch the engine version to V1. The AmazonAthenaPreviewFunctionality workgroup is agnostic to engine versions, other than which version of the parser is used. We only updated the V2 parser with the new changes. 

We did send out notifications about two weeks ago via Personal Health Dashboard and emails regarding this change.

**Comment by johnchapin** [comment]
> Hi,
> 
> So UDF's are still in preview, and as a part of the GA release, we updated the syntax. The syntax is a breaking change for customers using the AmazonAthenaPreviewFunctionality workgroup with the V2 engine. The immediate workaround is to switch the engine version to V1. The AmazonAthenaPreviewFunctionality workgroup is agnostic to engine versions, other than which version of the parser is used. We only updated the V2 parser with the new changes. We will also be deprecating the AmazonAthenaPreviewFunctionality workgroup within the next month since all of the preview features will be GA by then.
> 
> We did send out notifications about two weeks ago via Personal Health Dashboard and emails regarding this change.

Thank you for that explanation. I went back and did find the notification in our PHD - clearly we just missed it.

Looking forward to UDFs in GA!
