### ISSUE TITLE
[BUG] "SELECT *" throws exception with connector DynamoDB Connector

### ISSUE THREAD

**Issue by beaksandclaws** [awslabs/aws-athena-query-federation#388]
**Describe the bug**
I'm using the DynamoDBConnector with Athena and Glue to fetch data from a DynamoDB table. The Glue definition of the table contains 233 columns. When I run this query in Athena: 
```
SELECT * FROM "dynamo-db-catalog"."default"."evt_development" WHERE contains(dataset_ids, 513);
```

I receive the following error:
```
GENERIC_USER_ERROR: Encountered an exception[com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException] from your LambdaFunction[arn:aws:lambda:us-west-2:531949516270:function:dynamodb] executed in context[S3SpillLocation{bucket='serves-athena-results', key='athena-spill/1ba2f449-8acf-4f6d-bd4b-23cacdab2005/9d7d7bac-ade7-466e-a29b-1635cc291939', directory=true}] with message[Invalid ProjectionExpression: Expression size has exceeded the maximum allowed size; (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: K2ELVA23GHPJ343NV3N2ETIFUFVV4KQNSO5AEMVJF66Q9ASUAAJG; Proxy: null)]
```

**To Reproduce**
1. Create a dynamo table called `evt_development`
2. Set up the DynamoDBConnector and call it "dynamo-db-catalog".
2. Create a Glue table definition for `evt_development` with 233 columns.
3. Run the query: `SELECT * FROM "dynamo-db-catalog"."default"."evt_development"`

**Expected behavior**
Results are returned.

**Screenshots / Exceptions / Errors**
Receive the error:
```
GENERIC_USER_ERROR: Encountered an exception[com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException] from your LambdaFunction[arn:aws:lambda:us-west-2:531949516270:function:dynamodb] executed in context[S3SpillLocation{bucket='serves-athena-results', key='athena-spill/1ba2f449-8acf-4f6d-bd4b-23cacdab2005/9d7d7bac-ade7-466e-a29b-1635cc291939', directory=true}] with message[Invalid ProjectionExpression: Expression size has exceeded the maximum allowed size; (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: K2ELVA23GHPJ343NV3N2ETIFUFVV4KQNSO5AEMVJF66Q9ASUAAJG; Proxy: null)]
```

**Connector Details (please complete the following information):**
 - Version: 2021.6.1
 - Name serverlessrepo-AthenaDynamoDBConnector
 - Athena Query IDs `1ba2f449-8acf-4f6d-bd4b-23cacdab2005.`

**Comment by henrymai** [comment]
@beaksandclaws 

This problem will be solved by this new feature (set to always) from release 2022.30.2:
https://github.com/awslabs/aws-athena-query-federation/tree/master/athena-dynamodb#disable_projection_and_casing
