### ISSUE TITLE
[BUG] Got errors if database name(eg: 'PRODUCTS') is in caps with jdbc connector

### ISSUE THREAD

**Issue by SathishGajendran** [awslabs/aws-athena-query-federation#396]
**Describe the bug**
An error occurred when quering the data from the table, if the database name is in capital letters.eg: 'PRODUCTS'

**To Reproduce**
1. create a database with name in capital letters. eg: 'PRODUCTS'
2. connect to this database using custom connector in Athena.
3. try to query the records in the table.

**Expected behavior**
It should treat database name as case sensitive 

**Connector Details :**
 - Version:  2021.14.01
 - Name: jdbc
 - Athena Query IDs [if applicable]

**Comment by burhan94** [comment]
Hi, 

I'll add this as a feature request. At the moment, the jdbc connector doesn't support case sensitivity, and neither does Athena. We have it in our roadmap to add this feature in the future.
