### ISSUE TITLE
[BUG] MongoQueryException with connector athena-docdb

### ISSUE THREAD

**Issue by yus4work** [awslabs/aws-athena-query-federation#397]
**Describe the bug**
Incompatibility in MongoDB 4.2. As we know the DocumentDB should support MongoDB 4.2.
I found this code which is not compatible with MongoDB 4.2.
Look at the file SchemaUtils.java at line 79.
_try (MongoCursor docs = db.getCollection(table.getTableName()).find().batchSize(numObjToSample)**.maxScan(numObjToSample)**.limit(numObjToSample).iterator())_

According to the documentation of MongoDB the maxScan function is removed from the release 4.2 check this link https://docs.mongodb.com/v4.2/release-notes/4.2-compatibility/#remove-maxscan
Removeing the maxScan function from the line indicated. it works without throwing any exception any more.
the solution:
_try (MongoCursor docs = db.getCollection(table.getTableName()).find().batchSize(numObjToSample).limit(numObjToSample).iterator())_

**To Reproduce**
1. Go to Athena 
2. Click on Select data source
3. Select any database
3. Go to New query 
4. Do a simple select query
4. See an error

**Screenshots / Exceptions / Errors**
![image](https://user-images.githubusercontent.com/83000021/115673099-8a6a5b00-a34c-11eb-89e8-255414b4093f.png)

**Connector Details (please complete the following information):**
 - Version: 2021.14.1
 - Name athena-docdb

**Comment by rafiron** [comment]
@yus4work can you tell me how you are able to connect to MongoDB. I'm using Atlas MongoDB cluster and for adding the data source by creating a Glue Data catalog but it simply doesn't work!! I've tried creating a MongoDB connection but it doesn't work with any connection string.

I've tried several possible combinations of connection string as input but every time I get this issue every time:
```Check that your connection definition references your Mongo database with correct URL syntax, username, and password.```

**Comment by yus4work** [comment]
> @yus4work can you tell me how you are able to connect to MongoDB. I'm using Atlas MongoDB cluster and for adding the data source by creating a Glue Data catalog but it simply doesn't work!! I've tried creating a MongoDB connection but it doesn't work with any connection string.
> 
> I've tried several possible combinations of connection string as input but every time I get this issue every time:
> `Check that your connection definition references your Mongo database with correct URL syntax, username, and password.`

I used aws-athena-query-federation/athena-docdb 

https://github.com/awslabs/aws-athena-query-federation/blob/master/athena-docdb/README.md

my connection string like this format: mongodb://<username>:<password>@xxxx-shard-00-00.xxxxx.mongodb.net:27017,xxxx-shard-00-01.xxxxx.mongodb.net:27017,xxxx-shard-00-02.xxxxx.mongodb.net:27017/?ssl=true&replicaSet=atlas-xxxxxx-shard-0&authSource=admin&retryWrites=true&w=majority

**Comment by rafiron** [comment]
@yus4work thanks for this. I was getting a problem with the connection string that I was using with the federated query. Will give this connection string a try. 

Can you also answer these things :

- I tried with a mongo setup on EC2 as well with version 4.4 but wasn't able to connect it. Wanted to know what version of mongo are you using, cause AWS support says that they officially support up to version 4.0
- I was trying to set up an AWS Glue crawler for the MongoDb atlas cluster but when I create the connection in AWS glue and test the connection it simply says that there is an issue with the connection string. Have tried multiple things but nothing works. The GitHub link that you shared also mentions that it's better to have a Glue Data Catalog for getting the documents' metadata. Have you set up Glue crawlers on your Atlas cluster and if so, can you please help me with how you did that.

**Comment by rafiron** [comment]
@yus4work I tried with the connection string you mentioned by updating the lambda's env variable but I'm getting this error

```
Timed out after 30000 ms while waiting for a server that matches com.mongodb.client.internal.MongoClientDelegate$1@396a51ab. Client view of cluster state is {type=REPLICA_SET, servers=[{address=xxxx-shard-00-02.xxxxx.mongodb.net:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: connect timed out}}, {address=xxxx-shard-00-00.xxxxx.mongodb.net:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: connect timed out}}, {address=xxxx-shard-00-01.xxxxx.mongodb.net:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: connect timed out}}]: com.mongodb.MongoTimeoutException
com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches com.mongodb.client.internal.MongoClientDelegate$1@396a51ab. Client view of cluster state is {type=REPLICA_SET, servers=[{address=xxxx-shard-00-02.xxxxx.mongodb.net:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: connect timed out}}, {address=xxxx-shard-00-00.xxxxx.mongodb.net:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: connect timed out}}, {address=xxxx-shard-00-01.xxxxx.mongodb.net:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: connect timed out}}]
	at com.mongodb.internal.connection.BaseCluster.createTimeoutException(BaseCluster.java:404)
	at com.mongodb.internal.connection.BaseCluster.selectServer(BaseCluster.java:123)
	at com.mongodb.internal.connection.AbstractMultiServerCluster.selectServer(AbstractMultiServerCluster.java:52)
	at com.mongodb.client.internal.MongoClientDelegate.getConnectedClusterDescription(MongoClientDelegate.java:138)
	at com.mongodb.client.internal.MongoClientDelegate.createClientSession(MongoClientDelegate.java:94)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.getClientSession(MongoClientDelegate.java:249)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:172)
	at com.mongodb.client.internal.MongoIterableImpl.execute(MongoIterableImpl.java:132)
	at com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:86)
	at com.mongodb.client.internal.MappingIterable.iterator(MappingIterable.java:39)
	at com.amazonaws.athena.connectors.docdb.DocDBMetadataHandler.doListSchemaNames(DocDBMetadataHandler.java:146)
	at com.amazonaws.athena.connector.lambda.handlers.MetadataHandler.doHandleRequest(MetadataHandler.java:236)
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:132)
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:100)
```

**Comment by yus4work** [comment]
> @yus4work I tried with the connection string you mentioned by updating the lambda's env variable but I'm getting this error
> 
> ```
> Timed out after 30000 ms while waiting for a server that matches com.mongodb.client.internal.MongoClientDelegate$1@396a51ab. Client view of cluster state is {type=REPLICA_SET, servers=[{address=xxxx-shard-00-02.xxxxx.mongodb.net:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: connect timed out}}, {address=xxxx-shard-00-00.xxxxx.mongodb.net:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: connect timed out}}, {address=xxxx-shard-00-01.xxxxx.mongodb.net:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: connect timed out}}]: com.mongodb.MongoTimeoutException
> com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches com.mongodb.client.internal.MongoClientDelegate$1@396a51ab. Client view of cluster state is {type=REPLICA_SET, servers=[{address=xxxx-shard-00-02.xxxxx.mongodb.net:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: connect timed out}}, {address=xxxx-shard-00-00.xxxxx.mongodb.net:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: connect timed out}}, {address=xxxx-shard-00-01.xxxxx.mongodb.net:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: connect timed out}}]
> 	at com.mongodb.internal.connection.BaseCluster.createTimeoutException(BaseCluster.java:404)
> 	at com.mongodb.internal.connection.BaseCluster.selectServer(BaseCluster.java:123)
> 	at com.mongodb.internal.connection.AbstractMultiServerCluster.selectServer(AbstractMultiServerCluster.java:52)
> 	at com.mongodb.client.internal.MongoClientDelegate.getConnectedClusterDescription(MongoClientDelegate.java:138)
> 	at com.mongodb.client.internal.MongoClientDelegate.createClientSession(MongoClientDelegate.java:94)
> 	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.getClientSession(MongoClientDelegate.java:249)
> 	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:172)
> 	at com.mongodb.client.internal.MongoIterableImpl.execute(MongoIterableImpl.java:132)
> 	at com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:86)
> 	at com.mongodb.client.internal.MappingIterable.iterator(MappingIterable.java:39)
> 	at com.amazonaws.athena.connectors.docdb.DocDBMetadataHandler.doListSchemaNames(DocDBMetadataHandler.java:146)
> 	at com.amazonaws.athena.connector.lambda.handlers.MetadataHandler.doHandleRequest(MetadataHandler.java:236)
> 	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:132)
> 	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:100)
> ```

First, you have to do the change that I mentioned in the beginning. 
step. 
1. clone the repo 
2. open the file SchemaUtils.java 
3. goto line 79
4. remove the maxScan(numObjToSample): (try (MongoCursor docs = db.getCollection(table.getTableName()).find().batchSize(numObjToSample)
.**maxScan**(numObjToSample).limit(numObjToSample).iterator()))
5. publish the app in your amazon account using their script ../tools/publish.sh serverless-app-repo-mna-prod athena-docdb ${AWS_REGION} 
6. install the app using the template.

this should work with MongoDB Atlas 4.4 tested and it works.

**Comment by avirtuos** [comment]
Thanks for the detailed explanation, the fix is in the process of merging.
