### ISSUE TITLE
[FEATURE] Use Set instead of List for partitionCols in GetSplitsRequest

### ISSUE THREAD

**Issue by sethtdenney** [awslabs/aws-athena-query-federation#4]
Currently, [GetSplitsRequest](https://github.com/awslabs/aws-athena-query-federation/blob/master/athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/metadata/GetSplitsRequest.java#L55) requires a List\<String\> partitionCols argument, but [GetTableLayoutRequest](https://github.com/awslabs/aws-athena-query-federation/blob/master/athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/metadata/GetTableLayoutRequest.java#L53) requires a Set\<String\> partitionCols argument, and [GetTableResponse](https://github.com/awslabs/aws-athena-query-federation/blob/master/athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/metadata/GetTableResponse.java#L72) returns a Set\<String\> of partition columns.

This task is to change GetSplitsRequest to require a Set\<String\> instead of List\<String\> to match the convention used elsewhere in the SDK.

**Comment by hackett123** [comment]
This will be addressed in the near future as we are moving to Protobuf for our request/response objects. Protobuf has no notion of a "set" type, instead it just has "repeated" fields. The generated Java classes in the SDK will then all have the same type (List). So this is something we can close out.
