### ISSUE TITLE
[QUESTION] Generating large of amounts of splits in parallel? 

### ISSUE THREAD

**Issue by ahuwaa** [awslabs/aws-athena-query-federation#404]
I have a question that I don't think is related to a bug or feature request. 

Is there a recommended way to generate large amounts of splits in parallel? From my understanding the `getSplits` method provides pagination support (continuationToken) but this is for a collection of partitions. Generating splits from one partition may require its own pagination. With the goal of trying to generate splits in a performant manner and avoiding hitting any "body too large" (assuming this is Lambda payload size issue from too many splits) errors, this could become complex trying to track pagination for multiple partitions within the same `getSplits` invocation. 

Any suggestions appreciated!

**Comment by ahuwaa** [comment]
That makes sense. We do have a current implementation doing split pagination over a batch of partitions, but this is still sequential for each batch. One partition can potentially generate a very large amount of splits so parsing in this sequential manner for one batch can still be non-performant. Would you be able to share how partitions are split (max batch size perhaps)? Or would there be a way for us to control the partition batch size? E.g. we could tweak partition batch size to 1

**Comment by avirtuos** [comment]
You can't influence the batch size today but you can produce more (smaller)
partitions. One way to do this is to add another 'virtual' dimension to
your partitions. For example you can arbitrarily divide every partition
into 100 partitions (0-99). That would effectively reduce the splits
generated per partition by a factor of 100. I'll see if I can dig up more
examples of this.

**Comment by avirtuos** [comment]
closing since its been a while since further communication on this topic. please reopen if you have additional questions.
