### ISSUE TITLE
[BUG] lambda can't connect to secret manager with connector JDBC

### ISSUE THREAD

**Issue by k-hasan-19** [awslabs/aws-athena-query-federation#406]
After using the JDBC connector's secret manager settings, the lambda can't connect to secretsmanager.us-west-2.amazonaws.com . My lambda is in default vpc.

![image](https://user-images.githubusercontent.com/6383136/117187215-83882180-adfd-11eb-820a-c2950020cb1c.png)

1. Deploy the JDBC connector from Serverless app repo
2. Use the secret manager settings for jdbc connection string during deployment
3. run the query in athena like `SELECT * FROM "lambda:mysql".sakila.film_text`

**Expected behavior**
It should return query result from RDS

**Screenshots / Exceptions / Errors**
![image](https://user-images.githubusercontent.com/6383136/117186944-33a95a80-adfd-11eb-82eb-c2907ef78ea6.png)

**Connector Details (please complete the following information):**
 - serverlessrepo:semanticVersion | 2021.18.1
 - JDBC
 - Athena Query IDs [if applicable]

**Comment by burhan94** [comment]
hi @k-hasan-19 

So for these types of errors, its typically due to the vpc access policy. You'll have to attach a VPC endpoint for secrets manager so that your vpc can communicate with secretsmanager

https://docs.aws.amazon.com/secretsmanager/latest/userguide/vpc-endpoint-overview.html

**Comment by k-hasan-19** [comment]
SOLVED!

Had to create a VPC interface endpoint for secrets manager and attach the SG from deployed lambda to the vpc endpint SG's inbound https rule.

Thanks @burhan94
