### ISSUE TITLE
[BUG] Random tuple error with DynamoDBConnector

### ISSUE THREAD

**Issue by houmark** [awslabs/aws-athena-query-federation#407]
**Describe the bug**
Recently, we are seeing random errors when running a query that has not changed for a long period. This error only happens sometimes (half the time more or less?) but it also succeeds sometimes.

Error message:

Your query has the following errors:GENERIC_INTERNAL_ERROR: Enforced tuple domain cannot be determined. Connector returned an unenforced TupleDomain that contains columns not in predicate.

This query ran against the 'default' database, unless qualified by the query. Please post the error message on our forum or contact customer support with query id.

Query ID (failed): c7ce8394-2971-41a7-a246-d6f09b5e8a89
Query ID (same query, succeeded): c34d8811-f1f7-4f32-a457-259288b41268

**Expected behavior**
That the query will succeed.

**Connector Details (please complete the following information):**
* Athena engine version 2
* 2021.6.1

I'm not exactly sure how to update the connector at this time (cannot really find it anywhere in any console, let alone an upgrade option), and I'm also not sure it's safe to do.

If something breaks, can I revert back to this version?

In any case, this version has worked without issues and it's only within the last few weeks we've seen this one query failing but intermittent. I've not noticed other queries fail (20+ other queries run around the same time this one runs).

**Comment by vassbence** [comment]
Same here, have not touched anything in weeks and a simple federated query fails (every time for me) with the error above.

I'm using Athena v2 w/ federated query via the official lambda to dynamodb.

**Comment by burhan94** [comment]
Hi Folks, we've identified a bug in the last engine release, and we are in the process of deploying a fix. Should be deployed to all major regions by EOD.

**Comment by houmark** [comment]
Just to confirm, this does not require us to update the serverless Java app, correct? This is a cloud fix?

**Comment by aiasmartakis** [comment]
Hi, we're in the Oregon (us-west-2) region and still have issues, did the update not get applied last night?

**Comment by fmcastro** [comment]
Same here us-east-1

> Hi, we're in the Oregon (us-west-2) region and still have issues, did the update not get applied last night?

**Comment by houmark** [comment]
We are also still seeing it in us-east-1.

**Comment by burhan94** [comment]
Hello again, 

sorry for the churn, the deployment was delayed yesterday due to an unrelated issue. We've started the deployment this morning and it is currenlty in progress. I will update here once it is done.

**Comment by houmark** [comment]
@burhan94 Is this deployment still ongoing? We are still seeing errors on our end.

**Comment by aiasmartakis** [comment]
Hi, what is the status on this? Can whatever caused this, a few days ago, be rolled back while you figure out a fix? is there a workaround that we should try? when is the fix expected to roll out?
We have reports that rely on a working Athena with federation.
Thanks!

**Comment by burhan94** [comment]
Hi Folks, 

We've been working around the clock to fix this issue. After a long night of manually reverting everything, we've finally finished with the majority of regions, and the rest (handful) of regions will be done in the next few hours. Unfortunately there were multiple non-related issues that were blocking us and thats why it took so long. Nonetheless, we will be doing a full deep dive on our side to figure out how this got missed, what we can do to make sure that errors like this are caught much earlier, and take a deeper look at our deployment system. Thank you for being patient, and for supporting this initiative. 

Thanks, 
Burhan & the Athena Query Federation team.

**Comment by burhan94** [comment]
all of the regions mentioned in this ticket have been deployed to. 

(us-east-1, us-west-2, eu-central-1)

**Comment by houmark** [comment]
I can confirm we have not seen errors for at least 48 hours.

**Comment by burhan94** [comment]
thanks for confirming. after checking internally, there are no more errors of this type. Resolving ticket.
