### ISSUE TITLE
[BUG] Pagination token is not handled properly with connector athena-timestream

### ISSUE THREAD

**Issue by ningqian-dev** [awslabs/aws-athena-query-federation#410]
**Describe the bug**
Pagination token is not handled properly in athena-timestream connector which leads to empty query result when the dataset is large

**To Reproduce**
1. Create a TimeStream table and ingest 500MB data
2. Setup the TimeStream Athena Connector
3. Query from Athena Connector with an expensive query: "Select * from your_table"
4. Empty result returned

**Expected behavior**
All the data in the TimeStream should be returned properly

**Screenshots / Exceptions / Errors**
If applicable, add screenshots, exception stack traces, or error messages to help explain your problem.  Stack traces for exceptions thrown by your Connector can be found in CloudWatch Logs under the 'aws/lambda/<Lambda_function_name>' log group.

**Connector Details (please complete the following information):**
 - Version: [2021.18.1]
 - Name [timestream]
 - Athena Query IDs [114b28d1-70ce-49d3-a22c-e90611890e2b] us-east-1 region

**Additional context**
I have made a fix locally and tested. The issue seems related to the behavior that TimeStream can return empty result with a nextToken when the query is in progress and will take a long period of time to complete.

**Comment by burhan94** [comment]
hi ningqian, 

thank you for reporting this and submitting the PR. I will take a look in the AM

**Comment by ningqian-dev** [comment]
Hey,

Updates here?

Thanks,
Qian

From: burhan94 ***@***.***>
Reply-To: awslabs/aws-athena-query-federation ***@***.***>
Date: Thursday, May 13, 2021 at 8:02 PM
To: awslabs/aws-athena-query-federation ***@***.***>
Cc: Qian Ning ***@***.***>, Author ***@***.***>
Subject: Re: [awslabs/aws-athena-query-federation] [BUG] Pagination token is not handled properly with connector athena-timestream (#410)


hi ningqian,

thank you for reporting this and submitting the PR. I will take a look in the AM

**Comment by avirtuos** [comment]
An earlier comment from @burhan94 suggests you raised a PR but I couldn't find a PR from you. Is this still an issue? if so, are you sure the table you are querying had data in it? I wasn't able to reproduce.

**Comment by ningqian-dev** [comment]
Hey,

I have raised the PR and it has been approved.

Thanks

**Comment by avirtuos** [comment]
ah i see. it. will merge shortly.
