### ISSUE TITLE
[FEATURE] Better error msg when S3 path is not in the expected format. 

### ISSUE THREAD

**Issue by MishaAW** [awslabs/aws-athena-query-federation#415]
**Is your feature request related to a problem? If yes, please describe.**
When I put "bucket-name/" for spill bucket, Athena gives: "You do NOT own the spill bucket with the name" error. This made me go debug IAM and such. Right way was to put "bucket-name" without the / at the end.

**Describe the solution you'd like**
Error to say something like: S3 resource does not exit, if the path is wrong. Just not imply it is a permissions issue.

**Describe alternatives you've considered**
None.

**Additional context**
None

Thank you very much for having this tool. Looks awesome!

**Comment by nauy2697** [comment]
Hi,

Thank you for reaching out on the reported issue. We have made an update to address the error message.

Thanks!
