### ISSUE TITLE
[QUESTION] Date fields and performance optimizations

### ISSUE THREAD

**Issue by ryanaston** [awslabs/aws-athena-query-federation#416]
I have a question that I don't think is related to a bug or feature request. 

My Glue schema has some Date fields defined.  If I try to query against these date fields using date types with the Athena DDB Connector no rows are found.  I have to cast the date fields to strings and query against them that way to get what I expect.  This may be a known limitation since DDB does not natively support date types, but I did notice my Kinesis-streamed Parquet files can query date types without issue (using the same Glue schema).

Also, my Parquet queries are significantly faster than my DDB connector queries.  Is there anything that can be done, either in the configuration of the Glue schema or elsewhere, to improve the performance of my DDB queries?

I'm using version 2021.18.1 of the connector, by the way.

Really appreciate this package.  It's a big help for my use case!

**Comment by avirtuos** [comment]
The DynamoDB connector presently supports only a finite set of date types today [DynamoDB Connector Types](https://github.com/awslabs/aws-athena-query-federation/blob/9954cf40cc93357376857f7a8284e6dfe0a3f926/athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/util/DDBTypeUtils.java#L282). When it can't find a match for supported types it will coerce to string.
