### ISSUE TITLE
[QUESTION] Out of Memory Exception when Writing Records to Athena

### ISSUE THREAD

**Issue by teddyf** [awslabs/aws-athena-query-federation#420]
When running athena queries on records with larger fields (in the scale of mb) we encounter OOM errors: `Encountered an exception[org.apache.arrow.memory.OutOfMemoryException] from your LambdaFunction[arn:aws:lambda:us-east-1:************:function:ourRecordHandlerFunction] executed in context[S3SpillLocation{bucket='spill-bucket-name, key='athena-federation-spill/pathTo/location', directory=true}] with message[Unable to allocate buffer of size 16777216 due to memory limit. Current allocation: 2132725996]`

We attempted to remedy this by writing splits with fewer records; but even with a size of 1 we are still encountering this error. It seems that the blockSpiller which is used in the recordHandler is passed to the function in the federatedSdk. Is there some configuration we can set to allocate more memory to blocks or is there some way we can ensure that the blockSpiller only writes to blocks that have enough room?  Thanks.

**Comment by avirtuos** [comment]
Which connector are you using? This error leads me to believe that something is using Apache Arrow buffers and not properly freeing them as the Federation SDK would rarely have more than ~32MB of buffer active at a time and your Lambda seems to have nearly 2GB of buffer active.

**Comment by teddyf** [comment]
Our connector is an implementation of the sdk handlers. I should add that this occurs in the record handler when we attempt to write rows with the blockspiller for larger jobs (the job that is failing is querying over an exabyte worth of logs, uncompressed).

**Comment by avirtuos** [comment]
This sounds like you are writing a single row (or possibly column) that is HUGE. Or you may be leaking apache arrow memory in your custom connector. Is it possible for you to share some of the source so I can take a look? We can continue this chat on slack since you seem to be internal.

**Comment by teddyf** [comment]
Will continue on internal channels. Thanks
