### ISSUE TITLE
[BUG] error querying empty index with a field of "object"/"nested" data type with connector elasticsearch

### ISSUE THREAD

**Issue by madhavvishnubhatta** [awslabs/aws-athena-query-federation#422]
**Describe the bug**
When I create an empty index with a field of "object"/"nested" data type, and query it from Athena I get an error that says "Detected unsupported type[Null / NULL for column[col1]]"

**To Reproduce**
1. Create an index in Elasticsearch using the Kibana dev tools interface with the following command
```
PUT /testindex
{
 "mappings": {
   "properties": {
    "col1": {"type": "object"}
  }
 }
}
```
2. Go to Athena and try to query the table using the Athena Elasticsearch connector
```sql
select count(*) from "lambda:elasticsearch"."testdomain"."testindex"
```
3. See error
```
GENERIC_USER_ERROR: Encountered an exception[java.lang.RuntimeException] from your LambdaFunction[elasticsearch] executed in context[retrieving meta-data] with message[Detected unsupported type[Null / NULL for column[col1]]
```

**Expected behavior**
Athena should just say `Zero records returned`

**Screenshots / Exceptions / Errors**
If applicable, add screenshots, exception stack traces, or error messages to help explain your problem.  Stack traces for exceptions thrown by your Connector can be found in CloudWatch Logs under the 'aws/lambda/<Lambda_function_name>' log group.

**Connector Details (please complete the following information):**
 - Version: `2021.18.1`
 - Name - `Elasticsearch`
 - Athena Query IDs - `881570cc-6d9c-419b-8e0e-e760881ed120`

**Additional context**
After I add a document to the index with the following command, it starts working fine. The Athena query returns the count as 1.
```
POST /testindex/_doc
{
"col1": {"e": ["1","2","3"]}
}
```

**Comment by nauy2697** [comment]
Hi, This issue is related to schema inference mechanism. For schema inference, it needs some sample data for it to identity the type. This issue can be resolve by adding supplement Glue metadata to the connector. 

Related ticket https://github.com/awslabs/aws-athena-query-federation/issues/423.

**Comment by nauy2697** [comment]
Hi,

Thanks for reaching out on the issue. Since this issue is specific to the user's data and schemas set up. I will close this ticket. If you have further questions feel free to reach out or reopen.

Thanks
