### ISSUE TITLE
[BUG] Missing Data with connector athena-dynamodb

### ISSUE THREAD

**Issue by dragonH** [awslabs/aws-athena-query-federation#424]
**Describe the bug**

After create the data source in AWS Athena

Some filed was missing in AWS Athena

**To Reproduce**
1. Create data source in AWS athena
2. Just click on "preview table"

**Expected behavior**
All data should be seen in AWS Athena

**Screenshots / Exceptions / Errors**
![image](https://user-images.githubusercontent.com/18332044/120636469-423c6d80-c4a0-11eb-918d-1d75813b9394.png)
![image](https://user-images.githubusercontent.com/18332044/120636822-b24af380-c4a0-11eb-802f-088538093f4a.png)

**Connector Details (please complete the following information):**
 - Version: 2021.18.1
 - Name serverlessrepo-test-dynamodb

**Comment by avirtuos** [comment]
Do all rows in your DDB table have the same schema? Can you try running a describe in Athena to see if this is a schema inference problem? In which case you may be able to use a Glue Table to supply supplimental metadata to ensure Athena discovers all columns and makes them queriable.

**Comment by dragonH** [comment]
hi @avirtuos 

```
Do all rows in your DDB table have the same schema
```

do u mean the data of the column that has issue have the same schema ? i think yes

```
In which case you may be able to use a Glue Table to supply supplimental metadata to ensure Athena discovers all columns and makes them queriable
```

that means

i will need to defined the metadata first to sue the connector ?

**Comment by avirtuos** [comment]
When you say 'i think yes' is there a way to confirm? For example do the columns you are missing show up in a describe table? You can also check the logs of the Lambda function to see what columns it found and even which columns it may have ignored due to type incompatibility.

As for the glue catalog approach, yes. You would define the tables in advance.

**Comment by dragonH** [comment]
```
When you say 'i think yes' is there a way to confirm? For example do the columns you are missing show up in a describe table?
```

yes i've try describe table in athena

and the column was there

maybe i did not describe my issue well

my issue was the `data` in the column are missing

not the column itself

```
You can also check the logs of the Lambda function to see what columns it found and even which columns it may have ignored due to type incompatibility
```

i can't not see something like this in cloudwatch log

do i need to change something like leg level to see this ?

thanks for youe help

**Comment by henrymai** [comment]
From your screenshots, I can see that your `userId` column in DDB has different casing that what is in your Athena output (`userid`), I assume that you must be using a Glue Table for this to occur. If so, please update to the latest version of the connector and use the `disable_projection_and_casing` environment variable (set to `always`) on the DDB Connector.

Here is an example: https://github.com/awslabs/aws-athena-query-federation/issues/772#issuecomment-1235014282

The example also includes the `ATHENA_FEDERATION_SDK_LOG_LEVEL` environment variable set to `debug` to log more information to your DDB Connector Lambda function's logs.

The casing issue is the most likely issue that you were missing data and it has already been fixed. Please reopen this issue if your issue still persists and please attach logs at debug level logging for this issue as well.
