### ISSUE TITLE
[QUESTION] Unable to run publish.sh file

### ISSUE THREAD

**Issue by salihah-rilvan** [awslabs/aws-athena-query-federation#428]
Hi, I am trying to deploy JAR to AWS Lambda but I can't seem to run these steps successfully:
1. ![image](https://user-images.githubusercontent.com/39508749/121119990-445f4d00-c84f-11eb-98db-a50931218b06.png) this is from the user guide
2.  I also can't run 
![image](https://user-images.githubusercontent.com/39508749/121120082-74a6eb80-c84f-11eb-91a6-6471194999d7.png)
this from https://athena-in-action.workshop.aws/50-udf/503-udf-code.html

Here is a snippet of what I see when I run those commands:
![image](https://user-images.githubusercontent.com/39508749/121120163-9acc8b80-c84f-11eb-88f8-23dd9f86a4e9.png)

I am not sure why I can't run publish.sh and what exactly the issue is. Would greatly appreciate if someone could help me out with this!

**Comment by avirtuos** [comment]
are you attempting to run this on Windows? Those errors seem like windows
complaining about line ending characters. The script will only work on
Linux based systems.

**Comment by salihah-rilvan** [comment]
Thanks for the reply! I was actually running it on ubuntu. I cloned the repo again, repeated the steps again and now I am able to run the publish.sh. :)
