### ISSUE TITLE
[BUG] Athena not detecting all the atributes/columns in DynamoDB with connector Athena/DynamoDB

### ISSUE THREAD

**Issue by JackieAnVal** [awslabs/aws-athena-query-federation#431]
**Describe the bug**
I tried to use the new Athena/DynamoDB connector like Jared Donboch does here-> https://dev.to/jdonboch/finally-dynamodb-support-in-aws-quicksight-sort-of-2lbl (bless you man and David Atias who introduced my team to this post 🙏🙏🙏) so I can use that connector with QuickSight as well. 
After my team managed to create this connector, we already had data in our DynamoDB table, we could make our QuickSight analysis correctly until we added more data to the DynamoDB tables. 

Since it is a non-relational database you know each row may or may not have some attributes, we believe the connector only reads the first row of the tables inside DynamoDB to create the schema for Athena, so if the first row doesn't have the complete attributes, those columns won't be in the schema and Athen will never detect them, unless we fill the whole row with default data, so nothing is empty, therefore the all the columns are detected in the schema. But the point of using non-relational databases is lost since we need to declare the attributes every time we add more data to the table. Also, the column where we needed to get the data from can't be empty since it was a string set which made it a little bit more complicated. Our solution for now is set a default value to that string set which we will not be taking into account for the analysis.

**To Reproduce**
1. Create Athena/DynamoDB connector 
https://dev.to/jdonboch/finally-dynamodb-support-in-aws-quicksight-sort-of-2lbl for more info
2. Create tables in DynamoDB with no missing attributes
3. Create an analysis in QuickSight using Athena to detect the DynamoDB tables
4. In the DynamoDB table go to the first row and delete an attribute you use for the analysis.
In our DynamoDB table we had the first row like so: 
![image](https://user-images.githubusercontent.com/45046537/121433409-95e80480-c941-11eb-87bb-bfe88e3a8641.png)
As you can see the first row does not have data in favoritePosts, so Athena doesn't detect that column, therefore QS creates the following error in the analysis 
![image](https://user-images.githubusercontent.com/45046537/121433530-bfa12b80-c941-11eb-8a95-afa98687db90.png)

**Expected behavior**
The connector should detect the whole columns despite the first row has or not data inside that attribute.

**Screenshots / Exceptions / Errors**
One or more columns are missing from the dataset. Check the dataset to verify the columns that you want in this visual. Or you can update the visual to remove any missing columns. QuickSight
![image](https://user-images.githubusercontent.com/45046537/121434008-5241ca80-c942-11eb-9591-ca2e3337e8e3.png)

SYNTAX_ERROR: line 1:37: Column 'favoriteposts' cannot be resolved
This query ran against the "default" database, unless qualified by the query. Athena
![image](https://user-images.githubusercontent.com/45046537/121434710-56bab300-c943-11eb-92f3-dce22ff269b2.png)

**Connector Details (please complete the following information):**
 - Name serverlessrepo-AthenaDynamoDBConnector

**Comment by Dlozitskiy** [comment]
We faced similar issue, and there is another one reported that may be related to the same: https://github.com/awslabs/aws-athena-query-federation/issues/424

There are couple things to be aware of:
1) Athena is trying to use schema introspection if table with matching table name isn't found in Glue Catalog. This can cause some attributes being lost as introspection samples only small portion of data. The recommended approach is to have corresponding Glue Catalog table to support Athena query
2) Glue doesn't support special characters apart from "_"  in names of tables discovered by crawler and also converts column names to lower case (for backwards compatibility with earlier versions of HIVE)

So in order for Athena DDB Connector to recognize Glue Catalog table and successfully map column names you need to:

1) add `dynamo-db-flag` string into `Location URI` property of a Glue Database
2) add property `sourceTable` on the Glue Table created by crawler, it should match the Athena table name (lower case name as you see in Athena)
3) add `columnMapping` property on the Glue Table in a format: "<glue column name 1>=<dynamo db column name 1>, etc..."

**Comment by avirtuos** [comment]
If @Dlozitskiy 's suggestion does not resolve your issue, please reopen this ticket with addition information of what happened when you tried his suggestion.

**Comment by ebisbe** [comment]
> 1. The recommended approach is to have corresponding Glue Catalog table to support Athena query

Can you give me any insight on how to do this? I was trying to avoid to do all the Glue Catalog/Crawler/Jobs stuff but if reached a point where I have some attributes that are null due to they nature ( disabledAt, subscribedAt). If the user is active this value will never be filled, the same happens if the user is not a paying one.

Right, now I'm not sure how to follow... Any link to article/info would help

**Comment by Mateus863** [comment]
Im having the same issue , is there a article/info to do the above with aws glue ?

**Comment by avirtuos** [comment]
This procedure should give you what you are looking for: https://github.com/awslabs/aws-athena-query-federation/tree/master/athena-dynamodb#setting-up-databases--tables-in-glue

**Comment by ebisbe** [comment]
> Im having the same issue , is there a article/info to do the above with aws glue ?

Are you using cloud formation ? I can give you the sample I have to deploy it so it doesn't bother anymore.
