### ISSUE TITLE
[QUESTION] How to resolve DynamoDB map attribute as JSON in query result

### ISSUE THREAD

**Issue by james-ni** [awslabs/aws-athena-query-federation#434]
My DynamoDB table has an item like below. The `name` attribute is a Map type, with `firstName` and `lastName`

![image](https://user-images.githubusercontent.com/10679959/121769151-5cafce80-cba5-11eb-82ee-5971230df9e5.png)

When I query the table from Athena (Using the default DynamoDB connector), the `name` column in result is a string like below.

```sql
select * from "my_dynamodb_data_catalog"."default"."my_dynamodb_table"
```

![image](https://user-images.githubusercontent.com/10679959/121769301-26bf1a00-cba6-11eb-9fc9-e4f5cca1c488.png)

This question is: how can I get a JSON like object from that?
- can I customize the DynamoDB connector to achieve this?
- or I can parse the string `{firstName=John, lastName=Doe}` in the query result to a JSON object? 
```json
{
   "firstName": "John", 
   "lastName":  "Doe"
}
```

**Comment by james-ni** [comment]
Though I sorted it out by tweak the SQL a bit into below,
```sql
select name.firstname, name.lastname from "my_dynamodb_data_catalog"."default"."my_dynamodb_table"
```

still thinks it may be better to return a JSON result, so that I can easily parse the result in my application code (e.g. using Python pandas)

**Comment by avirtuos** [comment]
Can you share why you'd want to have to parse it yourself as opposed to having Athena take care of that for you?

**Comment by james-ni** [comment]
Thanks @avirtuos 

The simple answer is I feel more comfortable parsing these complex data structures (list, map...) in a programming language (like Python with pandas), instead of SQL.

Probably this comes from my impression that the world of SQL is full of different dialects. Every DBMS tends to have something different on top of standard SQL. Therefore I incline to take the strategy that keeps the SQL script as basic as possible and does all dirty work in a programming language like Python.

Anyway, the modified SQL script works for my use case now. Let's see if further issue arises when we have more complex scenarios.

**Comment by ebisbe** [comment]
> Can you share why you'd want to have to parse it yourself as opposed to having Athena take care of that for you?

In my case connecting Athena with Quicksight gave me issues to filter data. 

For example I have this attribute from a third party api:
```
"username": {
    "_content": "Username 1"
  },
```
And I couldn't filter the _content data in Quicksight properly to use in visuals. I'm not sure if I'm doing something wrong though.
