### ISSUE TITLE
[FEATURE] Prometheus Connector

### ISSUE THREAD

**Issue by kiyose** [awslabs/aws-athena-query-federation#436]
**Is your feature request related to a problem? If yes, please describe.**
I would like to be able to access some of our service usage metrics in Athena. Our service metrics are primarily available in Prometheus.

**Describe the solution you'd like**
An Athena Federated Query Connector for Prometheus.

**Describe alternatives you've considered**
I have considered exporting the data we have in Athena to Prometheus.

**Additional context**
I am specifically trying to tie CUR data to our service usage data in order to calculate COGS.

**Comment by jeromeinsf** [comment]
closed as completed?

**Comment by hackett123** [comment]
Didn't realize there was another option when closing tickets - updating status.
