### ISSUE TITLE
[QUESTION] Error build athena-example

### ISSUE THREAD

**Issue by Abagnale92** [awslabs/aws-athena-query-federation#437]
I have a question that I don't think is related to a bug or feature request. 

When  I run the command: ../tools/publish.sh S3_BUCKET_NAME athena-example AWS_REGION

I have this error:
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.015 s <<< FAILURE! - in com.amazonaws.connectors.athena.example.ExampleMetadataHandlerTest
[ERROR] com.amazonaws.connectors.athena.example.ExampleMetadataHandlerTest.initializationError  Time elapsed: 0.001 s  <<< ERROR!
java.util.ServiceConfigurationError: Locale provider adapter "CLDR"cannot be instantiated.
Caused by: java.lang.reflect.InvocationTargetException
Caused by: java.util.ServiceConfigurationError: sun.util.locale.provider.LocaleDataMetaInfo: Unable to load sun.util.resources.cldr.provider.CLDRLocaleDataMetaInfo
Caused by: java.lang.LinkageError: loader 'platform' attempted duplicate class definition for sun.util.resources.cldr.provider.CLDRLocaleDataMetaInfo. (sun.util.resources.cldr.provider.CLDRLocaleDataMetaInfo is in module jdk.localedata of loader 'platform')

Can you help?

**Comment by avirtuos** [comment]
I was able to successfully build the connector. what java version are you using?

**Comment by Abagnale92** [comment]
I tried with Java 11 and Java 16.
I'm using Intellij as IDE, maven version is: 3.6.3.
I tried to reinstall maven and change the jdk but I see ever this error.

**Comment by Abagnale92** [comment]
The error with the connector validation is:

if test -f "target/athena-federation-sdk-tools-2021.21.1.jar"; then
    echo "athena-federation-sdk-tools is already built, skipping compilation."
else
    mvn clean install
fi

java -cp target/athena-federation-sdk-tools-1.0-withdep.jar com.amazonaws.athena.connector.validation.ConnectorValidator $@

this last row need to be change in:
java -cp target/athena-federation-sdk-tools-2021.21.1-withdep.jar com.amazonaws.athena.connector.validation.ConnectorValidator $@

--------------
In local I don't know how to resolve the previous error

**Comment by janmran** [comment]
Are you still facing the same issue? Have you also tried jdk 8?
