### ISSUE TITLE
[BUG] Athena cannot Query PostgreSQL with UUID field in where clause

### ISSUE THREAD

**Issue by vipulrajputt** [awslabs/aws-athena-query-federation#442]
Related to #153 ,

**Describe the bug**

We are getting below error while running query in Athena :
++++++++++++
GENERIC_USER_ERROR: Encountered an exception[java.lang.RuntimeException] from your LambdaFunction[arn:aws:lambda:us-east-1:xxxxxxxxxx:function:postgres-connector] executed in context[S3SpillLocation{bucket=‘xxxxxx-xxxxxx-spill’, key=‘postgres/dxxxxxxxxx/8d604d85-2d38-4576-af66-xxxxxxxx’, directory=true}] with message[0: ERROR: operator does not exist: uuid = character varying Hint: No operator matches the given name and argument types. You might need to add explicit type casts. Position: 197]
++++++++++++
Query used 

SELECT * FROM “catalog_name"."public"."table_name" where column_name = 'xxxxxxx-xxxxx-xxxxx-xxxxx-xxxxxxx’ # UUID

It seems uuid is getting compared with the string. However, below query is working fine :

SELECT * FROM “catalog_name"."public"."table_name" where column_name =uuid() 

As uuid() generates random UUID , Also tried to cast value to UUID but got "unknown type : uuid" error

SELECT * FROM “catalog_name"."public"."table_name" where column_name = cast('xxxxxxx-xxxxx-xxxxx-xxxxx-xxxxxxx’ as uuid)

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a connector which connects to PostgreSQL with a table having columns of UUID.
2. Try to query table in Athena with UUID Column in where clause.

**Comment by janmran** [comment]
Can you try this workaround:
`SELECT * FROM “catalog_name"."public"."table_name" where from_utf8(to_utf8(column_name) = 'xxxxxxx-xxxxx-xxxxx-xxxxx-xxxxxxx’`

**Comment by nichoio** [comment]
Thanks @janmran, this also solved my problem I had with running Athena with Postgres comparing against an enum type.
I would appreciate an explanation what exactly the issue is and how it is solved by `from_utf8(to_utf8())`.

**Comment by podj** [comment]
Hi @burhan94, I see that you were mentioned in https://github.com/awslabs/aws-athena-query-federation/issues/153 regarding the issue of not supporting UUIDs.
There is still this problem where we have to cast UUIDs to VARCHAR in order to join 2 different tables, as mentioned in this thread.

Is there an opened bug? Is it a known issue? Currently, the workaround seems to do the trick but we would love to get it working without it :)

**Comment by christinegu1** [comment]
Hi @janmran - I'd like to follow up on this question nichoio's question. What would be the trigger of this issue? Historically, I've had no issues connecting two tables together via UUIDs, but found myself troubleshooting this problem today.

**Comment by jonathanchen7** [comment]
Hi @burhan94, following up on this thread - casting UUIDs to VARCHARS is a workaround, but it does not take advantage of any indexes on the existing UUID fields. This limitation unfortunately disqualifies the connector as an option for my use case.

**Comment by jonathanchen7** [comment]
We were able to find a workaround! Adding the query parameter `?stringtype=unspecified` to the JDBC connection URL in the PostgreSQL connector/lambda config fixes this problem. It seems like both Athena and PostgreSQL are OK with the `VARCHAR <-> UUID` comparison but the JDBC layer was complaining. Indexes are being utilized as expected on the PostgreSQL end as well.
