### ISSUE TITLE
[BUG] LocalEncryptionKeyFactory.create() often blocks forever on Windows

### ISSUE THREAD

**Issue by avirtuos** [awslabs/aws-athena-query-federation#443]
**Describe the bug**
LocalEncryptionKeyFactory.create() often blocks forever on Windows due to its direct use of SecureRandom to seed the initialization of the KeyGenerator. While this behavior is desirable on Linux since we'd rather block than proceed with a flawed encryption key there seems to be an issue with the cross platform support of either the init(...) or SecureRandom on Windows or Windows Subsystem for Linux.

As such, we may want to add code to LocalEncryptionKeyFactory that attempts to init the KeyGenerator in a secondary thread and if it detects the init taking longer than X seconds, it falls back to a non-init approach like the one shown below or throws suggesting the use of the KMSEncryptionKeyFactory.

**To Reproduce**
1. Run unit tests for athena-example on Windows using Windows SubSystem for Linux 2 after having appropriately edited the code for the example handlers.

**Expected behavior**
Don't block forever on every call, either throw after an appropriate time or fallback to reasonably secure platform dependent option.

Example code that won't block on Windows is shown below but may NOT be equally secure to that the LocalEncryptionKeyFactory does today.

```java
    /**
     * WARNING: DO NOT USE THIS! We are overloading the super method because it can
     *          at time block indefinitely when running on Windows Subsystem for Linux
     *          due to insufficient entropy. The super's implementaiton is more secure.
     *          For this teaching exercise we want the widest range of acceptable development
     *          environments. For max security authors should opt for the KMSEncryptionKeyFactory
     *          over the LocalEncryptionKeyFactory anyway.
     */
    publicEncryptionKey create()
    {
        try {
            Random random = new Random();
            KeyGenerator keyGen = KeyGenerator.getInstance("AES");
            SecretKey key = keyGen.generateKey();
            final byte[] nonce = new byte[12];
            random.nextBytes(nonce);
            return new EncryptionKey(key.getEncoded(), nonce);
        }
        catch (NoSuchAlgorithmException ex) {
            throw new RuntimeException(ex);
        }
    }
```

**Comment by henrymai** [comment]
Resolved in this pr and see this note: https://github.com/awslabs/aws-athena-query-federation/pull/1262#issuecomment-1547975299
