### ISSUE TITLE
[BUG] UDF and ML Documentation and Examples Out of Date with GA Syntax

### ISSUE THREAD

**Issue by avirtuos** [awslabs/aws-athena-query-federation#444]
The query examples in athena-example and possibly other parts of the repository are out of date and no longer work. This appears to be due to syntax changes that were made when Federation and UDF went GA. The EXTERNAL modifier is now expected but the examples haven't been reflected to do that.

As an aside, its unclear to me why we choose to break the preview syntax by adding the EXTERNAL modifier.

**Comment by janmran** [comment]
Fixed in #464
