### ISSUE TITLE
Docdb connection string error - The connection string contains invalid user information. If the username or password contains a colon (:) or an at-sign (@) then it must be urlencoded

### ISSUE THREAD

**Issue by evainthecloud** [awslabs/aws-athena-query-federation#446]
connection string for docdb is passed with secrets manager name in the same format as specified in the README.

mongodb://${secretsname}@hostname:port/?ssl=true&ssl_ca_certs=rds-combined-ca-bundle.pem&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false

When launching the catalog from Athena - the below error is displayed:

"The connection string contains invalid user information. If the username or password contains a colon (:) or an at-sign (@) then it must be urlencoded".

The username nor the password has a colon or at-sign. Tried different ways of invoking the secretsmanager - it still doesn't work.

**Comment by avirtuos** [comment]
Can you share the stack-trace of the error? be sure to remove any sensitive information before posting.

**Comment by avirtuos** [comment]
Also what version of the connector are you using? (we have a [template](https://github.com/awslabs/aws-athena-query-federation/issues/new?assignees=&labels=bug&template=bug_report.md&title=%5BBUG%5D+%3Cdescrption+of+issue%3E+with+connector+%3Cconnector+type%3E) for issues which will show you the questions we typical ask in order to streamline support)

**Comment by evainthecloud** [comment]
**Describe the bug**
Failed to invoke lambda function due to com.amazonaws.services.lambda.invoke.LambdaFunctionException: The connection string contains invalid user information. If the username or password contains a colon (:) or an at-sign (@) then it must be urlencoded (Service: AmazonAthena; Status Code: 400; Error Code: MetadataException; Request ID:xxxxxxxxxxxxxxxxxxxx; Proxy: null)

**To Reproduce**
Steps to reproduce the behavior:
1. Go to 'Athena’, select the ‘catalog’ created for document db(Assumption – connection to external data source – documentdb is completed through the cloudformation stack setup for the Lambda function to establish the connection)
2. It keeps looping on the screen and the above error message is displayed(under “Describe the bug” section)

**Expected behavior**
The tables should have been listed for the docdb database, once the docdb catalog is selected in Athena.

**Screenshots / Exceptions / Errors**
When you enter the username and password for the docdb in the connection string, it works fine and connects. For security reasons, we want to pass the secrets manager name instead and when we use the secrets manager name, we encounter this error.

**CloudWatch Logs Trace:**
2021-06-22 19:36:17 INFO  DocDBMetadataHandler:129 - getConnStr: No environment variable found for catalog xxxx, using default default_xxxx
2021-06-22 19:36:18 INFO  DocDBConnectionFactory:52 - getOrCreateConn: enter
2021-06-22 19:36:18 WARN  CompositeHandler:104 - handleRequest: Completed with an exception.
java.lang.IllegalArgumentException: The connection string contains invalid user information. If the username or password contains a colon (:) or an at-sign (@) then it must be urlencoded
	at com.mongodb.ConnectionString.<init>(ConnectionString.java:318) ~[task/:?]
	at com.mongodb.client.MongoClients.create(MongoClients.java:61) ~[task/:?]
	at com.amazonaws.athena.connectors.xxxx.DocDBConnectionFactory.getOrCreateConn(DocDBConnectionFactory.java:56) ~[task/:?]
	at com.amazonaws.athena.connectors.xxxx.DocDBMetadataHandler.getOrCreateConn(DocDBMetadataHandler.java:118) ~[task/:?]
	at com.amazonaws.athena.connectors.xxxx.DocDBMetadataHandler.doListSchemaNames(DocDBMetadataHandler.java:145) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.MetadataHandler.doHandleRequest(MetadataHandler.java:236) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:132) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:100) [task/:?]
	at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:902) [LambdaSandboxJava-1.0.jar:?]
	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:340) [LambdaSandboxJava-1.0.jar:?]
	at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:63) [LambdaSandboxJava-1.0.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_201]
	at java.lang.Class.forName(Class.java:348) [?:1.8.0_201]
	at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:150) [LambdaJavaRTEntry-1.0.jar:?]

**Connector Details (please complete the following information):**
 - Version: 2021.21.1
 - Name: docdb(mongodb)
 - Athena Query IDs [if applicable]

**Additional context**
Add any other context about the problem here.

**Comment by evainthecloud** [comment]
Hi,

Just wanted to check if there is any insight into this connection string issue on connecting Athena with Docdb?

**Comment by avirtuos** [comment]
Sorry but we haven't been able to look deeply into this yet. Have you tried urlencoding the username and password just in case there is some other character causing issues? : And @ are just two examples of problematic characters.

**Comment by evainthecloud** [comment]
For security reasons, we are using the secrets manager name instead of passing the username and password directly in the connection string.

Connection string that we are passing:

mongodb://**${secretsname}**@hostname:port/?ssl=true&ssl_ca_certs=rds-combined-ca-bundle.pem&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false

Is there a way to pass the username and password of the secrets manager as placeholders in the connection string? For example - ${secrets.username}.

**Comment by avirtuos** [comment]
I'm sorry but your response didn't answer my question or I may be missunderstanding your response. When using secrets manager the connector essentially does a find replace of that secret with the contents of your secrets manager secret. If the contents of the secret contains special characters you may need to ensure the secret is URL encoded when storing it in Secrets Manager. 

As for your follow up question, that is not presently supported. You'd need to have multiple secrets manager secrets to accomplish that today.

**Comment by evainthecloud** [comment]
I checked, there are no special characters in the username and password for docdb in secrets manager. Is it possible for us to get onto a call, so I can show you the issue?

**Comment by et304383** [comment]
@avirtuos  when creating a secret in secrets manager to connect to document DB, it will create many keys/values such as username, password, host, port, etc.

I looked at the source code under CachableSecretsManager under getSecret and I cannot see how the values are broken out to grab just the <username:password> that one would expect to replace ${secretname}.

What is the expected format of the secret in secrets manager?

**Comment by avirtuos** [comment]
There is no expected format the literal contents of the secret is applied.
So, for example some folks put the entire connection string into secrets
manager. Then just have a {$my_secret_conneciton_string} as their config.

**Comment by et304383** [comment]
Wowsers.  That REALLY needs to be documented, as the console immediately drives you to the json format, AND with a DocumentDB type secret (that again, most people will use given they're trying to connect to a DocumentDB) there is no opportunity to put the plain text values in as the README suggests given the example:

```
mongodb://${docdb_instance_1_creds}@myhostname.com:123/?ssl=true&ssl_ca_certs=rds-combined-ca-bundle.pem&replicaSet=rs0
```

This example implies you should put a plain text item in with the format

```
<username>:<password>
```

So that's in no way compatible with the DocumentDB secret type.

**Comment by avirtuos** [comment]
You can do that too. It only expects a plaintext item, how you use it is up
to you. I agree we can put better examples or at least more text explaining
the contents of the secret in our existing examples.

**Comment by et304383** [comment]
@avirtuos  I'm not sure what you mean by "you can do that too."  That's literally the only thing you can do?

**Comment by avirtuos** [comment]
We are not prescriptive about the contents of the secret, for example...
You can have one secret that is "username:password" or two secrets with
username and password respectively or one secret with the entire connection
string.

It might be worth us supporting a nested structure for the secret that
allow key-value Jason resolution as well. I'll see if I can write up some
examples of this to get feedback from you and other interested folks.

**Comment by evainthecloud** [comment]
Thank you @et304383 for calling this out. I replaced the plaintext in secrets manager to <username>:<password> and it worked. Athena is now able to connect to documentdb.

**Comment by mpereira-dev** [comment]
This tripped me up as well. Didn't realize you could set the secret as plain text. Thanks @evainthecloud.
