### ISSUE TITLE
[BUG] Intermittent connection issues when loading tables with connector AthenaJDBC - PostgreSQL

### ISSUE THREAD

**Issue by nihal-aws** [awslabs/aws-athena-query-federation#447]
**Describe the bug**
Hi team, I'm a Cloud Architect from ProServe. I've got a customer who's looking at implementing the AthenaJDBC part of your tool and it’s currently deployed in dev. However, they’re facing some intermittent connection issues when loading tables from a PostgreSQL Database. They sometimes load and sometimes fail. And I’ve narrowed it down to the line of java code which throws the SQLException (org.postgresql.util.PSQLException: The connection attempt failed.). But I can’t seem to go any deeper than that.

The connection seems to fail after being idle for a while. After several tries, the tables will load and then it will work for a while. Based on the Lambda logs it seems to timeout after 10 seconds.

**To Reproduce**
1. Go to the Athena Console
2. Click on Refresh 
3. Approximately 10 seconds later the following error appears:
![Screen Shot 2021-06-24 at 10 53 13 am](https://user-images.githubusercontent.com/64448517/123195337-930d1800-d4da-11eb-9ee1-3caf418feaf7.png)
4. Keep trying several times
5. The tables successfully load for a period of time and then the error appears again

**Expected behavior**
When the Athena console is loaded, the PostgresSQL DB tables load successfully every time.

**Screenshots / Exceptions / Errors**
Lambda Stack Trace:
```
0: org.postgresql.util.PSQLException: The connection attempt failed.: java.lang.RuntimeException
java.lang.RuntimeException: 0: org.postgresql.util.PSQLException: The connection attempt failed.
	at com.amazonaws.connectors.athena.jdbc.connection.GenericJdbcConnectionFactory.getConnection(GenericJdbcConnectionFactory.java:108)
	at com.amazonaws.connectors.athena.jdbc.manager.JdbcMetadataHandler.doListSchemaNames(JdbcMetadataHandler.java:129)
	at com.amazonaws.connectors.athena.jdbc.MultiplexingJdbcMetadataHandler.doListSchemaNames(MultiplexingJdbcMetadataHandler.java:102)
	at com.amazonaws.athena.connector.lambda.handlers.MetadataHandler.doHandleRequest(MetadataHandler.java:236)
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:132)
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:100)
```

Code line which appears to throw the exception:
![Screen Shot 2021-06-22 at 4 33 16 pm](https://user-images.githubusercontent.com/64448517/123195780-5988dc80-d4db-11eb-89c5-a6004ae261db.png)

**Connector Details (please complete the following information):**
 - Version: 2021.18.1
 - Name: AthenaJDBC
 - Athena Query IDs: N/A

**Additional context**
None

**Comment by henrymai** [comment]
Typically these are actual networking issues with the customer's environment this isn't a problem with the connector code itself.

If this is still happening try connecting to the postgres instance with something like psql or dbeaver right after you see this error. Most likely you will see a similar connection issue when using those tools. The line you are pointing to is simply the connector trying to establish a connection with the database.

Closing this issue out.
