### ISSUE TITLE
[QUESTION] Neptune DB querying

### ISSUE THREAD

**Issue by m4t22** [awslabs/aws-athena-query-federation#451]
So I managed to create glue tables for graph nodes and I am able to query all of them via Athena,
my question is how to make use of graph dependencies via Athena SQL queries?
Should I create tables for edges and make inner joins on them?
Some guide on how Athena's SQL to gremlin queries are translated together with some examples would be a nice addition.
Thanks in advance!

**Comment by m4t22** [comment]
@abhishekpradeepmishra can you assist on this one?

**Comment by abhishekpradeepmishra** [comment]
We don't have support for edges, we are building it. Once in place you should be able to do  a 3 way join between two vertices tables and an edge table to traverse a Graph Relationship
