### ISSUE TITLE
[BUG] Counting works but select fails with connector postgresql

### ISSUE THREAD

**Issue by contentfree** [awslabs/aws-athena-query-federation#460]
**Describe the bug**
A simple `select * from my_table;` results in "Zero record returned"
Doing a count on the same table: `select count(*) from my_table;` returns the expected number of rows.

**Expected behavior**
I assume simple queries should work :D 

**Connector Details (please complete the following information):**
 - Version: 2021.27.1
 - Name: jdbc
 - Athena Query IDs:
    Successful count: 862a7418-becf-4672-a30a-c74580de526a
    Failed select: 5255c624-db21-4562-bdb1-0e2fea8948c6

**Comment by contentfree** [comment]
The `select` query says that it scanned 0 KB. The `count` says it queried 186.15 KB.

**Comment by avirtuos** [comment]
while we investigate, can you try one more query? can you repeat your select * but do two variations:

1. select <some_valid_column> from my_table;
2. select * from my_table where <some_valid_column> = <some_present_value>

please substitute some_valid_column for a real column in your table and some_present_value for a value that exists in atleast 1 row in that table for that column. :)

Thanks.

**Comment by contentfree** [comment]
Not sure if something has changed in the last month (seems reasonable) but my simple select queries are working. If I come across more-specific scenarios that fail I'll open a new ticket.
