### ISSUE TITLE
[BUG] error with large number of records with connector to Elasticsearch

### ISSUE THREAD

**Issue by madhavvishnubhatta** [awslabs/aws-athena-query-federation#461]
**Describe the bug**
When I query an index with a large number of rows (roughly greater than about 50,000), I get an error:

```
GENERIC_USER_ERROR: Encountered an exception[org.elasticsearch.ElasticsearchStatusException] from your LambdaFunction[es-connector] executed in context[S3SpillLocation{bucket='<spill-bucket-name>', key='athena-spill/6519b7e0-eaf3-45ce-849b-a2c3d8acd9e3/5d3c9931-bd11-4a23-9d64-04b2f1556a89', directory=true}] with message[Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]]
```

**To Reproduce**
1. Create an index in Elasticsearch and load more than 50,000 records (or more, I am not sure what the threshold is)
2. Count the records using the following query on Kibana Dev Tools
```
POST _opendistro/_sql
{
  "query":""" select count(*) from testindex"""
}
```

The result will be like this
```json
{
  "schema": [
    {
      "name": "count(*)",
      "type": "integer"
    }
  ],
  "datarows": [
    [
      161564
    ]
  ],
  "total": 1,
  "size": 1,
  "status": 200
}
```
3. Now deploy the connector application and query the same index from Athena

```sql
select count(*) from "lambda:es-connector"."es-alleninstitute-data"."cord19"
```

We get the error
```
GENERIC_USER_ERROR: Encountered an exception[org.elasticsearch.ElasticsearchStatusException] from your LambdaFunction[es-connector] executed in context[S3SpillLocation{bucket='<spill-bucket-name>', key='athena-spill/6519b7e0-eaf3-45ce-849b-a2c3d8acd9e3/5d3c9931-bd11-4a23-9d64-04b2f1556a89', directory=true}] with message[Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]]
```

**Expected behavior**
The returns the proper count.

**Screenshots / Exceptions / Errors**
N/A

**Connector Details (please complete the following information):**
 - Version: 2021.27.1
 - Name elasticsearch
 - Athena Query IDs: 6519b7e0-eaf3-45ce-849b-a2c3d8acd9e3.

**Additional context**
The exact query works fine if the number of records is about 47K

**Comment by avirtuos** [comment]
What happens if you run this query on elasticsearch without using Athena? e.g. using some other elastic client?

I ask because this error message seems to suggest that you elasticsearch cluster is having issues under the load of this query. Keep in mind that when you do a count(*) or any aggregation function in Athena, your federated source (e.g. elasticsearch) doesn't get the count(*) but rather a select * because Athena will be doing the counting. Its possible that this simple count(*) is actually asking your easticsearch cluster to do a lot of work in terms of returning ALL the data in that domain/collection.

**Comment by madhavvishnubhatta** [comment]
The same query runs fine on the Kibana Dev tools interface. I too agree that the error message suggests something is wrong with the cluster, but the query fails only on Athena using the connector.

**Comment by rsr28** [comment]
> I ask because this error message seems to suggest that you elasticsearch cluster is having issues under the load of this query. Keep in mind that when you do a count(_) or any aggregation function in Athena, your federated source (e.g. elasticsearch) doesn't get the count(_) but rather a select * because Athena will be doing the counting. Its possible that this simple count(*) is actually asking your easticsearch cluster to do a lot of work in terms of returning ALL the data in that domain/collection.

```
org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]
	at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:177) ~[task/:?]
	at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1706) ~[task/:?]
	at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1683) ~[task/:?]
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1446) ~[task/:?]
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1403) ~[task/:?]
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1373) ~[task/:?]
	at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:915) ~[task/:?]
	at com.amazonaws.connectors.athena.elasticsearch.AwsRestHighLevelClient.getDocuments(AwsRestHighLevelClient.java:148) ~[task/:?]
	at com.amazonaws.connectors.athena.elasticsearch.ElasticsearchRecordHandler.readWithConstraint(ElasticsearchRecordHandler.java:162) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.RecordHandler.doReadRecords(RecordHandler.java:192) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.RecordHandler.doHandleRequest(RecordHandler.java:158) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:138) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:103) [task/:?]
	at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:902) [LambdaSandboxJava-1.0.jar:?]
	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:340) [LambdaSandboxJava-1.0.jar:?]
	at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:63) [LambdaSandboxJava-1.0.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_302]
	at java.lang.Class.forName(Class.java:348) [?:1.8.0_302]
	at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:150) [LambdaJavaRTEntry-1.0.jar:?]
	Suppressed: org.elasticsearch.client.ResponseException: method [POST], host [https://search-maple-search-prod-2gipmg4vo5otpd53wbmnphqd2q.us-west-2.es.amazonaws.com], URI [/role-memberships-v1/_search?typed_keys=true&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true&preference=_shards%3A0&search_type=query_then_fetch&batched_reduce_size=512&ccs_minimize_roundtrips=true], status line [HTTP/1.1 400 Bad Request]
{
    "error": {
        "root_cause": [
            {
                "type": "illegal_argument_exception",
                "reason": "Result window is too large, from + size must be less than or equal to: [10000] but was [10100]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting."
            }
        ],
        "type": "search_phase_execution_exception",
        "reason": "all shards failed",
        "phase": "query",
        "grouped": true,
        "failed_shards": [
            {
                "shard": 0,
                "index": "<index-name>",
                "node": "<node-id>",
                "reason": {
                    "type": "illegal_argument_exception",
                    "reason": "Result window is too large, from + size must be less than or equal to: [10000] but was [10100]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting."
                }
            }
        ],
        "caused_by": {
            "type": "illegal_argument_exception",
            "reason": "Result window is too large, from + size must be less than or equal to: [10000] but was [10100]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting.",
            "caused_by": {
                "type": "illegal_argument_exception",
                "reason": "Result window is too large, from + size must be less than or equal to: [10000] but was [10100]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting."
            }
        }
    },
    "status": 400
}
```
Error says the shard failure but the actual root cause is something different `Result window is too large, from + size must be less than or equal to: [10000] `. Then on deep dive into code found that to get results from elastic search from + size [https://github.com/awslabs/aws-athena-query-federation/blob/c9ea87f3d06408319e740cafe762a3cbf8d12c3b/athena-elasticsearch/src/main/java/com/amazonaws/connectors/athena/elasticsearch/ElasticsearchRecordHandler.java#L161-L162] implementation is used. https://www.elastic.co/guide/en/elasticsearch/reference/7.x/paginate-search-results.html.

`
By default, you cannot use from and size to page through more than 10,000 hits. This limit is a safeguard set by the index.max_result_window index setting. If you need to page through more than 10,000 hits, use the search_after parameter instead.
`

We should be using scrolling with search_after implementation if we want to support querying large data sets from Elasticsearch. One other option is to have limit of max_result_window increased but as it is not advised and may result in poor performance so personally not in favour of increasing that limit.

**Comment by nauy2697** [comment]
We updated the connector to bypass the max_result_window index settings. This will be visible in next release. In the mean time, feel free to build and update the connector. :)
