### ISSUE TITLE
[QUESTION] AthenaDocumentDBConnector & Tableau/SQL editor

### ISSUE THREAD

**Issue by freeIsa** [awslabs/aws-athena-query-federation#465]
Hello,
we have successfully deployed an AthenaDocumentDBConnector to query our DocumentDB SQL-like. It works fine when using the Athena console.
However:

1) even though we can run queries on our collections using a SQL editor (DBeaver), these collections are not shown under the related connection;
2) When connecting Tableau to Athena, even though we can see and query the tables we have in the default AwsDataCatalog (basically, in S3), we cannot see any collection in the connected DocumentDB.

Are these issues related to known limitations or is it possible to change some config options to make things work?
Thanks in advance,

Isabella

**Comment by avirtuos** [comment]
@burhan94 has the JDBC driver been updated to see/fetch federated meta-data (e.g. tables, databases)?

@freeIsa What version of Athena JDBC driver are you using in DBeaver and Tableau? I'm assuming you connect to Athena via a JDBC driver in both tools but I'm not personally familiar with them so want to confirm.

**Comment by freeIsa** [comment]
@avirtuos The driver we use in DBeaver is SimbaAthenaJDBC-2.0.16.1000; the one in Tableau is version 02.00.09.1018.

@burhan94 I tried to add the `MetadataRetrievalMethod=ProxyAPI` option to the "URL template" property of the driver in DBeaver, but nothing happened.

**Comment by freeIsa** [comment]
Hi @burhan94, we decided for a database change a while ago so the issue is not relevant anymore, we can definitely close this. Thanks!
