### ISSUE TITLE
[FEATURE] Feature request - DynamoDB tables encrypted with kms

### ISSUE THREAD

**Issue by yujona** [awslabs/aws-athena-query-federation#468]
**Is your feature request related to a problem? If yes, please describe.**
Currently, tables encrypted with kms are not able to be decrypted if the DynamoDB Connector is used.  On a separate note, there is some documentation that we would like added.  Specifically, we would like if the documentation stated that kms decryption is not supported and that if a schema is not defined, the "quick scan" that the connector does may infer an incorrect schema.

**Describe the solution you'd like**
The solution we would like would be to expose the role which the Connector gives, allowing for us to add new policies to the role such as kms decrypt.  Furthermore, we would like the documentation to be updated with the points stated above.

**Describe alternatives you've considered**
An alternative would be to explicitly add kms decrypt roles to the connector as well.  This would work for our use case, but it would be more ideal to expose the role as then users would be able to customize the connector to their specific needs.

**Additional context**
N/A

**Comment by francoisbailly** [comment]
Until this is addressed, consider updating the README to clearly state that encrypted tables _cannot_ be read by the connector function

**Comment by nauy2697** [comment]
Hi,

Thanks for reaching out on the feature request for DynamoDB.

I was able to read DynamoDB KMS encrypted table with our latest DynamoDB connector (version 2023.12.1). 
I set encryption setting on my DynamoDB test table as `Managed by customer` or `Managed by AWS KMS` , Athena DynamoDB connector was able to show the table's schema correctly and return the data with no issue. 

However, for option `Managed by customer`, you do have to give permission to your lambda execution role on KMS key settings. 

Can you try with our latest connector version?

**Comment by nauy2697** [comment]
Hi,

Thanks for reaching out on the feature request for DynamoDB. Since, this ticked is old and no response for 7 days, I am going to close the ticket. 

If need any further assistance, or having more issues with same topic, feel free to re-open the ticket.
