### ISSUE TITLE
[FEATURE] Add column "tags" in table "ec2_instances" of cmdb connector

### ISSUE THREAD

**Issue by lprincewhn** [awslabs/aws-athena-query-federation#474]
**Is your feature request related to a problem? If yes, please describe.**
Tags of EC2 instances are very helpful for users to link instance to their appliction, business. However, they are not supported by cmdb connector currently. 

**Describe the solution you'd like**
Add column "tags".

**Describe alternatives you've considered**
N/A

**Additional context**
I have implemented this in my own fork and want to merge it into upstream.

**Comment by dbadaya1** [comment]
Resolving as https://github.com/awslabs/aws-athena-query-federation/pull/1290 is merged
