### ISSUE TITLE
[QUESTION] DynamoDB Connector - How to ensure a Query instead of a Scan operation

### ISSUE THREAD

**Issue by ouamer-dahmani** [awslabs/aws-athena-query-federation#476]
Hello!

We have a sudden need to fetch some data that is currently stored in dynamodb and has not been replicated to an Athena table to perform joins on other data that is stored in S3. One of the possible solutions is to try the DynamoDb connector to extend the Athena query engine.

I deployed the SAR app and configured a spill bucket, no AWS Glue table, then started writing very simply queries to test out behavior. I wrote those queries against a tiny table containing about 30 MBs worth of data.

I first wanted to ensure that the engine would use queries instead of table scans to avoid an inordinate consumption of Read Capacity Units.

Below is a query I ran against a table "messages". We get a data set consisting of user ids (this will eventually come from an Athena table) and then try to query dynamodb using those ids as the partition keys.

```sql
WITH ids AS ( 
SELECT * FROM (VALUES '1', '2', '3') as t (id)
),
messages AS (
  SELECT id, timestamp
  FROM "messages"
  WHERE id IN (
    SELECT DISTINCT
      id
    from ids
  )
)
SELECT * FROM ids
LEFT JOIN messages ON messages.id = ids.id
```

I ran this twice and looked at dynamodb consumption:
![image](https://user-images.githubusercontent.com/5343121/130791998-20bf40c0-0b2f-4084-8fbb-7b74b6a97412.png)

The spikes seem to indicate that the entire table was scanned while I was expecting it to instead run 3 query operations, 1 for each id.

Perusing the connector code I saw that it should be possible to use query operations instead of scans. How can we ensure optimal usage here?

Thanks!

**Comment by hackett123** [comment]
The behavior for the DynamoDB Query API (https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Query.html) has a constraint of "You must specify the partition key name and value as an equality condition." As a result of this, any Athena query which allows for multiple values against the partition key will have to use a Scan operator.

To enforce that only Query APIs are ever ran, you will have to run distinct Athena queries for each of the values you intend to query against for your partition key.

In the future we may be able to try and add support for cases such as this, but there's no planning to do so at this time.

**Comment by hackett123** [comment]
If there is substantive need for this feature, please feel free to add a feature request and we can think about how to add this.
