### ISSUE TITLE
[QUESTION] RecordHandler timing out (BlockSpiller hanging)

### ISSUE THREAD

**Issue by ahuwaa** [awslabs/aws-athena-query-federation#488]
We are running into an issue where the record handler lambda execution is timing out:

```
21:00:08 UTC  INFO  S3BlockSpiller:189 - writeRow: Spilling block with <redacted> rows and <redacted> bytes and config <redacted> bytes
21:00:08 UTC  INFO  GeneratedRowWriter:129 - recompile: Detected a new block, rebuilding field writers so they point to the correct Arrow vectors.
21:00:08 UTC  INFO  S3BlockSpiller:307 - write: Started encrypting block for write to S3SpillLocation{<redacted>}
21:00:08 UTC  INFO  S3BlockSpiller:312 - write: Started spilling block of size <redacted> bytes
21:00:08 UTC  WARN  AmazonS3Client:1903 - No content length specified for stream data.  Stream contents will be buffered in memory and could result in out of memory errors.
21:00:09 UTC  INFO  S3BlockSpiller:317 - write: Completed spilling block of size <redacted> bytes
END RequestId: <redacted>
REPORT RequestId: <redacted>	Duration: 900100.16 ms	Billed Duration: 900000 ms	Memory Size: <redacted> MB	Max Memory Used: <redacted> MB	
21:12:50.074Z <redacted> Task timed out after 900.10 seconds
```
As you can see form the timestamps, there is a 12+ minute gap between the last app log and the lambda event log. The very first log (`Spilling block with...`) seems to indicate the block spill for that batch never finishes so I looked at the code and traced it to potentially the [lock/async thread pool](https://github.com/awslabs/aws-athena-query-federation/blob/f3a36aa4bf27e7a63d322e95997072a386da37f1/athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/data/S3BlockSpiller.java#L364-L365)

Have you seen any similar issues before? If you need any more information please let us know.

**Comment by janmran** [comment]
The log also contains `21:00:09 UTC INFO S3BlockSpiller:317 - write: Completed spilling block of size <redacted> bytes` which indicates a block spill was completed. Is this the same block? I can't tell since the bytes size is redacted.

Can you enable more logging and share the new logs? You can do so by adding this environment variable to the lambda function
`ATHENA_FEDERATION_SDK_LOG_LEVEL` with value `debug`

**Comment by ykrystal** [comment]
Closing out ticket due since no response. Please re-open and attach additional logs if this is still an issue.
