### ISSUE TITLE
[QUESTION] athena-dynamodb connector isn't updating table schema automatically 

### ISSUE THREAD

**Issue by hlinfg** [awslabs/aws-athena-query-federation#490]
Hi,

I have an AthenaDynamoDBConnector that is connecting Dynamodb to Athena. I have some tables in Dynamodb that get dropped and recreated each day. Initially these tables only have so many key-value pairs (like expected_event_time), but about 7am ET, new key value pairs get added (like actual_event_time). I want Athena to update automatically with the new columns (or update on some schedule.) The Athena table should have expected_event_time and actual_event_time soon after actual_event_time key value is in dynamodb. 

Right now the table schema randomly updates. One day, the schema is updated at 10am. Another day, the schema isn't even updated by 1pm.

Could you please help?

Best,

Harry.

PS, I believe this person had the same issue? but it seems he found a work around
https://github.com/awslabs/aws-athena-query-federation/issues/348
 
yrybak commented on Feb 9
Hi,

I configured DynamoDB data source for DynamoDB and everything seems to works well.
New tables, created in DynamoDB, appears automatically in Athena data source tables list.

Lambda stack shows version 2020.33.1 in tags.

But I noticed for some tables that fields definition in Athena is not updated automatically. New fields added to the DynamoDB table don't appear in the list of table fields in Athena. Querying of new columns throws error.

Is there any way to refresh table definition or should it work automatically?

Thanks,
Yaroslav

**Comment by racheliurui** [comment]
@janmran could you please update the document to be specific:
After the first time deploy the connector, will I be able to query directly from Athena?

At the moment, I am not sure if the Glue configuration is mandatory or not. Is that only when I regularly change the scheme /data structure, then I need to manually configure Glue ?
or Glue Crawler is always mandatory and if I don't configure, I can't use the connector.

A bit confused by reading the documentation.

Thanks !
