### ISSUE TITLE
[FEATURE] Add a lambda flag environment variable, translate_object_id, to athena-docdb, to control translating queries on _id properties

### ISSUE THREAD

**Issue by theFlyRoper** [awslabs/aws-athena-query-federation#507]
**Problem**
When querying MongoDB, I can't filter or join on properties of type ObjectId, particularly `_id` properties.  Per documentation, all documents will contain an `_id` property, which will always be stored as a mongodb object id.  Right now, the query engine presents these values as strings.  Athena can display these values but filters on them don't work, because in MongoDB all queries that filter on `_id` must translate strings into the ObjectId value.

**Proposal**
The best way to translate a string into an objectId value is to use the mongodb internal function `ObjectId()`.  So, I propose a lambda environment variable that tells the function to convert any comparisons to an `_id` property to wrap whatever is being compared in that function.  

For example, an athena query like this:
`select *
from mongocollection
where _id = '444444d8e5930afaa0c92332'`
would convert to a mongodb findMany query, thus:
 `db.mongocolletion.findMany({ "_id": ObjectId('444444d8e5930afaa0c92332')})`

Controlling this with a flag would prevent breaking changes for existing users.

**Describe alternatives you've considered**
Most alternatives would involve changing or adding properties to documents, which I would prefer not to do.  There is no glue advanced type that covers this use case, and no way to define a custom type to translate this value.

**Comment by AbdulR3hman** [comment]
this is now addressed in the latest release.
