### ISSUE TITLE
[BUG] Elasticsearch connector unable to list/query datastreams

### ISSUE THREAD

**Issue by npow** [awslabs/aws-athena-query-federation#511]
**Describe the bug**
1. Show tables does not return any datastreams: ```show tables in `lambda:elasticsearch`.es```
2. When trying to query datastream directly, runtime exception is thrown: ```describe `lambda:elasticsearch`.es.pages```

**To Reproduce**
1. run `show tables` on an ES instance with datastreams
2. try to query the datastream directly

**Expected behavior**
Expect datastreams to show up and behave like regular tables

**Screenshots / Exceptions / Errors**
```
java.lang.RuntimeException: com.amazonaws.services.lambda.invoke.LambdaFunctionException: Error processing request to map index (pages): null
```

**Connector Details (please complete the following information):**
 - Version: [e.g. 2020.04.01 - 2021.42.1
 - Name [e.g. redis, hbase, jdbc]: elasticsearch
 - Athena Query IDs [if applicable]:  d38b8bfe-81eb-4fd0-9883-2381941360f5

**Additional context**
Elasticsearch datastreams: https://www.elastic.co/guide/en/elasticsearch/reference/master/data-streams.html

**Comment by chngpe** [comment]
Hi,

We have added support for data stream on ES connectors, please use our latest version >=2023.18.1
