### ISSUE TITLE
elasticsearch connector query error

### ISSUE THREAD

**Issue by gsjoy8888** [awslabs/aws-athena-query-federation#513]
Hi,

I'm testing elasticsearch connector and seeing the below error when executing sql queries in Athena. The error log was copied from lambda log group in Cloudwatch logs. Need your support to point me to the right direction for troubleshooting, thanks!

Unable to create domain map: DomainMapping Parsing error.: java.lang.RuntimeException
java.lang.RuntimeException: Unable to create domain map: DomainMapping Parsing error.
	at com.amazonaws.athena.connectors.elasticsearch.ElasticsearchDomainMapProvider.getDomainMapFromEnvironmentVar(ElasticsearchDomainMapProvider.java:158)
	at com.amazonaws.athena.connectors.elasticsearch.ElasticsearchDomainMapProvider.getDomainMap(ElasticsearchDomainMapProvider.java:87)
	at com.amazonaws.athena.connectors.elasticsearch.ElasticsearchMetadataHandler.<init>(ElasticsearchMetadataHandler.java:117)
	at com.amazonaws.athena.connectors.elasticsearch.ElasticsearchCompositeHandler.<init>(ElasticsearchCompositeHandler.java:33)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

The lambda environment variables are as below, the secret can be retrieved without any issue:

auto_discover_endpoint | false
disable_spill_encryption | false
domain_mapping | https://${opensearch}:search-opensearch-6ccaemuudyuqxxlob7k6yjt6x54.cn-north-1.es.amazonaws.com.cn
query_timeout_cluster | 10
query_timeout_search | 720
spill_bucket | athena-elasticsearch-connector-spill
spill_prefix | athena-spill

**Comment by stefan-novak-brt** [comment]
Hi @gsjoy8888, I came across the same issue and was curious what formatting you used for the domain mapping. Thanks!

**Comment by gsjoy8888** [comment]
> Hi @gsjoy8888, I came across the same issue and was curious what formatting you used for the domain mapping. Thanks!

Here is an example in my environment:

tableau-athena-opensearch=https://${ealstcsearch-secret}:search-tableau-athena-opensearch-xxxxxxxxx

"tableau-athena-opensearch" is your elasticsearch domain name
"ealstcsearch-secret" is the name of the secret you created in Secrets Manager
"search-tableau-athena-opensearch-xxxxxxxxx" is the name of elasticsearch domain endpoint URL

**Comment by RohitJadhav95** [comment]
> > Hi @gsjoy8888, I came across the same issue and was curious what formatting you used for the domain mapping. Thanks!
> 
> Here is an example in my environment:
> 
> tableau-athena-opensearch=https://${ealstcsearch-secret}:search-tableau-athena-opensearch-xxxxxxxxx
> 
> "tableau-athena-opensearch" is your elasticsearch domain name "ealstcsearch-secret" is the name of the secret you created in Secrets Manager "search-tableau-athena-opensearch-xxxxxxxxx" is the name of elasticsearch domain endpoint URL

Hi, thanks for the information. I am too facing the same problem and want to implement this solution. However, I had 3 questions - 
1) How are you creating the "ealstcsearch-secret", is it using aws secrets manager?
2) If yes, then in what format are storing the secret?
3) What permissions are associated with this secret? Does it have credentials to provide account for sending signed requests or Does it have credentials used to authorize elasticsearch domain?

Thanks in advance

**Comment by gsjoy8888** [comment]
> > > Hi @gsjoy8888, I came across the same issue and was curious what formatting you used for the domain mapping. Thanks!
> > 
> > 
> > Here is an example in my environment:
> > tableau-athena-opensearch=https://${ealstcsearch-secret}:search-tableau-athena-opensearch-xxxxxxxxx
> > "tableau-athena-opensearch" is your elasticsearch domain name "ealstcsearch-secret" is the name of the secret you created in Secrets Manager "search-tableau-athena-opensearch-xxxxxxxxx" is the name of elasticsearch domain endpoint URL
> 
> Hi, thanks for the information. I am too facing the same problem and want to implement this solution. However, I had 3 questions -
> 
> 1. How are you creating the "ealstcsearch-secret", is it using aws secrets manager?
> 2. If yes, then in what format are storing the secret?
> 3. What permissions are associated with this secret? Does it have credentials to provide account for sending signed requests or Does it have credentials used to authorize elasticsearch domain?
> 
> Thanks in advance

Hi @RohitJadhav95, yes please use plaintext format like "username@password" in aws secrets manager. I think permission is optional, I didn't dig into it but you can choose the way you like.

**Comment by RohitJadhav95** [comment]
> > > > Hi @gsjoy8888, I came across the same issue and was curious what formatting you used for the domain mapping. Thanks!
> > > 
> > > 
> > > Here is an example in my environment:
> > > tableau-athena-opensearch=https://${ealstcsearch-secret}:search-tableau-athena-opensearch-xxxxxxxxx
> > > "tableau-athena-opensearch" is your elasticsearch domain name "ealstcsearch-secret" is the name of the secret you created in Secrets Manager "search-tableau-athena-opensearch-xxxxxxxxx" is the name of elasticsearch domain endpoint URL
> > 
> > 
> > Hi, thanks for the information. I am too facing the same problem and want to implement this solution. However, I had 3 questions -
> > 
> > 1. How are you creating the "ealstcsearch-secret", is it using aws secrets manager?
> > 2. If yes, then in what format are storing the secret?
> > 3. What permissions are associated with this secret? Does it have credentials to provide account for sending signed requests or Does it have credentials used to authorize elasticsearch domain?
> > 
> > Thanks in advance
> 
> Hi @RohitJadhav95, yes please use plaintext format like "username@password" in aws secrets manager. I think permission is optional, I didn't dig into it but you can choose the way you like.

Hi, thanks for quick response. I tried using an IAM user's credentials in the secret manager assuming it can be used for signing the requests and used that secret in the domain mapping. 

However, I am still facing this error in Athena when I try to list the indices - 
"""
Failed to get tables names from lambda function due to com.amazonaws.services.lambda.invoke.LambdaFunctionException: Error processing request to list indices: method [HEAD], host [https://search-es-alleninstitute-data-estnkx6kx3m4zuy4hbijuwkt2y.us-east-1.es.amazonaws.com], URI [/], status line [HTTP/1.1 403 Forbidden]

"""

**Comment by Bennyelg** [comment]
Did you solve the issue? if so what have you done to fix it?
