### ISSUE TITLE
[QUESTION] Using CDK how to set the Lambda Environment Variable for a Postgres JDBC Connector

### ISSUE THREAD

**Issue by jackchi** [awslabs/aws-athena-query-federation#517]
My goal is to use Athena federated queries for Aurora using this JDBC Connector. 

In the documentation, the connection string is defined with the Lambda environment variable `${athena_data_datalog_name}_connection_string`. I got it to work via click-ops. But I want to manage it with CDK.

However, this goes away when the CDK Stack re-deploys.

![athena-postgres-jdbc](https://user-images.githubusercontent.com/255235/140806413-ab27a952-e8bc-4a82-b51a-2c2c3b355f52.png)

I've tried:
```python
app = sam.CfnApplication(
            self,
            'athena-jdbc-connector',
            location=location,
            parameters={
                      ....,
                       'DefaultConnectionString':'postgres://jdbc:postgresql://my-aurora-db:port/db?{Secrets}',
                       'DataCatalogNameConnectionString':'...',
            }
```
with no success. 

When I run `cdk deploy <my-stack-name>`, it gives me:

```bash
Parameters: [DataCatalogNameConnectionString] do not exist in the template parameters. 
```

Do you suggest using [something](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_sam/CfnApplication.html#aws_cdk.aws_sam.CfnApplication.add_override) like `Cfn.Application.add_override(property,value)` ?

Or how does the team propose to solve this problem for devops?

**Comment by xbno** [comment]
running into the same issue here, seems like theres a manual step required to set the DataCatalogNameConnectionString value since env vars aren't available. please add this capability

**Comment by janmran** [comment]
You would need to modify the athena-jdbc.yaml template to add a new parameter called `DataCatalogNameConnectionString` and a new  environmental variable `<athena catalog name>_connection_string` that references the param `DataCatalogNameConnectionString`.

**Comment by henrymai** [comment]
I think that if you're mainly looking to just use the `default` connection string, you can make use of this new SAM template parameter that was added in version 2022.44.1: https://github.com/awslabs/aws-athena-query-federation/blob/master/athena-postgresql/athena-postgresql.yaml#L51

Just set `CompositeHandler` to `PostGreSqlCompositeHandler` along with your `DefaultConnectionString` and I think your problem should be solved.
