### ISSUE TITLE
[QUESTION] DynamoDB connector document mentioned Glue configuration but didn't mention if it's mandatory

### ISSUE THREAD

**Issue by racheliurui** [awslabs/aws-athena-query-federation#518]
After the first time deploy the connector, will I be able to query directly from Athena?

At the moment, I am not sure if the Glue configuration is mandatory or not. Is that only when I regularly change the scheme /data structure, then I need to manually configure Glue ?
or Glue Crawler is always mandatory and if I don't configure, I can't use the connector.

A bit confused by reading the documentation.

Thanks !

===

BTW, I used to be able to query the dynamodb staight away but can't do it anymore after swithing to a new env.
ATM, I am not sure if it's env issue or I did something wrong or the connector get updated..
I have tried to manually configure a glue crawler to crawler my dynamodb tables but still those schemas are not showing up in Athena

**Comment by janmran** [comment]
Glue metadata isn't mandatory for DDB connector. Also if you are using glue with the connector, make sure your lambda function's vpc has internet or a vpc endpoint to glue.
