### ISSUE TITLE
[QUESTION] Can I use Athena federated to only return metadata for query, but keep reading with HIVE(parquet) connector?

### ISSUE THREAD

**Issue by GrigorievNick** [awslabs/aws-athena-query-federation#520]
I have a question that I don't think is related to a bug or feature request. 

In my company I have a custom Metadata catalog, where I have a list of files and metadata.
Something similar to Iceberg/delta, but the data itself is organized in a compatible way with HIVE table in parquet.

So my question is  - can I override only metadata handling but keep using a built-in connector for file reading from s3?
I believe, In my case amount of data is so big, that reading them through lambda function is too expensive and also creates too big latency overhead for additional network flow.

**Comment by burhan94** [comment]
Hi, this use case sounds like a good candidate for our External Hive Metastore feature: https://docs.aws.amazon.com/athena/latest/ug/connect-to-data-source-hive.html

**Comment by GrigorievNick** [comment]
But hive metastore api work only on partition level. And I need some api on
file or InputSplit level.

вт, 30 нояб. 2021 г., 20:02 burhan94 ***@***.***>:

**Comment by burhan94** [comment]
Hi, is this still an issue?

**Comment by GrigorievNick** [comment]
Nope, now I use iceberg connector.

пн, 8 мая 2023 г., 18:38 burhan94 ***@***.***>:
