### ISSUE TITLE
[BUG] Zero Parameter Functions do not work with connector UDF

### ISSUE THREAD

**Issue by sbrandtb** [awslabs/aws-athena-query-federation#523]
**Describe the bug**

It seems like functions with zero arguments do not work. Wether or not this is a useful use case is a different question. Just seeing a random NullPointer when playing around is very confusing and possibly time consuming.

**To Reproduce**

```java
public class UserDefinedFunctions extends UserDefinedFunctionHandler
{
    private static final String SOURCE_TYPE = "FRIDAY";

    public UserDefinedFunctions()
    {
        super(SOURCE_TYPE);
    }

    public Integer return_one() {
        return 1;
    }

    public Integer return_one_with_param(Integer i) {
        return 1;
    }
}
```

```sql
USING EXTERNAL FUNCTION return_one_with_param(i integer) RETURNS integer LAMBDA 'AthenaUdfSbr'
select return_one_with_param(1);
-- 1

USING EXTERNAL FUNCTION return_one() RETURNS integer LAMBDA 'AthenaUdfSbr'
select return_one();
-- [HY000][100071] [Simba][AthenaJDBC](100071) An error has been thrown from the AWS Athena client. GENERIC_USER_ERROR: com.facebook.presto.spi.PrestoException: Encountered an exception[java.lang.NullPointerException] from your LambdaFunction[AthenaUdfSbr] executed in context[calling UDF method return_one] with message[java.lang.NullPointerException] [Execution ID: 7d5a7cc0-cf6b-4759-9026-090d4ec60505]
```

**Expected behavior**
No exception, but 1 returned.

**Screenshots / Exceptions / Errors**
See above.

**Connector Details (please complete the following information):**
 - Version: 2021.42.1
 - Name: UDF
 - Athena Query IDs: 7d5a7cc0-cf6b-4759-9026-090d4ec60505

**Comment by hackett123** [comment]
I can't think of any meaningful use cases for a zero-arg UDF, seeing as the UDFs are meant to allow users to run functions against their rows. I can see, however, that the NPE is a confusing error for someone who is just trying to deploy something to test.

I can have our documentation writer add a known limitation that we do not support no-arg UDFs. I'll close out this ticket once it's published.

**Comment by hackett123** [comment]
The docs will be live in a few hours. Closing this ticket now.

**Comment by sbrandtb** [comment]
@hackett123 With all due respect, after doing nothing, this is the worst possible solution. Being a developer that regularly reads documentation, I guarantee you that having some remote limitation documented somewhere would most likely not have stopped me from wondering and spending too much time on trying to debug this.

Maybe I am naive, but this looks like something that could be caught in a simple `if` or `try/catch` statement, throw more meaningful error message and add one test for it. If that part of the implementation wouldn't be closed source, I would do it.

If it is not closed source, then pardon, but please point me to the code.
