### ISSUE TITLE
[QUESTION] [How-to] Athena JDBC connector local test

### ISSUE THREAD

**Issue by jerrywonggithub** [awslabs/aws-athena-query-federation#563]
I have a question that I don't think is related to a bug or feature request. 

I would like to integrate this connector in my own environment, however I am not able to find a way to pass parameters or any function entry for invocation.

May I have any advice? Thanks.

**Comment by janmran** [comment]
We have integration tests setup which you can run in your own environment. See https://github.com/awslabs/aws-athena-query-federation/tree/master/athena-jdbc#running-integration-tests
