### ISSUE TITLE
Update Dependencies

### ISSUE THREAD

**Issue by avirtuos** [awslabs/aws-athena-query-federation#564]
**Describe the bug**
Updating log4j dependencies

**Comment by ramblingenzyme** [comment]
@avirtuos Should there be another update to 2.17.0? https://www.bleepingcomputer.com/news/security/all-log4j-logback-bugs-we-know-so-far-and-why-you-must-ditch-215/

**Comment by janmran** [comment]
2021.51.1 now has log4j 2.17.0
