### ISSUE TITLE
[QUESTION] [How-to] Access dynamo data from another region while creating data connector

### ISSUE THREAD

**Issue by Mansh05** [awslabs/aws-athena-query-federation#566]
I have a question that I don't think is related to a bug or feature request. 

I am creating athena data connector in the region of us-east-1 but the thing is my dynamodb is situated in us-west-1. Apart from the dynamodb, all of my other resources are in us-east-1 and would like to keep it that way.

Is there a way to connect my athena data connector through a lambda which is situated in region us-east-1 to connect to dynamodb situated at region us-west-1?

**Comment by janmran** [comment]
Theres no built in feature to do this. But you can probably do so my building the DDB client with custom params (customer region) in 
https://github.com/awslabs/aws-athena-query-federation/blob/master/athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/DynamoDBMetadataHandler.java#L142 
and
 https://github.com/awslabs/aws-athena-query-federation/blob/master/athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/DynamoDBRecordHandler.java#L114
