### ISSUE TITLE
[QUESTION] using "left join" doesn't working

### ISSUE THREAD

**Issue by diegopmayer** [awslabs/aws-athena-query-federation#603]
I have a question that I don't think is related to a bug or feature request. 

I have following tables
irsc -> 364.808 registers (table left)
irsct -> 52.365 registers (table right)

It is supposed to when I use the left join it must return the minimum of table left 364.080 more the match is it?
let's see an example:

select 
    c.id, c.parent, t.id, t.parent
from irsc as c
left join irsct as t on c.parent = t.parent

But return only the equal comparison of a parent, if match return else doesn't return.
Why the left join it working the same way of inner join? if I use, inner join, join, left outer join and left join -> returns the same result

**Comment by rs-sathya** [comment]
Seeing this issue as well, some of our left joins are acting as though they're inner joins, or close to it. It's strange.

**Comment by abwl084** [comment]
Same here

**Comment by nauy2697** [comment]
Hi, 

Can you please share which connector is using? and does this happened only for specific connector?

**Comment by chngpe** [comment]
This issue appear to be an engine issue rather than connector issue. Federated connector only perform metadata and record retrieval. Connector doesn't perform join.

Going to close this ticket since this is issue from engine
