### ISSUE TITLE
Updating code to latest log4j2 version - Security issue relating to the open-source Apache “Log4j2" utility

### ISSUE THREAD

**Issue by evainthecloud** [awslabs/aws-athena-query-federation#604]
Hi,

Regarding the latest security issue with the above apache utility, how do we update the CF stack to pull the latest code from github, so I can avoid deleting the stack and creating a new one, so that the latest code is pulled in which contains the new patch of log4j version 2.15.0 - to mitigate this vulnerability. This way the CW logs are not deleted.

Also, just updating the code with the latest version will fix the security issue?
https://aws.amazon.com/security/security-bulletins/AWS-2021-006/

This is more of a request on how to, rather than an issue with the code.

It would be nice to see Athena federated queries as a built in feature, rather than deploying it with CF every-time to get the latest code.

Thanks.

**Comment by ramblingenzyme** [comment]
@evainthecloud We're just going through this internally too and found this https://docs.aws.amazon.com/serverlessrepo/latest/devguide/serverlessrepo-how-to-consume-new-version.html

TL;DR you install it again with the same name.

**Comment by janmran** [comment]
2021.51.1 is now in Serverless Application Repository and it contains log4j 2.17.0. You have to deploy the new version of the connector. I don't believe Serverless Application Repository has the ability to replace an existing deployed lambda function.
