### ISSUE TITLE
[FEATURE] Multiple calls to getTableLayouts()

### ISSUE THREAD

**Issue by avirtuos** [awslabs/aws-athena-query-federation#63]
We've seen cases where Athena calls getTableLayouts(...) multiple times for a given query. This is not expected and seems to suggest that Athena's optimizer is looking for different options (layouts) to find the best one. This task is to:

1.  try and reproduce that (a simple query against any table with at least 1 partition should suffice) and see why this happened or if it was an artifact of the environment I saw it in (which was imperfect). 
1. stop issuing redundant calls if we have no indication that additional layouts are possible.

**Comment by hackett123** [comment]
The Athena V3 Query Engine will cache calls to `GetTableLayout`, among other requests that are issued multiple times in the planning phase. Any customers looking for perf boosts here should make sure their Athena engine version is set to V3.

As it is the responsibility of the calling entity to cache results, there is no action to take in the connectors themselves. Closing this ticket out.
