### ISSUE TITLE
[FEATURE] Java8 runtime update for Athena DynamoDB Connector

### ISSUE THREAD

**Issue by seanWLawrence** [awslabs/aws-athena-query-federation#647]
**Is your feature request related to a problem? If yes, please describe.**
Can we update the runtime for the Athena DynamoDB Connector as outlined in this blog post: https://aws.amazon.com/blogs/compute/announcing-migration-of-the-java-8-runtime-in-aws-lambda-to-amazon-corretto/

**Describe alternatives you've considered**
Forking and upgrading manually

**Additional context**
I'm not a Java developer, but I'm happy to timebox solving this if it's valuable to the project.

**Comment by janmran** [comment]
https://github.com/awslabs/aws-athena-query-federation/blob/master/athena-dynamodb/athena-dynamodb.yaml#L61
Java runtime was already `java8` and since November 5, 2021 only Corretto Java8 is available so the migration has already happened.
