### ISSUE TITLE
Log4j2 version update to 2.17.1

### ISSUE THREAD

**Issue by evainthecloud** [awslabs/aws-athena-query-federation#651]
Hi,

This is in continuation to the closed issue - [(https://github.com/awslabs/aws-athena-query-federation/issues/604)] - I wanted to check on when the new code containing the log4j2 version of **2.17.1** becomes available for use.

**Comment by anwari666** [comment]
Hi @evainthecloud , I created PR #650 to bump the version but it's yet to be reviewed

**Comment by evainthecloud** [comment]
Hi @anwari666 . Thank you for the response. Do we have an ETA as to how soon it can get reviewed, as our reporting is on hold, since we are waiting to deploy this fix to mitigate the security vulnerability of log4j2.

**Comment by Gav76** [comment]
@evainthecloud the update has been approved and merged.

**Comment by evainthecloud** [comment]
Thank you @Gav76 for the update.
