### ISSUE TITLE
[BUG] The schema of my table dynamo doesn't update in athena  with connector dynamo

### ISSUE THREAD

**Issue by johangar-dreamc** [awslabs/aws-athena-query-federation#657]
previous question in issue #655  

I have a table in dynamo with more than 50 rows(45 colums per row), when I add the next row with a new field(46 columns) and execute a query in athena the new field is not present in the result(45 colums yet)  and this query generate an error
select newcolumn from 'my-table'
SYNTAX_ERROR: line 1:7: Column 'newcolumn' cannot be resolved

if execute the following query the result doesn't show the new column
select * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'default' AND TABLE_NAME = 'my-table'

But, if I have for example 25 rows and add the new row with extra column it works fine. Also if I have the problem and delete row to have 25, it update the schema and show the new column

1. Go to dynamo and insert 50 or more rows
2. execute a query to see the rows(works fine at moment)
3. Next go to dynamo a insert a new row with a extra column
4. execute a query again, the new colum is not present 
5. execute a specific query with the new colum e.g. select newcolumn from 'my-table'
6. see the error SYNTAX_ERROR: line 1:7: Column 'newcolumn' cannot be resolved

The expected to happen is that query contains the new colums when execute the query again.

Connector Details 
 - Version: [2022.2.1 - 2021.49.2]
 - AthenaDynamoDBConnector

**Comment by janmran** [comment]
Instead of relying on the DynamoDB Connector's limited ability to infer schema, I recommend you setup a Glue Table, especially if only one contains the extra column. https://github.com/awslabs/aws-athena-query-federation/tree/master/athena-dynamodb#setting-up-databases--tables-in-glue

**Comment by johangar-dreamc** [comment]
> Instead of relying on the DynamoDB Connector's limited ability to infer schema, I recommend you setup a Glue Table, especially if only one row contains the extra column. https://github.com/awslabs/aws-athena-query-federation/tree/master/athena-dynamodb#setting-up-databases--tables-in-glue

I follow the instructions in the readme but, when I try to define the parameters these two options don't exist in the .yaml and generate an error

disable_glue - (Optional) If present, with any value except false, the connector will no longer attempt to retrieve supplemental metadata from Glue.
glue_catalog - (Optional) Can be used to target a cross-account Glue catalog. By default the connector will attempt to get metadata from its own Glue account.

**Comment by janmran** [comment]
> disable_glue - (Optional) If present, with any value except false, the connector will no longer attempt to retrieve supplemental metadata from Glue.
> 
> glue_catalog - (Optional) Can be used to target a cross-account Glue catalog. By default the connector will attempt to get metadata from its own Glue account.

Are lambda environment variables. You do not set them in the yaml file. Plus you don't even need to set any values for them in your case. You just need to create the glue db and tables according to the doc

**Comment by henrymai** [comment]
Not an actual issue. As the previous commenter mentioned, there is no need to touch those environment variables that were mentioned.

Here is a similar more recent issue that has some information on setting up your Glue Table: https://github.com/awslabs/aws-athena-query-federation/issues/776#issuecomment-1274118229
