### ISSUE TITLE
Arrow Schema Serialization for Arrow 0.15.0 and up

### ISSUE THREAD

**Issue by grundprinzip** [awslabs/aws-athena-query-federation#66]
While building a Python (and Rust) driver for the federation lambda functions, I stumbled across the issue that there seems to be an incompatibility when deserializing old IPC messages.

See: Columnar “Streaming Protocol” Change since 0.14.0 in http://arrow.apache.org/blog/2019/10/06/0.15.0-release/

I think, it would be great to either document this issue or check if it would be possible to upgrade the Arrow version to 0.15+.

**Comment by burhan94** [comment]
Upgraded arrow to 3.0.0. closing ticket.
