### ISSUE TITLE
[BUG] Empty fields are returned with connector DynamoDB

### ISSUE THREAD

**Issue by gianlucb** [awslabs/aws-athena-query-federation#666]
**Describe the bug**
I setup the Athena DDB connector and a Glue table to provide the metadata.
When I execute the query (SELECT * FROM "glue_table_name") using the Glue table the majority of the fields returned are "**Empty**", _I have all the rows and all the columns but only some columns are populated._
When the same query is executed with the real "_dynamo db table_" name everything is fine (the connector infers the schema).

**Expected behavior**
The query using the GLUE Table (metadata) must return all the fields values

**Screenshots / Exceptions / Errors**
No errors in cloudwatch (even with the DEBUG variable set)

**Connector Details (please complete the following information):**
 - Version: 2021.27.1
 - Name serverlessrepo-AthenaDynamoDBConnector

**Additional context**
I reproduced this in 3 different AWS Accounts.
The schema in GLUE match 100% the one inferred (mostly string fields)

**Comment by henrymai** [comment]
Spoke with @gianlucb internally and confirmed with him that his problem was related to column names with casing.

The current workaround/solution is to set the "columnMapping" Glue Table property as mentioned here:
https://github.com/awslabs/aws-athena-query-federation/tree/master/athena-dynamodb

> columnMapping - Optional table property/parameter that define column name mappings. Use this if Glue column naming rules prevent you from creating a Glue table with the same column names as your DynamoDB table (e.g. capital letters are not permitted in Glue column names but are permitted in DynamoDB column names). This is expected to be in the format col1=Col1,col2=Col2.

Closing out this issue, but we are continuing to track better solutions for dealing with this internally.
