### ISSUE TITLE
connection string. using secrets manager

### ISSUE THREAD

**Issue by dcssi** [awslabs/aws-athena-query-federation#681]
I setup the jdbc connector, i created the secret in the secrets manager with 
user, and password.

When I tried using the lambda it failed with the error User can not be null.
After hours trying, i figured out that the secret is supposed to have a
username
password 

fields.  However the error message says User

**Comment by pjagwani** [comment]
Can you please provide an example of the connection string using secrets manager?

**Comment by akuzin1** [comment]
Due to inactivity this issue will be closed. If issue persists please reopen.
