### ISSUE TITLE
[FEATURE] Support IAM for connecting to Redshift

### ISSUE THREAD

**Issue by Limess** [awslabs/aws-athena-query-federation#682]
**Is your feature request related to a problem? If yes, please describe.**
I'd like to connect to Redshift via IAM to avoid having to manage credentials

**Describe the solution you'd like**
To be able to use an IAM jdbc URL: https://docs.aws.amazon.com/redshift/latest/mgmt/jdbc20-configure-authentication-ssl.html

**Additional context**
Currently an error is received when trying to use IAM in a connection URL:

```
com/amazonaws/services/redshift/AmazonRedshiftClientBuilder: java.lang.NoClassDefFoundError
java.lang.NoClassDefFoundError: com/amazonaws/services/redshift/AmazonRedshiftClientBuilder
	at com.amazon.redshift.core.IamHelper.setClusterCredentials(Unknown Source)
	at com.amazon.redshift.core.IamHelper.setIAMCredentials(Unknown Source)
```

**Comment by clklachu** [comment]
I have the exact same issue. Are there any workarounds?

**Comment by chngpe** [comment]
Closing ticket since @akuzin1
