### ISSUE TITLE
[BUG] Default connector cannot be named as described by Redshift connector documentation

### ISSUE THREAD

**Issue by Limess** [awslabs/aws-athena-query-federation#683]
**Describe the bug**
The redshift connector documentation suggests that if the Athena catalog is named `lambda:${AWS_LAMBDA_FUNCTION_NAME}` then the default connection string will be used.

However, this is an invalid Athena catalog name.

**Expected behavior**
It should be possible to create a connector which uses the default connection string, without then having to modify the created lambda function manually.

**Connector Details (please complete the following information):**
 - Version: 2022.10.1
 - Name Redshift

**Comment by Limess** [comment]
Hmm, after some reading it seems that the idea is to _not_ add the connectors as Athena datasources, but just query at runtime as  `lambda:${AWS_LAMBDA_FUNCTION_NAME}`? But this does not allowing viewing catalog metadata/tables up front?

**Comment by henrymai** [comment]
Hi @Limess 

In regards to:
> Expected behavior
> It should be possible to create a connector which uses the default connection string, without then having to modify the created lambda function manually.

You should be able to just use the default connection string now if you do not have any other connection strings defined after this patch: 65c29e4bad1d89634b30b3604abc90b4adfabc3e

Please upgrade to any version of the Redshift connector after v2023.01.1 to get this fix.

Thanks.
