### ISSUE TITLE
[BUG] Invalid argument type error when connecting Athena with connector ElasticSearch

### ISSUE THREAD

**Issue by goyalritik** [awslabs/aws-athena-query-federation#686]
I am trying to query data from ES using Athena connector, it works fine when I am querying few attributes but it throws Invalid Argument type error when I try to get whole table.

`GENERIC_USER_ERROR: Encountered an exception[java.lang.IllegalArgumentException] from your LambdaFunction[arn:aws:lambda:XXXXXXXXX:XXXXXXX:function:XXXXXXXXXX] executed in context[S3SpillLocation{bucket='athenadataspillbucket', key='athena-spill/XXXXXXXXXXXXXXX/XXXXXXXXXXX', directory=true}] with message[Invalid argument type. Expecting a Map, but got: java.util.ArrayList]`

**Connector Details:**
 - Version: 2022.10.1
 - Name Athena-ElasticSearch

**Comment by kevindekemele** [comment]
I have the same issue for dynamoDB connector! The schema was taken from glue connector, there it is defined as a 'struct'.
