### ISSUE TITLE
[BUG] Athena UDF query fails with error: Could not initialize class org.apache.arrow.memory.RootAllocator when extending UserDefinedFunctionHandler

### ISSUE THREAD

**Issue by DovratShoval** [awslabs/aws-athena-query-federation#687]
I'm extending UserDefinedFunctionHandler and when I run UDF query from Athena console I'm getting:
GENERIC_USER_ERROR: Encountered an exception[java.lang.NoClassDefFoundError] from your LambdaFunction[digital-insights-bmh-udf-lambda-staging] executed in context[ping] with message[Could not initialize class org.apache.arrow.memory.RootAllocator]

I'm following this guide https://docs.aws.amazon.com/athena/latest/ug/querying-udf.html#udf-creating-and-deploying 
I use java 1.8 and aws-athena-federation-sdk 2021.30.1
I have no other dependencies in my pom so this class is part of the aws-athena-federation-sdk dependencies

This is the only dependency in my pom file:
<groupId>com.amazonaws</groupId>
<artifactId>aws-athena-federation-sdk</artifactId>
<version>2021.30.1</version>

This it the output of  "mvn dependency:tree -Ddetails=true" :
[INFO] \- com.amazonaws:aws-athena-federation-sdk:jar:2021.30.1:compile
[INFO]    +- com.amazonaws:aws-java-sdk-secretsmanager:jar:1.11.800:compile
[INFO]    |  +- com.amazonaws:aws-java-sdk-core:jar:1.11.800:compile
[INFO]    |  |  +- org.apache.httpcomponents:httpclient:jar:4.5.9:compile
[INFO]    |  |  |  \- org.apache.httpcomponents:httpcore:jar:4.4.11:compile
[INFO]    |  |  +- software.amazon.ion:ion-java:jar:1.0.2:compile
[INFO]    |  |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:jar:2.6.7:compile
[INFO]    |  |  \- joda-time:joda-time:jar:2.8.1:compile
[INFO]    |  \- com.amazonaws:jmespath-java:jar:1.11.800:compile
[INFO]    +- com.amazonaws:aws-java-sdk-glue:jar:1.11.800:compile
[INFO]    +- com.amazonaws:aws-java-sdk-athena:jar:1.11.800:compile
[INFO]    +- org.apache.arrow:arrow-vector:jar:3.0.0:compile
[INFO]    |  +- org.apache.arrow:arrow-format:jar:3.0.0:compile
[INFO]    |  +- com.fasterxml.jackson.core:jackson-core:jar:2.11.4:compile
[INFO]    |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.11.4:compile
[INFO]    |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.11.4:compile
[INFO]    |  +- commons-codec:commons-codec:jar:1.10:compile
[INFO]    |  +- io.netty:netty-common:jar:4.1.48.Final:compile
[INFO]    |  \- com.google.flatbuffers:flatbuffers-java:jar:1.9.0:compile
[INFO]    +- org.apache.arrow:arrow-memory-core:jar:3.0.0:compile
[INFO]    |  \- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO]    +- org.apache.arrow:arrow-memory-netty:jar:3.0.0:compile
[INFO]    |  \- io.netty:netty-buffer:jar:4.1.48.Final:compile
[INFO]    +- com.amazonaws:aws-lambda-java-core:jar:1.2.0:compile
[INFO]    +- com.amazonaws:aws-java-sdk-lambda:jar:1.11.800:compile
[INFO]    +- com.amazonaws:aws-java-sdk-s3:jar:1.11.800:compile
[INFO]    +- com.amazonaws:aws-java-sdk-kms:jar:1.11.800:compile
[INFO]    +- com.google.guava:guava:jar:29.0-jre:compile
[INFO]    |  +- com.google.guava:failureaccess:jar:1.0.1:compile
[INFO]    |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[INFO]    |  +- org.checkerframework:checker-qual:jar:2.11.1:compile
[INFO]    |  +- com.google.errorprone:error_prone_annotations:jar:2.3.4:compile
[INFO]    |  \- com.google.j2objc:j2objc-annotations:jar:1.3:compile
[INFO]    +- org.slf4j:slf4j-api:jar:1.7.30:compile
[INFO]    +- org.slf4j:jcl-over-slf4j:jar:1.7.30:compile
[INFO]    +- org.bouncycastle:bcprov-jdk15on:jar:1.61:compile
[INFO]    \- org.apache.commons:commons-lang3:jar:3.9:compile

**Comment by DovratShoval** [comment]
it was not a bug, but a problematic configuration of the maven-shade-plugin

**Comment by madhur** [comment]
> it was not a bug, but a problematic configuration of the maven-shade-plugin

Can you explain more, I am getting the same error
