### ISSUE TITLE
[Cloudformatio/CDK] General question

### ISSUE THREAD

**Issue by kamipatel** [awslabs/aws-athena-query-federation#688]
I have a question that I don't think is related to a bug or feature request. 

Hi,
Is there a way to make it part of Cloudformation stack or CDK? That way user does not have to do manual configuration of this.
Thanks,
Kam

**Comment by henrymai** [comment]
You should be able to just use one of the .yaml files as a nested application.

Here are some guides:

https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-nested-applications.html

https://docs.aws.amazon.com/prescriptive-guidance/latest/patterns/automate-deployment-of-nested-applications-using-aws-sam.html

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-nested-stacks.html
