### ISSUE TITLE
[DOCUMENTATION] Snowflake connector README has ❄️ instead of `:snowflake:` in connection strings 

### ISSUE THREAD

**Issue by mreno-EBSCO** [awslabs/aws-athena-query-federation#691]
There are several connection strings in the snowflake connector README that have a ❄️ instead of `:snowflake:`. 

Here's an example: 
![image](https://user-images.githubusercontent.com/31450518/165772701-ccda0337-4d2c-45a4-b6eb-ef6d71e4ab74.png)

**Comment by avirtuos** [comment]
Thanks for calling this out. While i think the emoji is pretty cheerful, it does make it pretty annoying to copy-paste a usable connection string enable. I submitted a PR to fix it.
