### ISSUE TITLE
[BUG] Rounding numbers with connector Redshift connector

### ISSUE THREAD

**Issue by davisb2** [awslabs/aws-athena-query-federation#694]
**Describe the bug**
The lambda is rounding numbers to whole number when querying in athena.  When the same query is run in redshift, rounding does not occur

**To Reproduce**
1. Go to redshift, create a table, add in a decimal value
2. Create a lambda connector to athena using the athena redshift connector
3. Query the table in redshift
4. Query the same table in athena
5. The value in athena will be rounded and the value in redshift will be unaltered

**Expected behavior**
Value in Athena should match value in Redshift

**Connector Details (please complete the following information):**
 - Version: version 2022.10.1
 - Name Redshift

**Comment by akuzin1** [comment]
After looking into the issue you have been experiencing, I've been unable to recreate it following your provided steps. 

1. I created a table in redshift with the following schema:
`CREATE TABLE <redshift_database>.<schema>."sample_data"(name varchar, value DECIMAL(18, 6));`
**sample_data** table has two variables - **name** which is a _string_, and **value** which is a _Decimal_ value, that will have a scale of 18 and precision of 6 digits.

3. Then I inserted some values into the table, and ran a `select *` query in redshift, retrieving the following results:

![Screen Shot 2022-09-15 at 11 27 10 AM](https://user-images.githubusercontent.com/111004764/190444369-11e8430d-be5c-4e47-bf9c-6e3e4b3334db.png)

4. Afterwards, I deployed the Athena Redshift Connector, and attempted to run the same query in Athena where I got the following results:

![Screen Shot 2022-09-15 at 11 55 40 AM](https://user-images.githubusercontent.com/111004764/190451184-f91fe053-7566-4db5-9beb-4eb24956cfd4.png)

If you can provide the schema you are using for your Redshift table, that would give me further insight into what the potential problem can be and would allow me to better help you.

**Comment by henrymai** [comment]
Closing this out since there hasn't been any updates from the original poster of this issue.
