### ISSUE TITLE
ThrottlingInvoker to conservative with cloudwatch-metrics

### ISSUE THREAD

**Issue by avirtuos** [awslabs/aws-athena-query-federation#70]
When testing the cloudwatch-metrics connector I noticed it was too easy for me to write a query that would result in thrashing against cloudwatch getMetricData(...) API. This was surprising to me because ThrottlingInvoker was indeed kicking in and reducing the TPS to 1 for each running Lambda. However, it seems as though in aggregate Athena's minimum concurrency when peak congestion control active was still high enough to overwhelm the typical cloudwatch-metrics account limits. As such this task is to:

1. Reproduce the issue and confirm the above behavoir.
1. Use lower (bigger back off, less frequent calls) for the ThrottlingInvoker used by cloudwatch-metrics. It currently uses the default ThrottlingInvoker config. Don't change the default, just use the builder in the cloudwatch-metrics connector to build a custom one for cw metrics.
1. Update the README for the connector to recommend using a lower default concurrency in the Lambda console for this connector so as to override Athena's minimum concurrency.
1. Update our docs to have a better example query which is less likely to catch dozens of individual metrics and thus produces lower concurrency.
1. We should also consider changing how we form splits so that we make fewer calls to GetMetricData by pulling up to 30 metrics in each call as recommended by CW team

**Comment by atennak1** [comment]
https://github.com/awslabs/aws-athena-query-federation/pull/71 address 1, 2, and 5.  3 and 4 are probably no longer be necessary so resolving this.
