### ISSUE TITLE
[BUG]  Could not resolve dependencies with connector athena-cloudwatch-metrics

### ISSUE THREAD

**Issue by RattyMyles** [awslabs/aws-athena-query-federation#714]
**Describe the bug**
When installing the athena-cloudwatch-metrics using "mvn clean install -DskipTests", we receive this error message:
"[ERROR] Failed to execute goal on project athena-cloudwatch-metrics: Could not resolve dependencies for project com.amazonaws:athena-cloudwatch-metrics:jar:2022.22.1: Failed to collect dependencies at com.amazonaws:aws-athena-federation-sdk:jar:2022.22.1: Failed to read artifact descriptor for com.amazonaws:aws-athena-federation-sdk:jar:2022.22.1: Could not find artifact com.amazonaws:aws-athena-query-federation:pom:${aws-athena-query-federation.version} in central (https://repo.maven.apache.org/maven2)"

**To Reproduce**
"cd ${WORKING_DIR}

git clone https://github.com/awslabs/aws-athena-query-federation.git

cd ${WORKING_DIR}/aws-athena-query-federation/athena-federation-sdk/

mvn clean install -DskipTests

cd ${WORKING_DIR}/aws-athena-query-federation/athena-cloudwatch-metrics/

mvn clean install -DskipTests

mv ${WORKING_DIR}/aws-athena-query-federation/athena-cloudwatch-metrics/target/athena-cloudwatch-metrics-2022.22.1.jar ${WORKING_DIR}/aws-athena-query-federation/athena-cloudwatch-metrics/target/create_athena_cloudwatch.jar

cp ${WORKING_DIR}/aws-athena-query-federation/athena-cloudwatch-metrics/target/create_athena_cloudwatch.jar "${CI_PROJECT_DIR}/dist""

**Expected behavior**
Expected to obtain "athena-cloudwatch-metrics-2022.22.1.jar" after it installs.

**Screenshots / Exceptions / Errors**
If applicable, add screenshots, exception stack traces, or error messages to help explain your problem.  Stack traces for exceptions thrown by your Connector can be found in CloudWatch Logs under the 'aws/lambda/<Lambda_function_name>' log group.

**Connector Details (please complete the following information):**
 - Version: CodeUri: "./target/athena-cloudwatch-metrics-2022.22.1.jar"

**Comment by henrymai** [comment]
Try again with the 2022.23.1 release. I just tried it with a toy project depending on it and it works now:

```
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from central: https://repo.maven.apache.org/maven2/com/amazonaws/aws-athena-federation-sdk/2022.23.1/aws-athena-federation-sdk-2022.23.1.pom
Downloaded from central: https://repo.maven.apache.org/maven2/com/amazonaws/aws-athena-federation-sdk/2022.23.1/aws-athena-federation-sdk-2022.23.1.pom (11 kB at 20 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/com/amazonaws/aws-athena-query-federation/2022.23.1/aws-athena-query-federation-2022.23.1.pom
Downloaded from central: https://repo.maven.apache.org/maven2/com/amazonaws/aws-athena-query-federation/2022.23.1/aws-athena-query-federation-2022.23.1.pom (14 kB at 113 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/com/amazonaws/aws-java-sdk-athena/1.11.800/aws-java-sdk-athena-1.11.800.pom
Downloaded from central: https://repo.maven.apache.org/maven2/com/amazonaws/aws-java-sdk-athena/1.11.800/aws-java-sdk-athena-1.11.800.pom (3.6 kB at 35 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/com/amazon/ion/ion-java/maven-metadata.xml
Downloaded from central: https://repo.maven.apache.org/maven2/com/amazon/ion/ion-java/maven-metadata.xml (794 B at 9.0 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-databind/maven-metadata.xml
Downloaded from central: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-databind/maven-metadata.xml (5.8 kB at 57 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/dataformat/jackson-dataformat-cbor/maven-metadata.xml
Downloaded from central: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/dataformat/jackson-dataformat-cbor/maven-metadata.xml (3.7 kB at 35 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/com/amazonaws/aws-athena-federation-sdk/2022.23.1/aws-athena-federation-sdk-2022.23.1.jar
Downloading from central: https://repo.maven.apache.org/maven2/com/amazonaws/aws-java-sdk-athena/1.11.800/aws-java-sdk-athena-1.11.800.jar
Downloaded from central: https://repo.maven.apache.org/maven2/com/amazonaws/aws-java-sdk-athena/1.11.800/aws-java-sdk-athena-1.11.800.jar (432 kB at 640 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/com/amazonaws/aws-athena-federation-sdk/2022.23.1/aws-athena-federation-sdk-2022.23.1.jar (537 kB at 538 kB/s)
```
