### ISSUE TITLE
[BUG]  Invalid connection parameter name databaseTerm with connector Teradata

### ISSUE THREAD

**Issue by Nav25oct** [awslabs/aws-athena-query-federation#723]
**Describe the bug**

Getting below error when trying to connect Teradata

Failed to invoke lambda function due to com.amazonaws.services.lambda.invoke.LambdaFunctionException: 1536: java.sql.SQLException: [Teradata JDBC Driver] [TeraJDBC 17.10.00.27] [Error 1536] [SQLState HY000] Invalid connection parameter name databaseTerm

**To Reproduce**

Install Teradata Vantage Developer on EC2 install by using following Marketplace offering
https://aws.amazon.com/marketplace/server/fulfillment?deliveryMethod=8c69cadc801424177bca261a80010b20&productId=3abbb0a4-5207-4200-9ffd-694bb3ae6359&region=us-east-1&version=0a1a7c6d-76b8-4689-bb94-fdf42c88f593&ref_=cfg_full_continue

Follow steps to configure teradata federation - 
https://docs.amazonaws.cn/en_us/athena/latest/ug/athena-prebuilt-data-connectors-teradata.html

Trying to connect - Teradata using Athena federation from athena console.

**Expected behavior**

This query should execute without any error.
select userid,databaseid from teradatafederation.dbc.AccessRights

**Screenshots / Exceptions / Errors**
If applicable, add screenshots, exception stack traces, or error messages to help explain your problem.  Stack traces for exceptions thrown by your Connector can be found in CloudWatch Logs under the 'aws/lambda/<Lambda_function_name>' log group.

**Connector Details (please complete the following information):**
 - Version: [e.g. 2020.04.01 - if you are unsure, look at the tags on the Lambda function. One of the tag should contain the version if you deployed via Serverless Application Repo.]
 - Name [e.g. redis, hbase, jdbc]
 - Athena Query IDs [if applicable]

**Additional context**
Add any other context about the problem

**Comment by henrymai** [comment]
This pull request fixes this issue: https://github.com/awslabs/aws-athena-query-federation/pull/731

**Comment by henrymai** [comment]
The new release (2022.30.2) contains the fix for this. Try it out and let us know if there are any problems.
