### ISSUE TITLE
[FEATURE] Public S3 URLs for Lambda function creation

### ISSUE THREAD

**Issue by applike-ss** [awslabs/aws-athena-query-federation#725]
**Is your feature request related to a problem? If yes, please describe.**
Not related

**Describe the solution you'd like**
I would like to see public S3 urls in the release page or somewhere else where it makes sense for the developers.

This would enable devops to use them in e.g. terraform code to create a lambda function with this code.

Currently it seems you have to use the cloudformation stack template. If you however want to manage it on your own, you have to download the release of this project and put it into your terraform module (which i would like not to do as it bloats the module and makes it less flexible)

**Describe alternatives you've considered**
Using cloudformation stack resource of the terraform aws provider, but i don't want that.

**Comment by henrymai** [comment]
If you click "Copy as SAM Resource", you can use the Serverless Application ARN that is provided within that SAM Resource template with this terraform resource: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/serverlessapplicationrepository_cloudformation_stack

I've also attached a screenshot in case it helps
![SAM_resource_arn](https://user-images.githubusercontent.com/136857/175951959-8cb08dd5-1f5b-42c6-a950-1448dda278b8.png)
.

**Comment by applike-ss** [comment]
At first I wanted to not use cloudformation for that stuff.

However having had a bit of time to think about it, there is no real reason not to use it.

Thanks for explanation.

**Comment by henrymai** [comment]
This was covered in another issue before: https://github.com/awslabs/aws-athena-query-federation/issues/418#issuecomment-923499004

Does the answer provided there help with your situation?

**Comment by applike-ss** [comment]
Thank you for your helm @henrymai!

This could have helped for my described use-case. However for my real use case there was more involved that i did not mention here. So what i did was to create all those resources via terraform and upload the code from a demo function (exported deployment package first) to an s3 bucket of my choice.
