### ISSUE TITLE
[BUG] where clause not working with postgres numeric type with connector PostgreSQL

### ISSUE THREAD

**Issue by pietvanham** [awslabs/aws-athena-query-federation#732]
**Describe the bug**
Where clause for numeric columns not working for PostgreSQL connector

**To Reproduce**
1. Create table in PostgreSQL
`create table test_fq_numeric as select cast( -7821704872881582871 as numeric(19,0)) as test_column;`
2. Query table from Athena
`select * from test_fq_numeric;`
```
#	test_column	partition_schema_name	partition_name
1	-7821704872881582871	*	*
```

`select * from test_fq_numeric where test_column = -7821704872881582871;`
```
#	test_column	partition_schema_name	partition_name
[ no results]
```

**Expected behavior**
To return the row

**Connector Details (please complete the following information):**
 - Version: 2022.24.1
 - Name: PostgresQL
 - Athena Query IDs: 9bcc4b10-d7c7-4993-bda6-e2bc3aafcde6
 - PostgreSQL version: 11.13

**Comment by akuzin1** [comment]
Thank you for reaching out! This issue should be resolved by updating to latest version of PostgreSQL connector.
