### ISSUE TITLE
[BUG] <Missing UserAgent string in SDK connection> with connector <Athena Timestream Connector>

### ISSUE THREAD

**Issue by rajeiyer** [awslabs/aws-athena-query-federation#733]
**Describe the bug**
Update the AWS Timestream SDK query connection string to add UserAgent to connections from Athena Timestream Connector to the Timestream Query service. The string `aws-athena-timestream-connector` can be added to the UserAgent string.

**To Reproduce**
N/A

**Expected behavior**
The Timestream service is trying to collect and report query usage from the Athena Timestream Connector. Including `aws-athena-timestream-connector` in the UserAgent string will help the service quantify the usage.

**Screenshots / Exceptions / Errors**
N/A

**Connector Details (please complete the following information):**
 - Version: All
 - Name: Timestrea
 - Athena Query IDs: N/A

**Additional context**
N/A

**Comment by hackett123** [comment]
This bug is resolved with PR https://github.com/awslabs/aws-athena-query-federation/pull/736. Closing issue.
