### ISSUE TITLE
DynamoDB connector chokes on some tables

### ISSUE THREAD

**Issue by houmark** [awslabs/aws-athena-query-federation#75]
Hey there,

I'm checking out this FANTASTIC improvement to Athena with a DynamoDB but hit a snag fairly early in my testing. Some tables seem to be returning data fine, while 1-2 of my tables seems to choke no matter what I do:

Your query has the following error(s):

> GENERIC_INTERNAL_ERROR: Row type must have at least one parameter
> This query ran against the "default" database, unless qualified by the query. Please post the error message on our forum or contact customer support with Query Id: e7ab04c2-bcb1-4eaa-9cfc-a3f176866fa1.

I've more than triple checked that my query is valid and correct.

The Query Id should help you debug I understand? I'm suspecting that this is a problem with one or more of the records in the table, though it's working normally in production for the rest of the system (Amplify with GraphQL which is pretty sensible in itself due to schemas etc.). The reason for this is that I have 3 environments of this same table, and 2 of them are breaking, while the third one is not (but it that one does not have any data).

I'd be happy to assist in any further debugging. Unfortunately, this table is also my main table, so until I figure out what's going wrong here, I will not be able to progress and I already wasted an insane amount of time trying to make Athena work with Firehose / Glue / ETL :/

**Comment by avirtuos** [comment]
Akila, can you take a look?

Based on the error message, I suspect we had some issue with schema inference or mapping a value to a struct field. Could be a bug in Athena itself or in the connector not properly creating an empty struct vs a null struct. I recall us having some issue with this in testing but thought we corrected it Athena side.

**Comment by atennak1** [comment]
Thanks @houmark for raising the issue!  I'm going to need a little more data to figure this out.  Can you provide one or more of the following?

1. In CloudWatch logs for your Lambda, there should be one or more log lines showing the table schema that the Lambda is returning to Athena.  Could you paste that here (anonymized as necessary).
2. Some sample data may help as well.  I suspect your table may contain Maps that aren't being handled correctly on our side.  Could you upload a CSV of sample data (anonymized as necessary)?  You can export to CSV directly from the DDB Console.

Thanks in advance.

**Comment by houmark** [comment]
I may be able to add more here, though this is a total goose chase and may not be related at all.

Before I discovered these new Athena connectors, I spent two weeks on and off trying to setup a Glue crawler and an ETL job to pull out data to S3.

In that process, where I'm selecting "A proposed script generated by AWS Glue", Spark 2.4, Python 3, then the Change schema option on the next page, I had trouble with setting up the field mapping in "Map the source columns to target columns."

Specifically I get this error consistently on trying to save:

```
{"service":"AWSGlue","statusCode":400,"errorCode":"InvalidInputException","requestId":"9024ff9f-1ac3-11ea-9e60-97d57cde674b","errorMessage":"No enum constant com.amazonaws.services.glue.FileFormat.DYNAMODB","type":"AwsServiceError"}
```

Since it does not seem possible to delete fields, and only do very limited changes on that step, I was unable to figure out what went wrong.

The error message points to something with `enum` but my table does not have an enum field.

Now, as I mentioned before I am using Amplify and in the Schema to setup GraphQL which resolves to DynamoDB, I once had an `enum` type for a status field, but that created some problems with Elasticsearch which we use for querying data from the UI (Elasticsearch is not suitable for counts and sum, so it's not a candidate for our the stats dashboard, which is what brought me on this long and hard Athena adventure). So to work around that we the field type to a `String` as DynamoDB saves AppSync/GraphQL `enum` field as string values anyways.

In addition, another table, which still has an `enum` type field in AppSync is querying without problems in Athena, so I may have contradicted my own theory here.

I've done a test query on all the tables we have in DynamoDB and there's just ONE table that has query issues (and this same table is "broken" for my two main environments where the table has data), but unfortunately, that's also my main table in the platform, from where I need to query stats.

I'm really hoping there's an easy solution to this, and I am willing to participate in any way that I can, so that I can move on in this project where I am already running way behind my deadline. Please let me know if there's anything I can do to help.

**Comment by houmark** [comment]
Hi @atennak1 

I missed your reply as I was writing mine. Can you give me an email where I can send this data? Anonymized won't be easy, but I have no problem email the data to you directly.

**Comment by atennak1** [comment]
Sure you can send them to tennakoo@amazon.com . Thanks!

**Comment by houmark** [comment]
Here's one error will I search for more:

```
2019-12-09 21:04:30 <f687a34e-10b3-4566-ba38-0376d52d3d55> WARN  DynamoDBMetadataHandler:doGetTable: Unable to retrieve table default from AWSGlue in database/schema com.amazonaws.services.glue.model.EntityNotFoundException: Table application-anon-prod not found. (Service: AWSGlue; Status Code: 400; Error Code: EntityNotFoundException; Request ID: 7e0bfc32-1ac7-11ea-8498-31d00e9a28de)
```

**Comment by houmark** [comment]
@atennak1 I just emailed you more logs and some sample data from the table in question.

**Comment by houmark** [comment]
Hey @atennak1 — can you confirm that you got my email with more data yesterday?

Also, I should maybe open a new issue, but after more testing, I've noticed another table where querying works fine, but some fields are missing. Those fields are nothing special (String/varchar) besides that I've recently added them (but they were added long before I connected Athena) and far from all items have a value for that field.

**Comment by avirtuos** [comment]
Are you relying on the connector's schema inference capability or using explict schema in Glue? Folks can be missing if some of your records in the table lack that column. This means when the connector scans the table to infer it's schema, it never sees those columns and as a result they may be missing  when you query.

**Comment by houmark** [comment]
I did not setup any explicit schema in Glue. I'd like to try it, but I was unable to get through the mapping process as I got the beforementioned error when doing so.

Specifically I get this error consistently on trying to save:

{"service":"AWSGlue","statusCode":400,"errorCode":"InvalidInputException","requestId":"9024ff9f-1ac3-11ea-9e60-97d57cde674b","errorMessage":"No enum constant com.amazonaws.services.glue.FileFormat.DYNAMODB","type":"AwsServiceError"}

This may also be the problem the "connector's schema inference capability" is having? I'm struggling to debug here as I cannot really see much if anything in logs and to my knowledge, there's nothing exposed in AWS consoles related to this.

**Comment by houmark** [comment]
So I tried adding the table that is working in general but has missing fields using a Glue crawler.

The crawler ran and found the missing fields (or well at least the ones I noticed was missing).

After that I verified that the table was created and had the `classification` field set to `dynamodb` and went back to Athena and refreshed the tables list in my database called `default` (which is also where the table was added to in Glue).

The Glue crawled table shows up in the list and a noticeable difference is that the table is named with `_` (underscores) instead of `-` (dashes).

Unfortunately any query to the new table results in the following error:


>Your query has the following error(s):
>
>GENERIC_USER_ERROR: Encountered an exception[com.amazonaws.services.dynamodbv2.model.ResourceNotFoundException] from your LambdaFunction[arn:aws:lambda:us-east-1:redacted:function:dynamodb] executed in context[retrieving meta-data] with message[Requested resource not found: Table: tablename_amplifyredacted_prod not found (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ResourceNotFoundException; Request ID: 6BVV1E1F00KKVI4H2L5H7HTAMVVV4KQNSO5AEMVJF66Q9ASUAAJG)]
>
> This query ran against the "default" database, unless qualified by the query. Please post the error message on our forum or contact customer support with Query Id: 75a480d0-b3eb-44df-b471-483709e9e32c.

I went to CloudWatch logs for the Lambda and found this:

```
com.amazonaws.services.dynamodbv2.model.ResourceNotFoundException: Requested resource not found: Table: tablename_amplifyredacted_prod not found (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ResourceNotFoundException; Request ID: PHMB2H6G29P3FPGH4FK088LLUFVV4KQNSO5AEMVJF66Q9ASUAAJG)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1701)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1356)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1102)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:759)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:733)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:715)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:675)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:657)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:521)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.doInvoke(AmazonDynamoDBClient.java:4230)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:4197)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.executeDescribeTable(AmazonDynamoDBClient.java:1885)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.describeTable(AmazonDynamoDBClient.java:1852)
	at com.amazonaws.athena.connectors.dynamodb.util.DDBTableUtils.lambda$getTable$0(DDBTableUtils.java:78)
	at com.amazonaws.athena.connector.lambda.ThrottlingInvoker.invoke(ThrottlingInvoker.java:186)
	at com.amazonaws.athena.connector.lambda.ThrottlingInvoker.invoke(ThrottlingInvoker.java:166)
	at com.amazonaws.athena.connectors.dynamodb.util.DDBTableUtils.getTable(DDBTableUtils.java:78)
	at com.amazonaws.athena.connectors.dynamodb.resolver.DynamoDBTableResolver.getTableMetadata(DynamoDBTableResolver.java:135)
	at com.amazonaws.athena.connectors.dynamodb.DynamoDBMetadataHandler.enhancePartitionSchema(DynamoDBMetadataHandler.java:253)
	at com.amazonaws.athena.connector.lambda.handlers.MetadataHandler.doGetTableLayout(MetadataHandler.java:333)
	at com.amazonaws.athena.connector.lambda.handlers.MetadataHandler.doHandleRequest(MetadataHandler.java:250)
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:132)
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:100)
	at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:906)
	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:341)
	at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:63)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:114)
```

What to try next?

**Comment by atennak1** [comment]
Still looking into the struct issue.  I did receive your email @houmark thanks.

It looks like Glue doesn't let you use hyphens in table names which is unfortunate because we assume the table name is the same (case insensitive).  Maybe we should use the "Location" property in Glue's StorageDescriptor if present and contains a DDB AWS ARN to map back to the actual DDB name.  Anyway I'll open a separate issue to address this.

**Comment by houmark** [comment]
Okay. The Amplify framework automatically name the tables on creation of the schema (including the hyphens) so this is something that’s out of my control.

**Comment by houmark** [comment]
Also, if the hyphen bug could be addressed then I may be able to workaround the struct issue by adding a glue crawler and remove the struct fields in the mapping which I won’t need for my queries anyways.

**Comment by atennak1** [comment]
Hi @houmark . I have a potential fix for the struct fields with https://github.com/awslabs/aws-athena-query-federation/pull/82 .

Until it's merged you can try it out by applying the patch locally: https://github.com/awslabs/aws-athena-query-federation/pull/82.patch

and then publish to your private Serverless App Repo using the `publish.sh` script, and then redeploy from there.

**Comment by houmark** [comment]
Looks great! I will try that out tonight or tomorrow max, I hope I can figure out how to do this, as this will be my first time trying it.

**Comment by houmark** [comment]
Hey @atennak1 

Sorry for the delay here, I fell sick and was offline for a couple of days. I tried building now, but I'm getting a weird error. It seems that it's trying to resolve one of the dependencies at s3-us-west-2 which it fails to do. I don't think that's something I can control. My AWS user and S3 bucket is in us-east-1.

The entire error here:
```
# Run this script from the directory of the module (e.g. athena-example) that you wish to publish.
# This script performs the following actions:
# 1. Builds the maven project
# 2. Creates a Serverless Application Package using the athena-example.yaml
# 3. Produces a final packaged.yaml which can be used to publish the application to your
#     private Serverless Application Repository or deployed via Cloudformation.
# 4. Uploads the packaged connector code to the S3 bucket you specified.
# 5. Uses sar_bucket_policy.json to grant Serverless Application Repository access to our connector code in s3.
# 6. Published the connector to you private Serverless Application Repository where you can 1-click deploy it.
Do you wish to proceed? (yes or no) yes
Proceeding...
SAR yaml found. We appear to be in the right directory.
Using AWS Region us-east-1
    "Policy": "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"serverlessrepo.amazonaws.com\"},\"Action\":\"s3:GetObject\",\"Resource\":\"arn:aws:s3:::my-bucket-name-dynamodb/*\"}]}"
[INFO] Scanning for projects...
[INFO]
[INFO] -------------------< com.amazonaws:athena-dynamodb >--------------------
[INFO] Building athena-dynamodb 1.0
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for com.amazonaws:aws-athena-federation-sdk:jar:2019.49.1 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.630 s
[INFO] Finished at: 2019-12-14T19:41:29-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project athena-dynamodb: Could not resolve dependencies for project com.amazonaws:athena-dynamodb:jar:1.0: Failure to find com.amazonaws:aws-athena-federation-sdk:jar:2019.49.1 in https://s3-us-west-2.amazonaws.com/dynamodb-local/release was cached in the local repository, resolution will not be reattempted until the update interval of dynamodb-local-oregon has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

The above error is after several retries, on the first build, it ran for quite some time and everything seemed to be working out okay, until it reached this point.

I also tried another package name, not sure what to do next.

**Comment by atennak1** [comment]
Looks like you need to build the SDK first.
```
cd ../athena-federation-sdk
mvn clean install
cd ../athena-dynamodb
../tools/publish.sh <bucket> athena-dynamodb us-east-1
```

**Comment by houmark** [comment]
Sorry, I'm Java is not my home soil.

I tried that now, but got a new error:

```
[INFO] 10 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Amazon Athena Query Federation SDK 2019.49.1 ....... FAILURE [01:15 min]
[INFO] aws-athena-query-federation 1.0 .................... SKIPPED
[INFO] athena-cloudwatch 1.0 .............................. SKIPPED
[INFO] athena-docdb 1.0 ................................... SKIPPED
[INFO] athena-redis 1.0 ................................... SKIPPED
[INFO] athena-aws-cmdb 1.0 ................................ SKIPPED
[INFO] athena-dynamodb 1.0 ................................ SKIPPED
[INFO] athena-hbase 1.0 ................................... SKIPPED
[INFO] athena-cloudwatch-metrics 1.0 ...................... SKIPPED
[INFO] athena-example 1.0 ................................. SKIPPED
[INFO] athena-tpcds 1.0 ................................... SKIPPED
[INFO] athena-jdbc 1.0 .................................... SKIPPED
[INFO] Amazon Athena Query Federation SDK Tools 1.0 ....... SKIPPED
[INFO] athena-udfs 1.0 .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:15 min
[INFO] Finished at: 2019-12-14T23:14:32-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile (default-testCompile) on project aws-athena-federation-sdk: Compilation failure: Compilation failure:
[ERROR] /Users/me/Sites/node-code/aws-athena-query-federation/athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/data/BlockTest.java:[73,24] package javax.activation does not exist
[ERROR] /Users/me/Sites/node-code/aws-athena-query-federation/athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/data/BlockTest.java:[371,125] cannot find symbol
[ERROR]   symbol:   class UnsupportedDataTypeException
[ERROR]   location: class com.amazonaws.athena.connector.lambda.data.BlockTest
[ERROR] /Users/me/Sites/node-code/aws-athena-query-federation/athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/data/BlockTest.java:[302,31] cannot find symbol
[ERROR]   symbol:   class UnsupportedDataTypeException
[ERROR]   location: class com.amazonaws.athena.connector.lambda.data.BlockTest
[ERROR] /Users/me/Sites/node-code/aws-athena-query-federation/athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/data/BlockTest.java:[632,31] cannot find symbol
[ERROR]   symbol:   class UnsupportedDataTypeException
[ERROR]   location: class com.amazonaws.athena.connector.lambda.data.BlockTest
[ERROR] /Users/me/Sites/node-code/aws-athena-query-federation/athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/data/BlockTest.java:[680,43] cannot find symbol
[ERROR]   symbol:   class UnsupportedDataTypeException
[ERROR]   location: class com.amazonaws.athena.connector.lambda.data.BlockTest
[ERROR] /Users/me/Sites/node-code/aws-athena-query-federation/athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/data/BlockTest.java:[686,31] cannot find symbol
[ERROR]   symbol:   class UnsupportedDataTypeException
[ERROR]   location: class com.amazonaws.athena.connector.lambda.data.BlockTest
[ERROR] /Users/me/Sites/node-code/aws-athena-query-federation/athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/data/BlockTest.java:[742,31] cannot find symbol
[ERROR]   symbol:   class UnsupportedDataTypeException
[ERROR]   location: class com.amazonaws.athena.connector.lambda.data.BlockTest
[ERROR] /Users/me/Sites/node-code/aws-athena-query-federation/athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/data/BlockTest.java:[792,43] cannot find symbol
[ERROR]   symbol:   class UnsupportedDataTypeException
[ERROR]   location: class com.amazonaws.athena.connector.lambda.data.BlockTest
[ERROR] /Users/me/Sites/node-code/aws-athena-query-federation/athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/data/BlockTest.java:[798,31] cannot find symbol
[ERROR]   symbol:   class UnsupportedDataTypeException
[ERROR]   location: class com.amazonaws.athena.connector.lambda.data.BlockTest
[ERROR] /Users/me/Sites/node-code/aws-athena-query-federation/athena-federation-sdk/src/test/java/com/amazonaws/athena/connector/lambda/data/BlockTest.java:[851,31] cannot find symbol
[ERROR]   symbol:   class UnsupportedDataTypeException
[ERROR]   location: class com.amazonaws.athena.connector.lambda.data.BlockTest
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

Java version is:

```
java -version    
java version "11.0.1" 2018-10-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.1+13-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.1+13-LTS, mixed mode)
```

Maybe that's a problem?

**Comment by houmark** [comment]
My Mac has both Java 8 and Java 11 which is kinda annoying, but I was able to swap to Java 8 and I'm now building the SDK.

I'll report back when I got news on building the connector.

**Comment by houmark** [comment]
OK, sorry again for the noob issues here with Java, but my main language is nodejs and I've never really done anything in Java.

I was able to build the connector and connect it, and I'm happy to report that I'm now able to query the table that was giving problems before 🚀👍 

I'll report back here if I hit anything weird, but no news is good news, so hoping to see this in the official connector soon.

Of course, the other ticket we opened in relation to the DynamoDB connector is also blocking for me, as the table interference is skipping some fields I need to query on — I gave my comments on that one and at least now I can somewhat continue on.

**Comment by atennak1** [comment]
Glad to hear it's working.

Regarding the inference skipping some fields, you can try increasing the number here: https://github.com/awslabs/aws-athena-query-federation/blob/master/athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/util/DDBTableUtils.java#L62

This will make it use a bigger scan to build the schema, so hopefully it may pick up those missing fields.

**Comment by houmark** [comment]
Nice! As I understand it, raising the number too much will slow stuff down, right?

**Comment by houmark** [comment]
@atennak1 Can you advise on updating an existing connector?

It seems that when I run the publish again, a new folder is created in S3, the app in the repository is overwritten, but I am unsure about the process to use the latest published connector in Athena. Do I need to delete the old connection and even the old app and then start all over again or is there a more simple process to make sure the connector is using the latest source code published?

**Comment by atennak1** [comment]
There's two ways:
1. If using the publish script, I would recommend first deleting the existing Lambda, bumping up the [version](https://github.com/awslabs/aws-athena-query-federation/blob/master/athena-dynamodb/athena-dynamodb.yaml#L13), running the script, and then deploying from SAR.
2. You can also update the Lambda directly:
```
cd athena-dynamodb
mvn clean install
aws lambda update-function-code --function-name <Lambda name> --zip-file fileb://target/athena-dynamodb-1.0.jar
```

**Comment by avirtuos** [comment]
Akila, can you add these steps for upgrading to the GitHub wiki?

**Comment by houmark** [comment]
If using step 1, do I then have to do anything in the console afterwards or will Athena pick  it up automatically once the new lambda is up?

**Comment by houmark** [comment]
Also deploying from SAR. Isn’t that a part of the publish script? Sorry about these questions, but I did look in the wiki/docs but it does not cover anything about upgrading.

**Comment by atennak1** [comment]
1. After running the publish script, navigate to the SAR console (you can click on the link that the script outputs).
2. Click on Available Applications on the left-hand side.
3. Click on the Private Applications tab.
4. Check the box "Show apps that create custom IAM roles or resource policies".
5. Click on AthenaDynamoDBConnector.
6. Fill out the Application settings form and click Deploy.

**Comment by atennak1** [comment]
> Akila, can you add these steps for upgrading to the GitHub wiki?

@avirtuos will do

**Comment by houmark** [comment]
Thanks again. I was now able to raise the `SCHEMA_INFERENCE_NUM_RECORDS` to a higher number and it picked up all the fields I need for now.

I'm still curious to understand if a higher value will have runtime performance issues or if this is only when listing tables? How is the interference schema cached, if at all? In any case, this works for development and to get the quieres working, but it seems that the most optimal way, and the way to ensure that especially all Number type fields end up as the correct type in Athena, is to use a Glue crawler. This also enables us to remove all fields that are in no way interesting in relation to the queries we would want to run from Athena.

Lastly, may I suggest a minor edit to point 8. and an addition of point 9 in the wiki SAR upgrade guide:

```diff
- 8. Fill out the Application settings form and click Deploy.
+ 8. Fill out the Application settings form (use the same `SpillBucket` and `AthenaCatalogName`) and click Deploy.
+ 9. The function will now replace the existing function and updated the stack as needed, but you may have to manually refresh your table list in the Athena UI to reflect changes. Reconnecting the connector is not needed.
```

**Comment by atennak1** [comment]
>I'm still curious to understand if a higher value will have runtime performance issues or if this is only when listing tables? How is the interference schema cached, if at all?

Yes this will add several tens of milliseconds to every query.  Right now there is no caching but adding caching would be a good perf improvement for warmed up Lambdas.

>it seems that the most optimal way, and the way to ensure that especially all Number type fields end up as the correct type in Athena, is to use a Glue crawler. This also enables us to remove all fields that are in no way interesting in relation to the queries we would want to run from Athena.

Makes sense.  I'll prioritize https://github.com/awslabs/aws-athena-query-federation/issues/78

>Lastly, may I suggest a minor edit to point 8. and an addition of point 9 in the wiki SAR upgrade guide

Thanks I'll incorporate this!

**Comment by avirtuos** [comment]
@atennak1 I see some of the PRs associated with this issue are now merged. Are we ok to close this? if not, what else is outstanding?

**Comment by atennak1** [comment]
Yep we can close this now.

Handled by https://github.com/awslabs/aws-athena-query-federation/pull/82
