### ISSUE TITLE
[BUG] "Unknown type for boolean" with connector Timestream !!!

### ISSUE THREAD

**Issue by yokharian** [awslabs/aws-athena-query-federation#752]
**Describe the bug**
i can't use the timestream connector, when i go into athena and it tries to **describe** the tables i get the following error 

`Failed to get metadata for table (raw_ext_fively) from lambda function due to java.lang.RuntimeException: com.amazonaws.services.lambda.invoke.LambdaFunctionException: Unknown type for boolean`

**To Reproduce**
1. create timestream database then one table with the following schema & measure (us-east-1)

**SCHEMA**

|Column					|Type		|Timestream attribute type |
|-----------------------|-----------|--------------------------|
|measure_name			| varchar	|MEASURE_NAME  			   |
|measure_value::boolean	| boolean	|MEASURE_VALUE 			   |
|measure_value::double	| double	|MEASURE_VALUE 			   |
|measure_value::varchar	| varchar	|MEASURE_VALUE 			   |
|meterId				| varchar   |DIMENSION     			   |
|time					| timestamp |TIMESTAMP     			   | 

**MEASURE**

measure_name |data_type |dimensions
|------|------|------|
|active |	boolean |	[ ( meterId, varchar ) ]|
|cost |	double |	[ ( meterId, varchar ) ]|
|currentAverage |	double |	[ ( meterId, varchar ) ]|
|demand |	double |	[ ( meterId, varchar ) ]|
|electricitySource |	varchar |	[ ( meterId, varchar ) ]|
|kVARh |	double |	[ ( meterId, varchar ) ]|
|kW |	double |	[ ( meterId, varchar ) ]|
|kWh |	double |	[ ( meterId, varchar ) ]|
|kWhRaw |	double |	[ ( meterId, varchar ) ]|
|pf |	double |	[ ( meterId, varchar ) ]|
|tariffApplied |	varchar |	[ ( meterId, varchar ) ]|
|tariffCategory |	varchar |	[ ( meterId, varchar ) ]|
|tariffExpected |	varchar |	[ ( meterId, varchar ) ]|
|voltageAverage |	double |	[ ( meterId, varchar ) ]|

3. deploy timestream athena lambda connector using [aws link](https://us-east-1.console.aws.amazon.com/lambda/home?region=us-east-1#/create/app?applicationId=arn:aws:serverlessrepo:us-east-1:292517598671:applications/AthenaTimestreamConnector)
4. Go to athena and try to use it, **you won't be able to**
6. See error ![image](https://user-images.githubusercontent.com/63127299/183743706-7f0839e1-3f41-4e61-97ef-2c4d9dbf1974.png)

**Expected behavior**
I need an odbc driver to make timestream queries, that's why I use athena as an intermediary, but it's not possible for me

**Screenshots / Exceptions / Errors**
[log-events-viewer-result.csv](https://github.com/awslabs/aws-athena-query-federation/files/9293992/log-events-viewer-result.csv)

**Connector Details (please complete the following information):**
 - Version: versions-2022.32.1
 - Name [athena-timestream]

**Additional context**
the documentation of the connector is very confusing, I can't understand how to integrate a database with glue to speed up the retrieval of metadata, (for the error that I am reporting I didn't configure anything related to glue)

**Comment by yokharian** [comment]
> I need an odbc driver to make timestream queries, that's why I use athena as an intermediary, but it's not possible for me

what i am trying to say is that i want to connect power BI to timestream, power BI does not support JDBC driver only ODBC and athena has it.

**Comment by hackett123** [comment]
Thanks for bringing this to our attention. I've merged a fix here https://github.com/awslabs/aws-athena-query-federation/pull/753

We'll push a new release within the next few weeks, but you can also package it and upload the jar to your lambda to get the fix right away.
