### ISSUE TITLE
[BUG] "Unknown type for bigint" with connector Timestream !!!

### ISSUE THREAD

**Issue by yokharian** [awslabs/aws-athena-query-federation#758]
**Describe the bug**
i can't use the timestream connector, when i go into athena and it tries to **describe** the tables i get the following error 

`Failed to get metadata for table (raw_ext_fively) from lambda function due to java.lang.RuntimeException: com.amazonaws.services.lambda.invoke.LambdaFunctionException: Unknown type for bigint`

**To Reproduce**
1. create timestream database then one table with the following schema & measure (us-east-1)

**SCHEMA**

|Column					|Type		|Timestream attribute type |
|-----------------------|-----------|--------------------------|
|measure_name			| varchar	|MEASURE_NAME  			   |
|measure_value::boolean	| boolean	|MEASURE_VALUE 			   |
|measure_value::double	| double	|MEASURE_VALUE 			   |
|measure_value::varchar	| varchar	|MEASURE_VALUE 			   |
|meterId				| varchar   |DIMENSION     			   |
|time					| timestamp |TIMESTAMP     			   | 

**MEASURE**

measure_name |data_type |dimensions
|------|------|------|
|active |	boolean |	[ ( meterId, varchar ) ]|
|cost |	double |	[ ( meterId, varchar ) ]|
|currentAverage |	double |	[ ( meterId, varchar ) ]|
|demand |	double |	[ ( meterId, varchar ) ]|
|electricitySource |	varchar |	[ ( meterId, varchar ) ]|
|kVARh |	double |	[ ( meterId, varchar ) ]|
|kW |	double |	[ ( meterId, varchar ) ]|
|kWh |	double |	[ ( meterId, varchar ) ]|
|kWhRaw |	double |	[ ( meterId, varchar ) ]|
|pf |	double |	[ ( meterId, varchar ) ]|
|tariffApplied |	varchar |	[ ( meterId, varchar ) ]|
|tariffCategory |	varchar |	[ ( meterId, varchar ) ]|
|tariffExpected |	varchar |	[ ( meterId, varchar ) ]|
|voltageAverage |	double |	[ ( meterId, varchar ) ]|

3. deploy timestream athena lambda connector using [aws link](https://us-east-1.console.aws.amazon.com/lambda/home?region=us-east-1#/create/app?applicationId=arn:aws:serverlessrepo:us-east-1:292517598671:applications/AthenaTimestreamConnector)
4. Go to athena and try to use it, **you won't be able to**
6. See error ![image](https://user-images.githubusercontent.com/63127299/184693875-14c47ac6-170b-4f74-99ec-17edf7d1b3bf.png)

**Expected behavior**
at least do a query, i want to connect power BI to timestream, power BI does not support JDBC driver only ODBC and athena has it.

**Screenshots / Exceptions / Errors**
[log-events-viewer-result.csv](https://github.com/awslabs/aws-athena-query-federation/files/9339106/log-events-viewer-result.csv)

**Connector Details (please complete the following information):**
 - Version: **latest commit** -> 685e1218daf35bf6ae4c8017a2f03928cf985d28
 - Name [athena-timestream]

**Additional context**
the documentation of the connector is very confusing, I can't understand how to integrate a database with glue to speed up the retrieval of metadata, (for the error that I am reporting I didn't configure anything related to glue)

**Comment by yokharian** [comment]
#752

**Comment by yokharian** [comment]
#752 similar issue

**Comment by henrymai** [comment]
Hi,

To reduce the amount of roundtrips for these fixes, can you give us a list of types that you use/expect to use in Timestream?

**Comment by yokharian** [comment]
> Hi,
> 
> To reduce the amount of roundtrips for these fixes, can you give us a list of types that you use/expect to use in Timestream?

hello henrymai of course, I have put them from the beginning in the **MEASURES** table in this post, is it enough with those data types or should I do something else?

**Comment by henrymai** [comment]
@yokharian 

The exception that you posted pertains to a column (`raw_ext_fively`) that does not exist in your *MEASURES* table.

**Comment by yokharian** [comment]
> @yokharian 
> 
> The exception that you posted pertains to a column (`raw_ext_fively`) that does not exist in your **MEASURES** table.
> 
> 

I ask for forgiveness, I couldn't see that the information was paginated, in total I only have these data types !
- varchar
- double
- boolean
- bigint

**Comment by henrymai** [comment]
> I ask for forgiveness @henrymai , I couldn't see that the information was paginated, in total I only have these data types !
>     varchar
>     double
>     boolean
>     bigint

No problem, thanks for providing the list of types that you need.
We can add support for `bigint` as well since that looks like the only other type that you are missing.

> I actually found the official list of possibilities!

The connector does not currently support all of those types and we do not currently have plans to support all of the possible types yet.

**Comment by yokharian** [comment]
> > I ask for forgiveness @henrymai , I couldn't see that the information was paginated, in total I only have these data types !
> > varchar
> > double
> > boolean
> > bigint
> 
> No problem, thanks for providing the list of types that you need. We can add support for `bigint` as well since that looks like the only other type that you are missing.
> 
> > I actually found the official list of possibilities!
> 
> The connector does not currently support all of those types and we do not currently have plans to support all of the possible types yet.

Hello, I fully understand that it is an additional **cost** to support each type of timestream, however, consider that the connector **does not work** at all if at least one data type **is needed,** added to the fact that timestream **does not support deleting or modifying the schema** , if by mistake you add an unsupported type, athena will stop working and **another ticket** will have to be created, so I think it would be convenient to add some **try catch,** I understand that this bug only affects the **metadata** description of a table, that is, you have to **ignore** the columns (measure_value::**unknown_type**) in favor of being **able to execute a query,** right?

**Comment by yokharian** [comment]
@henrymai hello, is there any update regarding this bug? to confirm if my message has been read
