### ISSUE TITLE
[BUG/FEATURE] Case Sensitive and Date/timestamp in Neptune Athena Connector

### ISSUE THREAD

**Issue by jinman** [awslabs/aws-athena-query-federation#759]
**Is your feature request related to a problem? If yes, please describe.**
We have several nodes and properties that are camel case and several date timestamps as datatypes. All the columntypes appear as blank and we are unable to consume the Athena neptune connector.

**Describe the solution you'd like**
Amazon DynamoDB provides casing flag which allows customers to query case sensitive column names for Quicksight consumption

**Describe alternatives you've considered**
Changing column names and datatypes is an option but typically not possible

**Additional context**
Abhishek has developed https://github.com/abhishekpradeepmishra/aws-athena-query-federation/tree/neptune-edge-support is there any chance we can merge this request as this will truly help us tremenduously.

**Comment by jinman** [comment]
Is there an update to move this to main branch/public serverless repo as we are unable to build - lots of test failures.

**Comment by henrymai** [comment]
This has been merged: https://github.com/awslabs/aws-athena-query-federation/commit/8fcad1b6d1014392fcde7158d22456035be4ac6f

Closing this out now.
