### ISSUE TITLE
StackOverflowError in the DynamoDB connector

### ISSUE THREAD

**Issue by eranation** [awslabs/aws-athena-query-federation#76]
I'm experimenting with the DynamoDB connector. It seems to work fantastically well. I do get this error for one specific table for some reason. Is this a known issue?

> GENERIC_USER_ERROR: Encountered an exception[java.lang.StackOverflowError] from your LambdaFunction[arn:aws:lambda:us-east-1:xxx:function:xxx] executed in context[retrieving meta-data] with message[java.lang.StackOverflowError]

Query Id: fe473a53-ea8d-4933-bbc5-0423fa15e0ae

**Comment by atennak1** [comment]
Thanks @eranation for raising this issue!  Definitely not known.  Could you post the stack trace from your Lambda logs?  You should be able to find them in CloudWatch under the `/aws/lambda/<lambda name>` log group.  Thanks!

**Comment by atennak1** [comment]
Closing this now as I have too little to go on in terms of debugging and have yet to see anyone else hit this.  @eranation if you could post those logs we can re-open this.
