### ISSUE TITLE
[BUG] Missing athena-jdbc.yaml in athena-jdbc/

### ISSUE THREAD

**Issue by apeyrat** [awslabs/aws-athena-query-federation#763]
**Describe the bug**
Following the README on the rebuild procedure for athena-jdbc, the sam package fails with a template file not found error.
 
**To Reproduce**
1. ../tools/publish.sh BUCKET_NAME athena-jdbc

Error displayed (running bash -x):
+ sam package --template-file athena-jdbc.yaml --output-template-file packaged.yaml --s3-bucket alain-tests --region eu-west-1
Error: Template file not found at ..../aws-athena-query-federation/athena-jdbc/athena-jdbc.yaml

**Expected behavior**
Looking at the mysql version, I see a yaml file so I'm supposing the file is missing.

**Connector Details (please complete the following information):**
 - Version: [e.g. 2020.04.01 - if you are unsure, look at the tags on the Lambda function. One of the tag should contain the version if you deployed via Serverless Application Repo.]
 - Name [e.g. redis, hbase, jdbc]
 - Athena Query IDs [if applicable]

**Additional context**

**Comment by kparwal** [comment]
Hi, thanks for writing up a bug report. However, it's important you tell us which commit/version you're using. In https://github.com/awslabs/aws-athena-query-federation/pull/662 we split out the connectors from athena-jdbc and made that a compile only library. It's not expected to launch. Do you see some kind of documentation where it says we can launch that?

If you need a specific connector, please try deploying that connector (i.e. you actually wanted postgres, please go to athena-postgres)

If you're trying to use jdbc generically, that's not supported by Athena Federation.

**Comment by apeyrat** [comment]
I cloned the repo today so using last version.
I now understood that the jdbc is not supported (but that's not clear in the readme).
About the doc I used, I used the readme in the athena-jdbc/ folder.
Alain

**Comment by hackett123** [comment]
Thanks for pointing this out Alain. I've merged a change to call this out specifically in the readme here https://github.com/awslabs/aws-athena-query-federation/pull/766
