### ISSUE TITLE
[Help] New Glue Console with Location URI with connector [athena-dynamodb]

### ISSUE THREAD

**Issue by jinman** [awslabs/aws-athena-query-federation#769]
**Describe the bug**
The new console has a validation of S3:// URI. How do we add dynamodb-db-flag?

**To Reproduce**
1. Go to new console
2. select the database and click edit
3. enter "dynamodb-db-flag" under Location URL

**Expected behavior**
accept this flag

**Screenshots / Exceptions / Errors**
<img width="961" alt="image" src="https://user-images.githubusercontent.com/4205770/187506052-5168d17c-9d88-4b86-93d6-3b5fe224aa0a.png">

**Connector Details (please complete the following information):**
Latest version of athena-dynamodb connector

**Additional context**

**Comment by henrymai** [comment]
You should be able to just do:

`s3://dynamo-db-flag`

The code I think just checks for the existence of that substring. Give it a try and let me know if it works for you.
