### ISSUE TITLE
[Help] Athena query returns no result for Select * but individual columns work with connector athena-dynamodb

### ISSUE THREAD

**Issue by jinman** [awslabs/aws-athena-query-federation#772]
**Describe the bug**
We have 5 columns in our DynamodB table (name, id, randomNumber, timestamp, value) called "a-timeseries-dev" and we can use the dynamodb connector with other dynamo queries without any issue. For this particular table, when we run the query with

SELECT * from "schema"."a-timeseries-dev"
No Results

Select randomNumber, id, timestamp, value  from "schema"."a-timeseries-dev"
results fine

select timestamp, value, name  from "schema"."a-timeseries-dev"
No Results

Select <any individual column name> from "schema"."a-timeseries-dev"
Results fine

**Expected behavior**
If the table is mapped correctly, why would select * wont work. As a result, our quicksight is also failing

**Connector Details (please complete the following information):**
latest version of dynamodb-connector

Any help will be highly appreciated.

**Comment by henrymai** [comment]
Are you using a Glue Table with the DynamoDB connector?

If so can you provide the Glue Table schema that you are using?

Do any of your columns contain casing?

What environment variables are you using with the DynamoDB connector Lambda?

**Comment by jinman** [comment]
1. I am using Glue Table with DynamoDB connector
2. 
<img width="418" alt="image" src="https://user-images.githubusercontent.com/4205770/188016442-0aca05d9-90b3-4093-a188-da21e9b05d0c.png">
3. 
<img width="426" alt="image" src="https://user-images.githubusercontent.com/4205770/188016556-7e347ba4-2940-49e2-9552-4a7a7a699041.png">
4. Cannot see any logs 



2022-09-01T14:46:26.846-07:00 | 2022-09-01 21:46:26 DEBUG QueryStatusChecker:115 - Background thread checking status of Athena query bb35d410-f6b8-4893-ad33-ccd6139693ca, attempt 2
-- | --
  | 2022-09-01T14:46:26.892-07:00 | 2022-09-01 21:46:26 INFO S3BlockSpiller:349 - write: Started spilling block of size 4369656 bytes
  | 2022-09-01T14:46:26.994-07:00Copy2022-09-01 21:46:26  WARN  S3BlockSpiller:368 - write: Encountered error while writing block.com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: SDC4FGRYZGRP2G8C; S3 Extended Request ID: YzDSByK4AO48YJJqJTS/N4Xle4XsU0bBJ1Qyv/f5BSvd2ywz+XWQgkYoaQmsp1u9m9m0WFP7at8=; Proxy: null)	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1811) ~[task/:?]	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1395) ~[task/:?]	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1371) ~[task/:?]	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145) ~[task/:?]	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802) ~[task/:?]	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770) ~[task/:?]	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744) ~[task/:?]	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704) ~[task/:?]	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686) ~[task/:?]	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550) ~[task/:?]	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530) ~[task/:?]	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5062) ~[task/:?]	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5008) ~[task/:?]	at com.amazonaws.services.s3.AmazonS3Client.access$300(AmazonS3Client.java:394) ~[task/:?]	at com.amazonaws.services.s3.AmazonS3Client$PutObjectStrategy.invokeServiceCall(AmazonS3Client.java:5950) ~[task/:?]	at com.amazonaws.services.s3.AmazonS3Client.uploadObject(AmazonS3Client.java:1812) ~[task/:?]	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1772) ~[task/:?]	at com.amazonaws.athena.connector.lambda.data.S3BlockSpiller.write(S3BlockSpiller.java:361) ~[task/:?]	at com.amazonaws.athena.connector.lambda.data.S3BlockSpiller.lambda$spillBlock$0(S3BlockSpiller.java:412) ~[task/:?]	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]	at java.lang.Thread.run(Unknown Source) [?:?] | 2022-09-01 21:46:26 WARN S3BlockSpiller:368 - write: Encountered error while writing block. com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: SDC4FGRYZGRP2G8C; S3 Extended Request ID: YzDSByK4AO48YJJqJTS/N4Xle4XsU0bBJ1Qyv/f5BSvd2ywz+XWQgkYoaQmsp1u9m9m0WFP7at8=; Proxy: null) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1811) ~[task/:?] at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1395) ~[task/:?] at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1371) ~[task/:?] at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145) ~[task/:?] at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802) ~[task/:?] at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770) ~[task/:?] at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744) ~[task/:?] at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704) ~[task/:?] at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686) ~[task/:?] at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550) ~[task/:?] at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530) ~[task/:?] at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5062) ~[task/:?] at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5008) ~[task/:?] at com.amazonaws.services.s3.AmazonS3Client.access$300(AmazonS3Client.java:394) ~[task/:?] at com.amazonaws.services.s3.AmazonS3Client$PutObjectStrategy.invokeServiceCall(AmazonS3Client.java:5950) ~[task/:?] at com.amazonaws.services.s3.AmazonS3Client.uploadObject(AmazonS3Client.java:1812) ~[task/:?] at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1772) ~[task/:?] at com.amazonaws.athena.connector.lambda.data.S3BlockSpiller.write(S3BlockSpiller.java:361) ~[task/:?] at com.amazonaws.athena.connector.lambda.data.S3BlockSpiller.lambda$spillBlock$0(S3BlockSpiller.java:412) ~[task/:?] at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?] at java.util.concurrent.FutureTask.run(Unknown Source) [?:?] at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?] at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?] at java.lang.Thread.run(Unknown Source) [?:?]

**Comment by henrymai** [comment]
@jinman

Are you seeing the spilling error in both of the following situations?
A) `select *` situation
B) ` Select randomNumber, id, timestamp, value from "schema"."a-timeseries-dev"
results fine`

If you are only seeing it for (A) and the other cases where you don't see results, then I think that's probably the main problem.

In order to resolve this problem, you will need to make sure that the DynamoDB Connector Lambda function has the correct permissions to the s3 bucket that you have set to spill to.

If you are not only seeing it for (A) and if you fix the s3 bucket permissions issue and you are still not getting results, please post the full log of the DynamoDB Connector Lambda function so that we can try to determine what's going on.

**Comment by henrymai** [comment]
Additionally, I have attached a screenshot of an attempt to repro your setup to show you that it works:
![ddb_github_issue_cant_repro](https://user-images.githubusercontent.com/136857/188049967-4025ee71-aa38-4f9c-aeef-0cf275920dad.png)

**Comment by jinman** [comment]
We are unable to fix this bug. Its only happening in `select *`

Do you think it might be due to dynamodb partition key?
Our partitionkey is `telematicsserialnumber` and sort key is `sensorName`. We dont have partKey (as in your example)

OR do you think it might be due to indexes?
We have two indexes: sensorName-index, telematicsSerialNumber-timeStamp-index

No results for `SELECT *`
No results for `SELECT value, timestamp, sensorName`

I deployed the connector using serverless repo, how do I fix the s3 bucket permissions for this connector? Is there a IAM role?

Thank you so much for @henrymai, you are a gem!

**Comment by henrymai** [comment]
In regards to why its not working for you, full logs would help me figure that out, currently I don't have enough information to go off of. But hopefully just fixing the permissions might work (see below).

> I deployed the connector using serverless repo, how do I fix the s3 bucket permissions for this connector? Is there a IAM role?

See the attached screenshot on how to setup your execution policy on the attached iam role on your lambda.

![lambda_execution_policy_spill_bucket](https://user-images.githubusercontent.com/136857/188102095-05965546-6b9b-4408-87a0-51a11c25fb45.png)

**Comment by jinman** [comment]
@henrymai This worked. We changed the bucket and the permissions. Thanks a lot for your help. Somehow the bucket name during the initial creation was not the same as the one we had. THANK YOU!

**Comment by henrymai** [comment]
Ok, so you're getting the expected results now with your `select *` queries right?
