### ISSUE TITLE
[BUG] CaseSensitive Node and Edge names with connector athena-neptune

### ISSUE THREAD

**Issue by jinman** [awslabs/aws-athena-query-federation#774]
**Describe the bug**
We are using the Athena connector with enable_caseinsensitive flag = true, This works for case sensitive (camel case) properties but does not return any results when nodes and edges are also camelcase

**To Reproduce**
1. Create a node with camelcase in neptune
2. Create Glue schema table
3. Try to connect the athena-neptune lambda connector
4. See no results

**Expected behavior**
It should match the node/edge name and return the results g.V().hasLabel('nodename') query

**Screenshots / Exceptions / Errors**
no

**Connector Details (please complete the following information):**
Latest version Athena-neptune connector

**Additional context**
Abhishek is aware of the issue and has possible fix with using table properties to specific the node name

**Comment by henrymai** [comment]
The athena-neptune connector does not have this flag. See the documentation here: https://docs.aws.amazon.com/athena/latest/ug/connectors-neptune.html
