### ISSUE TITLE
Handle Glue table name coercion

### ISSUE THREAD

**Issue by atennak1** [awslabs/aws-athena-query-federation#78]
When Glue Crawler crawls a table like a DynamoDB table, it will replace hyphens in the the table name with underscores.  Also it is likely that Glue will not allow hyphens during manual table creation.  Our current implementations of GlueMetadataHandler in all the current connectors currently assume the table name will be the same between Glue and the data source (allowing for case insensitivity).  I can think of three ways to address this:

1. Crawled tables maintain the original name of the table in the table's StorageDescriptor->Location property.  We can leverage this if present and in a known form (like an AWS ARN).
2. In the Table "Resolver" that some connectors have, we can explicitly fall back to replacing underscores with hyphens if a table lookup fails.  This can get messy and expensive if there's a mix of hyphens and underscores in the actual table name.
3. We can add an environment variable that can be used to provide a manual mapping of Glue table name to target table name.

I'm leaning toward a combination of 1 & 3.

**Comment by avirtuos** [comment]
Instead of #3 I'd recommend a table property in glue.

**Comment by houmark** [comment]
Hey guys,

My feedback here (I was hit by this).

This will affect all AWS Amplify (and possibly also AWS AppSync) generated DynamoDB tables, as Amplify creates multiple environments and a unique identifier on each table in addition to its name. Each part is divided by a hyphen.

If option 1 could be done first, then I think this will solve most of these situations. When I created the Glue crawler against my table, it automatically set the ARN of the DynamoDB table in the Location property, and that seems to be a safe mapping for the connector.

Then if someone wants or needs to override it, option 3 with a table property could be good, but I'm not sure when that would be needed if option 1 is implemented.

**Comment by atennak1** [comment]
Merged with https://github.com/awslabs/aws-athena-query-federation/commit/d3b25cb6bef865f51cfd5e19e9d9512b29f48015
