### ISSUE TITLE
Athena federated query issue with BigQuery

### ISSUE THREAD

**Issue by sanchit231** [awslabs/aws-athena-query-federation#788]
I am trying to do federated query in athena with google BigQuery but the private key we provided in AWS is getting the error below:
Failed to invoke lambda function due to com.amazonaws.services.lambda.invoke.LambdaFunctionException: Invalid PKCS#8 data.

We have provided the key in this format:
-----BEGIN PRIVATE KEY-----/n
<<<<<----key---->>>>>>/n
-----END PRIVATE KEY-----/n

But it still getting rejected. Is this format is wrong?
We also tried other iterations as well by removing or adding \n for space at different positions but nothing worked.
Could anyone help me on this with the correct format?

**Comment by namratas-trianz** [comment]
Hi, This looks like service account key issue. Can you please try to copy the service acount json key file content  and add to the AWS secret as plain text. This should work.

**Comment by chaitu0599** [comment]
Hi @namratas-trianz , could you please let me know how to do that? I am also facing the same issue..

**Comment by namratas-trianz** [comment]
Hi @sanchit231, You need to create a AWS secret and copy entire content of service account json file as plaintext as the secret value.

**Comment by sanchit231** [comment]
@namratas-trianz Thank you for your support. This issue is resolved now. We have to copy the whole key in plaintext.
