### ISSUE TITLE
[QUESTION] Why lambda is showing RequestEntityTooLargeException?

### ISSUE THREAD

**Issue by banglinh222** [awslabs/aws-athena-query-federation#793]
I have a question that I don't think is related to a bug or feature request. 

I am trying to use Athena's UDF to process some data, then this error happens:
```
GENERIC_USER_ERROR: com.facebook.presto.spi.PrestoException: Encountered an exception[Client] from your LambdaFunction[general-log-digest] executed in context[calling UDF method redact] with message[Request must be smaller than 6291456 bytes for the InvokeFunction operation (Service: AWSLambda; Status Code: 413; Error Code: RequestEntityTooLargeException
```

the request that athena node is sending to my Lambda is too big, how is this possible?
Athena should never send anything exceeding the 6mb limit to Lambda or am I missing something?

What I am trying to do is to digest general log of mysql: for each query I need its digest,
so the amount of data to process is large but should not be a problem

**Comment by hackett123** [comment]
Hi banglinh222@,

The max request size for a lambda is 6mb. Athena itself will invoke the UDF for each row in your dataset. So, you can exceed the request size limit if the actual row of data itself which you are providing as parameters to your UDF is > 6mb in size. Given that I see that your function appears to be digesting logs, these logs may be quite long (or at least one such record is > 6mb).

I haven't worked with this table before in mysql, but I supsect this is coming from your `performance_schema. events_statements_summary_by_digest` table? If so, you can find the max-sized record in that table to confirm if we're going over 6mb (keep in mind there is some extra stuff in the lambda payload, so if we're close to the limit, it might go over once we send it to lambda).

**Comment by hackett123** [comment]
We haven't heard back in around a week so I'm going to close this out because I believe my above explanation is likely the root cause. If you can follow my steps above and see no indication of any rows that would violate the 6mb row size that would be input to the UDF, feel free to re-open for some debugging.
