### ISSUE TITLE
[QUESTION] Where is MultiplexingJdbcCompositeHandler handler on released package?

### ISSUE THREAD

**Issue by zubeyiro** [awslabs/aws-athena-query-federation#797]
I have a question that I don't think is related to a bug or feature request. 

I am trying to use release package on my lambda function directly and therefore I'm have downloaded couple of different versions. But none of them has `com.amazonaws.athena.connectors.jdbc.MultiplexingJdbcCompositeHandler`. This [PR](https://github.com/awslabs/aws-athena-query-federation/pull/502/files) supposed to address that but I still cannot find it in any release starting from that one.

Here is the content of released package
<img width="391" alt="Screen Shot 2022-10-17 at 10 37 40" src="https://user-images.githubusercontent.com/7216505/196116826-71ac5d61-2a19-42f8-b089-e6648258e9ae.png">

But, when I deploy app via serverles and download the code from Lambda, I have the handlers:
<img width="1043" alt="Screen Shot 2022-10-17 at 10 38 56" src="https://user-images.githubusercontent.com/7216505/196117107-f8d68df2-01d3-4691-8768-99a7bc80f19e.png">

Where can I find correct package that contains JDBC handler?

**Comment by henrymai** [comment]
Hi,

That class was deleted a while ago: https://github.com/awslabs/aws-athena-query-federation/commit/2e44c81f16490589f311e225d918c5f98f166dda

You may be deploying an old unsupported connector from the Serverless Application Repository that still contains that class.

Can you provide a link to the connector that you deployed to obtain this class and we will get it unlisted.

**Comment by henrymai** [comment]
Right, so that connector is old and unsupported at this point, see this: https://github.com/awslabs/aws-athena-query-federation/tree/master/athena-jdbc#amazon-athena-lambda-jdbc-connector

If you want an up to date jdbc connector, you will need to get one of the database specific jdbc connectors (like `athena-mysql`, `athena-oracle`, etc).

**Comment by zubeyiro** [comment]
@henrymai yes I saw this but I couldnt find any release regarding to separate connectors, is there another page that I can follow and get the release?

**Comment by zubeyiro** [comment]
great, that was what I was looking for. I was able to build myself but if there is any official release ofc I'd like to use it.

Thanks @henrymai for the help

**Comment by henrymai** [comment]
@zubeyiro 

Just to follow up on this, we now have official connector jar builds attached to our releases: https://github.com/awslabs/aws-athena-query-federation/releases/tag/v2023.13.1
