### ISSUE TITLE
[BUG] Quick Start Guide can't be finished because of wrong jar name in validate_connector.sh

### ISSUE THREAD

**Issue by jiajie999** [awslabs/aws-athena-query-federation#798]
**Describe the bug**

**To Reproduce**
Just follow the steps in [Quick Start Guide](https://github.com/awslabs/aws-athena-query-federation/tree/master/athena-example), the [step 6](https://github.com/awslabs/aws-athena-query-federation/tree/master/athena-example#step-6-validate-our-connector) will get an error message.
```Error: Could not find or load main class com.amazonaws.athena.connector.validation.ConnectorValidator
Caused by: java.lang.ClassNotFoundException: com.amazonaws.athena.connector.validation.ConnectorValidator
```

**Expected behavior**
No error messages should be print

**Screenshots / Exceptions / Errors**
![image](https://user-images.githubusercontent.com/1141716/196622715-ff355bcb-1861-4d56-aaf6-7c9b6d8ce16d.png)

**Comment by jiajie999** [comment]
After fixing the jar name everything works fine. https://github.com/awslabs/aws-athena-query-federation/pull/799
![image](https://user-images.githubusercontent.com/1141716/196625960-3234239b-99ee-4581-b5f4-d06a698ce5b8.png)

**Comment by ykrystal** [comment]
Thanks for resolving! Closing this issue.
