### ISSUE TITLE
[BUG] Check only last row count with connector snowflake

### ISSUE THREAD

**Issue by rs-alexis** [awslabs/aws-athena-query-federation#809]
**Describe the bug**
It seems like there is a potential bug in the snowflake connector.
Looking at [this line](https://github.com/awslabs/aws-athena-query-federation/blob/master/athena-snowflake/src/main/java/com/amazonaws/athena/connectors/snowflake/SnowflakeMetadataHandler.java#L183) in the code. We loop over all the rows in the ResultSet and assign the row_count value to the `totalRecordCount` variable:

- There we'll only get the last row rowCount and ignore all the other rows. Is that intended?
- Do we want to sum up the count instead of overriding the value at every single loop?
- Do we want to change that [one query ](https://github.com/awslabs/aws-athena-query-federation/blob/3e8e4ec99e3ff702bf72a8c044409283707dce8b/athena-snowflake/src/main/java/com/amazonaws/athena/connectors/snowflake/SnowflakeMetadataHandler.java#L93) to also filter by database/schema name?

The result of that issue is that my Athena snowflake query does return an empty set of result.

**To Reproduce**
1. Have multiple time the same snowflake table but with different schema within the same wharehouse & db.
2. All the tables have rows except the last one.
3. Try to query a table that has rows.

**Expected behavior**
It should return the rows for a given schema no matter if other schema with the same table has no rows.

**Screenshots / Exceptions / Errors**
Athena connector query with the results (using the Snowflake UI):
![Screen Shot 2022-10-21 at 3 19 41 PM](https://user-images.githubusercontent.com/56841736/197296811-91a3c263-e432-4f6d-9537-b19e54f0c2b4.png)
Logs: 
![Screen Shot 2022-10-21 at 3 21 51 PM](https://user-images.githubusercontent.com/56841736/197297011-8185d227-fda7-44cf-9397-4a8522fca21f.png)

**Connector Details (please complete the following information):**
 - Version: 2022.42.2
 - Name: Snowflake
 - Athena Query IDs: dfe38cbf-49da-4bd3-b56d-e5d80375c77b

**Comment by henrymai** [comment]
PR that fixes this: https://github.com/awslabs/aws-athena-query-federation/pull/817

This will be included in the next release.

**Comment by henrymai** [comment]
Released in 2022.44.2
