### ISSUE TITLE
[QUESTION] AthenaJdbcConnector gone if so any replacement from SAM repo?

### ISSUE THREAD

**Issue by victorskl** [awslabs/aws-athena-query-federation#815]
I have a question that I don't think is related to a bug or feature request. 

Hello there;

Our TF code deploy `AthenaJdbcConnector` like this
https://github.com/umccr/infrastructure/blob/57eae920bcdb4bc986e5e8987c25b70f8dabc7e7/terraform/stacks/umccr_data_portal/athena.tf#L8-L42

From #797, find that, are you removing this `AthenaJdbcConnector` from SAM application repo?

![image](https://user-images.githubusercontent.com/4586509/197979928-b44ec9c4-f541-4742-abfe-605bedd0d3e0.png)

Understand the deprecation. However, it kinda hard break our setup and, therefore prod environment, etc. If `AthenaJdbcConnector` is gone, are there any drop-in replacement that I can pull from SAM application repo? How you would advice I should migrate/upgrade it to newer relevant one, gracefully.

Thanks

**Comment by henrymai** [comment]
Hi @victorskl

Sorry for the hard break. You should be able to just use the AthenaMySQLConnector instead.
It should be a drop in replacement given what I see in your lines that you've linked.

You can update your tf file as follows:

```
  name             = "AthenaMySQLConnector"
  application_id   = "arn:aws:serverlessrepo:us-east-1:292517598671:applications/AthenaMySQLConnector"
  semantic_version = "20222.42.2"
```

Here is also a link to the new connector:
https://us-east-1.console.aws.amazon.com/lambda/home?region=us-east-1#/create/app?applicationId=arn:aws:serverlessrepo:us-east-1:292517598671:applications/AthenaMySQLConnector

**Comment by victorskl** [comment]
Thanks for quick response. Awesome! I will try that now.

**Comment by victorskl** [comment]
Update:

Yep. That fix it. 

Though, running TF plan will try ping, now un-avail `AthenaJdbcConnector` SAM repo link.  

```
terraform plan

...
...
aws_serverlessapplicationrepository_cloudformation_stack.athena_jdbc_connector: Refreshing state... [id=arn:aws:cloudformation:ap-southeast-2:<snip>:stack/serverlessrepo-AthenaJdbcConnector/<snip>]
╷
│ Error: error getting Serverless Application Repository application (arn:aws:serverlessrepo:us-east-1:292517598671:applications/AthenaJdbcConnector, v2022.4.1): AccessDeniedException:
│   status code: 403, request id: <snip>
│
│   with aws_serverlessapplicationrepository_cloudformation_stack.athena_jdbc_connector,
│   on athena.tf line 8, in resource "aws_serverlessapplicationrepository_cloudformation_stack" "athena_jdbc_connector":
│    8: resource "aws_serverlessapplicationrepository_cloudformation_stack" "athena_jdbc_connector" {
```

I have to skip TF refresh. And that does the trick.

```
terraform plan -refresh=false
terraform apply -refresh=false
```

**Comment by henrymai** [comment]
I'm not that familiar with TF so I'm not sure what the problem is, but if its fixed for you, then that's great.
