### ISSUE TITLE
[FEATURE] Feature request - support Azure Data Explorer

### ISSUE THREAD

**Issue by shazi7804** [awslabs/aws-athena-query-federation#820]
Please add support for Azure Data Explorer. See https://azure.microsoft.com/en-us/products/data-explorer/

**Comment by hackett123** [comment]
If you are looking for an Azure Data Explorer connector, you can engage with your AWS support representative or account manager to get it onto the product team's radar. The Athena service team currently has no plans to add a new connector for Azure Data Explorer.
