### ISSUE TITLE
[BUG] lambda connector not able to convert Bigint in Athena Version 3

### ISSUE THREAD

**Issue by sivasankarig** [awslabs/aws-athena-query-federation#822]
**Describe the bug**
I have a table in Dynamodb, with column name "Timestamp" (sample value: 1667354412793), which is a number of type bigint. When a simple query of "select *" on Athena 2 fetches the results the type converted to decimal(38,9). Unfortunately, it fails with Athena Version 3 with below error

GENERIC_INTERNAL_ERROR: Exception while processing column LambdaColumnHandle{name='timeStamp', type=decimal(38,9), comment='null'}

**To Reproduce**
1. Create a DynamoDB table with a json file having Column value as mentioned in description
2. Insert the sample data (from the XXX.json) by creating an item for each on the table
3. Go to Athena and create a new data source with DynamoDB. (create a lambda function)
4. Go to Athena Query Editor (version 3 engine) and choose the created data source and default database. The DynamoDB table should be visible under "Tables".
5. Run a SELECT query against the table and you should receive the same GENERIC_INTERNAL_ERROR.
Note : In version 2 engine, bigint converts to decimal(38,9) and the query runs successfully

**Expected behavior**
The simple query should run both in Version 2 and 3, with bigint as data type. 

**Screenshots / Exceptions / Errors**
If applicable, add screenshots, exception stack traces, or error messages to help explain your problem.  Stack traces for exceptions thrown by your Connector can be found in CloudWatch Logs under the 'aws/lambda/<Lambda_function_name>' log group.

**Connector Details (please complete the following information):**
 - Version: [e.g. 2020.04.01 - if you are unsure, look at the tags on the Lambda function. One of the tag should contain the version if you deployed via Serverless Application Repo.]
 - Name [e.g. redis, hbase, jdbc]
 - Athena Query IDs [if applicable]

**Additional context**

**Comment by henrymai** [comment]
Thanks for submitting this bug, we know this is an issue and we have a fix that will be coming in a future update of Athena.

**Comment by burhan94** [comment]
Hi, 

This should be fixed now in all regions. Please let us know if you continue to have issues.

**Comment by henrymai** [comment]
This is fixed now. Thanks @burhan94 for the fix.
