### ISSUE TITLE
[QUESTION]I am getting error: Failed to invoke lambda function

### ISSUE THREAD

**Issue by maya-25** [awslabs/aws-athena-query-federation#823]
I would like connect athena with oracle. But it always showing me error
**Failed to invoke lambda function due to com.amazonaws.services.lambda.invoke.LambdaFunctionException: XXXX: java.sql.SQLException: Invalid Oracle URL specified.** 

I am giving the oracle connection string as decribed in documentation in [(https://aws.amazon.com/blogs/big-data/query-your-oracle-database-using-athena-federated-query-and-join-with-data-in-your-amazon-s3-data-lake/)]

like this : oracle://jdbc:oracle:thin:${oracle-athena}@//ora19csource.c7jzerofc1jp.us-east-2.rds.amazonaws.com:1521/ORCL
or also oracle://jdbc:oracle:thin://ora19csource.c7jzerofc1jp.us-east-2.rds.amazonaws.com:1521/ORCL?${oracle-athena}
or also oracle://jdbc:oracle://ora19csource.c7jzerofc1jp.us-east-2.rds.amazonaws.com:1521/ORCL?${oracle-athena}

Could anyone tell what I am doing wrong here?

**Comment by Jithendar12** [comment]
Hi Mayank,
The first connection string should work
Syntax:- oracle://jdbc:oracle:thin:${<Oracle SecretsName>}@//<Endpoint>:1521/orcl

**Comment by maya-25** [comment]
Hi Trianz,
 Tried lot of times, but as you said, i tried again, but showing me same error. where can be possible issue? 
<img width="251" alt="image" src="https://user-images.githubusercontent.com/41962603/199514734-43b8644d-1fe4-481e-aaf2-1f1a88d5bedb.png">

**Comment by Jithendar12** [comment]
please confirm me that whether password has a special charcter. If yes please enclose them within double quotes("") or flower brackets({}) in secretsName

**Comment by maya-25** [comment]
That was very good suggestion and i have special characters in password(#_ ,-). I tried with of your both suggestions. But unfortunately the error is same:(

**Comment by Jithendar12** [comment]
i mean complete password in a ""/{}

**Comment by maya-25** [comment]
Thanks a lot Jithendar, That worked now. You saved my lot of time :):)

**Comment by Jithendar12** [comment]
you're welcome
