### ISSUE TITLE
[FEATURE] Support for querying google sheets via the BigQuery connector

### ISSUE THREAD

**Issue by samyoung17** [awslabs/aws-athena-query-federation#832]
**Is your feature request related to a problem? If yes, please describe.**
Ability to query google sheets would be really useful for our analysts, so they can inject tables of parameters into their queries without having to edit code or setup ETL jobs.

**Describe the solution you'd like**
I believe this is very close to being supported out of the box. I think all that is required is to add the "https://www.googleapis.com/auth/drive" scope to the bigquery service account credentials in `BigQueryUtils.getCredentialsFromSecretsManager`. See https://cloud.google.com/bigquery/docs/samples/bigquery-auth-drive-scope#bigquery_auth_drive_scope-java for details.

**Describe alternatives you've considered**
ETL-ing google sheets via S3 and a special lambda for .csv processing. Too much config required to add a new sheet ETL for our use case.

**Additional context**

**Comment by henrymai** [comment]
A pull request to address this been merged: https://github.com/awslabs/aws-athena-query-federation/pull/864

I will close this issue out once we release a new version with this change.
If you need the change earlier you can build and deploy the connector manually.

**Comment by samyoung17** [comment]
Thanks henry!

**Comment by henrymai** [comment]
Hi @samyoung17 

2022.50.1 was released yesterday night which this feature now.
