### ISSUE TITLE
[BUG] Athena Dynamic Partition Projection Issue

### ISSUE THREAD

**Issue by baranauskase** [awslabs/aws-athena-query-federation#836]
I have a paritioned table in Athena that uses dynamic partition projection. In my case the partition key is called `latlong` and I enabled dynamic projection using the following 2 table properties:

```
'projection.latlong.type'='injected', 
'storage.location.template'='s3://my_bucket/prefix/latlong=${latlong}'
```

Running a query with a static filter on `latlong` partition key works just fine, e.g. :

```
SELECT count(*) FROM my_partitioned_table where latlong in ('50.076678_-5.235831', '50.100533_-5.259398')
```

However trying to build a dynamic list using a subquery results in an error, where the minimal reproducible example is as folows:

```
SELECT count(*) FROM my_partitioned_table where latlong in (select '50.076678_-5.235831' union select '50.100533_-5.259398')
```

The error I get is the same as not providing a filter at all when trying to query a table that is setup with a dynamic projection.

```
CONSTRAINT_VIOLATION: Injected projected partition column latlong must have only (and at least one) equality conditions in the WHERE clause!
```

Here is the region and the failed query ID, if that helps to debug this issue.

Region: eu-west-2
Query ID: d93e6502-5113-4be6-9407-de1ceca9813b

**Comment by henrymai** [comment]
Hi,

For the problem that you are describing, it sounds like a problem with Athena rather than Athena Federation (which is what this github repository is for).

To get help with your issue, you can reach out to AWS Support to open up a ticket against Athena: https://console.aws.amazon.com/support/home#/case/create?issueType=technical
