### ISSUE TITLE
[BUG] Truncated field with connector DynamoDB

### ISSUE THREAD

**Issue by jcfernandezpr** [awslabs/aws-athena-query-federation#867]
**Describe the bug**
We are using the DynamoDB connector with Athena to query some data. One of the fields inside the DynamoDB table is a nested JSON object with multiple length, but when we query the raw data in Athena it only returns the first two objects of the field. 

**To Reproduce**
1. Go to DynamoDB and create the following record:
```
"defectMap": {
    "M": {
      "0": {
        "M": {
          "name": {
            "S": "ok"
          }
        }
      },
      "1": {
        "M": {
          "defectId": {
            "N": "46898"
          },
          "name": {
            "S": "Place Point Large"
          }
        }
      },
      "2": {
        "M": {
          "defectId": {
            "N": "46899"
          },
          "name": {
            "S": "round circle empty"
          }
        }
      },
      "3": {
        "M": {
          "defectId": {
            "N": "46940"
          },
          "name": {
            "S": "4"
          }
        }
      },
      "4": {
        "M": {
          "defectId": {
            "N": "46751"
          },
          "name": {
            "S": "Osier"
          }
        }
      },
      "5": {
        "M": {
          "defectId": {
            "N": "46752"
          },
          "name": {
            "S": "Place Point"
          }
        }
      },
      "6": {
        "M": {
          "defectId": {
            "N": "46941"
          },
          "name": {
            "S": "5"
          }
        }
      }
  }
```
3. Connect it with Athena with version 2022.47.1
4. Query the record with `SELECT defectMap FROM dynamodb.table`
5. See the truncated result `{0={name=ok}, 1={name=Place Point Large, defectid=46898.000000000}}`

**Expected behavior**
The expected result shouldn't be truncated, it should be complete with all the objects inside DynamoDB, i.e. `{0={name=ok}, 1={name=Place Point Large, defectid=46898.000000000}, 2={name=round circle empty, defectid=46899}, ...} `

**Screenshots / Exceptions / Errors**
This is the record in DynamoDB in form view.
![imagen](https://user-images.githubusercontent.com/13982483/206767972-0ff090a4-8ec4-4010-a211-5d9f17a3b63b.png)
This is the record in DynamoDB in JSON view.
![imagen](https://user-images.githubusercontent.com/13982483/206768337-efa9a15b-260a-4e8f-8669-91696623b019.png)

This is what we get when querying in Athena.
![imagen](https://user-images.githubusercontent.com/13982483/206770035-2b8bad26-8d59-42b4-9f54-71730d3a8a9d.png)

**Connector Details (please complete the following information):**
 - Version: 2022.47.1
 - Name: DynamoDB

**Comment by henrymai** [comment]
Hi,

I just tried this myself and it works for me. See my attached screenshots for what I have in DDB and result from my Athena query (although my data is minorly different because I needed a partition key; not sure why your table doesn't need one).

![ddb_data](https://user-images.githubusercontent.com/136857/206825741-8b35e469-80df-43ff-836c-571549bb0623.png)

![athena_query_result](https://user-images.githubusercontent.com/136857/206825740-d351f42c-53c2-4e18-a2d5-1b5263915ee4.png)

**Comment by henrymai** [comment]
We are unable to replicate the issue and there haven't been updates on this ticket for a while. Closing this out.
