### ISSUE TITLE
[QUESTION] Receive notifications from the repository via slack?

### ISSUE THREAD

**Issue by asa-bell** [awslabs/aws-athena-query-federation#882]
Are there any plans for github and slack integration? 
Interested users can subscribe to the repository in slack. Receive notifications in slack about what's happening in the repository.

Thanks

**Comment by henrymai** [comment]
Hi @asa-bell,

If you just want notifications for what's going on with the repository, can you just go here:
https://slack.github.com/

and then in slack just do:

```
/github subscribe https://github.com/awslabs/aws-athena-query-federation
```

I don't think there's anything that has to happen on our end for you to get notifications in slack for this git repo.

**Comment by asa-bell** [comment]
Thanks for your reply.

I can subscribe other repositiories in slack.

When I subscribe this repositiory，I get error message:
```
Either the app isn't installed on your repository or the repository does not exist. Install it to proceed.
Note: You need to be an organization owner to install the app (or ask one to install it for you).
```

**Comment by henrymai** [comment]
I found a github issue about this and apparently an org owner needs to visit this link to install the "app" onto the org: https://github.com/integrations/slack/issues/559#issuecomment-424722613

I'm not an org owner so I won't be able to do that.
