### ISSUE TITLE
Address Log4J vulnerability

### ISSUE THREAD

**Issue by atennak1** [awslabs/aws-athena-query-federation#89]
https://github.com/awslabs/aws-athena-query-federation/network/alert/athena-federation-sdk-tools/pom.xml/log4j:log4j/open

**Comment by avirtuos** [comment]
We do not make us of the vulnerable TcpSocketServer and UdpSocketServer appenders that extend the vulnerable AbstractSocketServer. I've resolved the alert on the repo itself but will keep this issue open to track removing the dependency entirely.  Here is the associated issue in the open source project; https://issues.apache.org/jira/browse/LOG4J2-1863

**Comment by avirtuos** [comment]
looks like 2.9.0 is the version we need to switch to @atennak1

**Comment by atennak1** [comment]
Merged https://github.com/awslabs/aws-athena-query-federation/pull/91
