### ISSUE TITLE
Problem related to Query in Athena

### ISSUE THREAD

**Issue by hitesh1907nayyar** [awslabs/aws-athena-query-federation#93]
Hi All, 

I am running queries on Athena with configuration through Crawler,Tables and Databases. It is reading the queries from S3. First time i run the query i get the response in one line(Select * from hitesh1907). But when i run this query repetitively i keep on getting the blank rows and result of query way lower. 

I am not aware what i am doing wrong as why I am getting empty rows before actual result. 

Screenshot attached for reference. 
<img width="960" alt="ProblemwithAthena" src="https://user-images.githubusercontent.com/42111008/72865655-a96bde80-3cfe-11ea-8623-1ffb5977df2f.png">

**Comment by atennak1** [comment]
I suspect the issues you're facing were addressed recently.  Could you try publishing the latest version of the DDB connector by following the steps here?: https://github.com/awslabs/aws-athena-query-federation/wiki/How_To_Build_A_Connector_or_UDF . We've made some updates recently but have not yet cut a new release in Serverless App Repo.

**Comment by avirtuos** [comment]
@atennak1 Given the popularity of the DDB connector, maybe we can cut a release this week and update SAR? i'm not sure there is a downside to cutting a release even if we only have a few bug fixes ready to ship. Thoughts?

**Comment by atennak1** [comment]
Yep I was thinking the same thing.  I'll start the process.

**Comment by atennak1** [comment]
Latest version of the DDB connector was just published to SAR, so feel free to re-deploy from there.

**Comment by avirtuos** [comment]
I'm marking this as resolved since we haven't received additional details and it seems this make already be fixed. If you are still facing this issue please reopen and we will be happy to assist further.
