### ISSUE TITLE
[BUG] PostgreSQL Monetary types are not queryable

### ISSUE THREAD

**Issue by danielcmessias** [awslabs/aws-athena-query-federation#941]
**Describe the bug**

If you have a [Monetary](https://www.postgresql.org/docs/current/datatype-money.html) column in Postgres and try to query in Athena it will fail with the exception

```
GENERIC_USER_ERROR: Encountered an exception[java.lang.RuntimeException] from your LambdaFunction[...] executed in context[...] with message[org.postgresql.util.PSQLException: Bad value for type double : 25,000.00]
```

**To Reproduce**

1. Create a table in Postgres with a column of data type 'money'
2. Add a row with some value such as '$25,000.00'
3. Attempt to query in Athena

**Expected behavior**

You receive the column data, casted to an appropriate Athena type (double?)
 

**Screenshots / Exceptions / Errors**
If applicable, add screenshots, exception stack traces, or error messages to help explain your problem.  Stack traces for exceptions thrown by your Connector can be found in CloudWatch Logs under the 'aws/lambda/<Lambda_function_name>' log group.

**Connector Details (please complete the following information):**

serverlessrepo:applicationId | arn:aws:serverlessrepo:us-east-1:292517598671:applications/AthenaPostgreSQLConnector
serverlessrepo:semanticVersion | 2022.39.1

**Additional context**

**Comment by akuzin1** [comment]
Thank you for reaching out! The bug fix should be included in latest release, so please upgrade to version v2023.14.1 for PostgreSQL connector. Feel free to reopen issue if anything else is encountered.

**Comment by danielcmessias** [comment]
@akuzin1 Thanks!!
