### ISSUE TITLE
[QUESTION] Logging verbosity

### ISSUE THREAD

**Issue by wayne-folkes** [awslabs/aws-athena-query-federation#942]
I am having issues with my connector where it is timing out getting logs from a cloud watch log group. I can see that 4GB of data is scanned then progress stalls and then there is a timeout from the lambda function. I am wondering if there is a specific log stream(s) that causing the function to hang. But the connectior does not provide much in terms of details. Is it possible to have to logger be more verbose so I can see which which log stream is being queried?

**Comment by henrymai** [comment]
You can set the following environment variable on the connector lambda:

`ATHENA_FEDERATION_SDK_LOG_LEVEL` to `debug`

**Comment by hackett123** [comment]
Going to close this issue as we haven't had a follow-up since Henry's suggestion.
